### ISSUE TITLE
rmd vs Rmd

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#10]
I tried: 
wflow_open("MH-examples1.rmd")
Error: grepl("Rmd$", filename) is not TRUE

Two issues here. First, should we allow rmd as an alternative extension to Rmd?
Second, a more informative error message would be great.

**Comment by jdblischak** [comment]
I'll update to allow `rmd` file extensions and also replace `stopifnot` with the more verbose `if () stop()` construct to provide more informative error messages.

**Comment by jdblischak** [comment]
All the main functions now handle the file extension `.rmd` in [workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0). And in general the error messages are now more verbose. As an example, here is the new error message from the original example of an invalid file extension to `wflow_open()`:

```
> wflow_open("file.txt")
Error in wflow_open("file.txt") : 
  R Markdown files must have the extension Rmd or rmd.
```
