### ISSUE TITLE
Set title/author/date in `wflow_open`

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#100]
I am not sure whether this is really necessary, but I wonder if we can do the following:

```r
wflow_open("analysis_1.Rmd", title="Analysis 1", author="First Last", date="2018-08-08")
```

**Comment by xiangzhu** [comment]
Thanks!

>  2. wflow_open() is removed starting in workflowr 1.0.0 because the template files (e.g. chunks.R) are no longer used.

This seems a major change. I should start using 1.0.0 as soon as possible.

**Comment by jdblischak** [comment]
> This seems a major change. I should start using 1.0.0 as soon as possible.

Definitely for your new projects you'll want to use 1.0.0 (and I'd appreciate it if you'd give it a quick try sometime to give me feedback).

But for your current projects, `wflow_build()`/`wflow_publish()`/`wflow_status()` are backwards-compatible, so you don't have to update them. If you do, you can use `wflow_update()` (see the man page `?wflow_update` for details).

**Comment by xiangzhu** [comment]
I just tried 1.0.0 on a project repo. Below are what I saw. Please let me know if there is anything wrong. Thanks!

```
> library(workflowr)
Loading required package: rmarkdown
This is workflowr version 1.0.0
Run ?workflowr for help getting started

> wflow_update()
Running wflow_update in dry run mode
 [1] "./_workflowr.yml"                    "analysis/_site.yml"                  "analysis/chunks.R"                  
 [4] "analysis/include/footer.html"        "analysis/index.Rmd"                  "analysis/license.Rmd"               
 [7] "analysis/rtQTL_20170314.Rmd"         "analysis/rtQTL_20170429.Rmd"         "analysis/rtQTL_20170826.Rmd"        
[10] "analysis/rtQTL_20171228_region.Rmd"  "analysis/rtQTL_20171228_variant.Rmd"

> wflow_publish("analysis/rtQTL_20171228_region.Rmd")
Building 1 file(s):
Building analysis/rtQTL_20171228_region.Rmd
Summary from wflow_publish

**Step 1: Commit analysis files**

Summary from wflow_git_commit

The following was run: 

  $ git add analysis/rtQTL_20171228_region.Rmd 
  $ git commit -m "wflow_publish(\"analysis/rtQTL_20171228_region.Rmd\")" 

The following file(s) were included in commit 8aae701:
analysis/rtQTL_20171228_region.Rmd

**Step 2: Build HTML files**

Summary from wflow_build

Settings:


The following were built externally each in their own fresh R session: 

docs/rtQTL_20171228_region.html

Log files saved in /var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmpCeNrVC/workflowr

**Step 3: Commit HTML files**

Summary from wflow_git_commit

The following was run: 

  $ git add docs/rtQTL_20171228_region.html docs/figure/rtQTL_20171228_region.Rmd docs/site_libs 
  $ git commit -m "Build site." 

The following file(s) were included in commit fc49afa:
docs/rtQTL_20171228_region.html
```

I think the only thing I should remember is that `wflow_open` is no longer supported in 1.0.0, right?

**Comment by jdblischak** [comment]
The default for `wflow_update()` is to run in "dry-run" mode, i.e. it tells you which files will be modified without modifiying them. Try the following:

```
wflow_update(dry_run = FALSE)
wflow_build()
```

If you like the new look, then you can publish the results with:

```
wflow_publish("_workflowr.yml", "Update to 1.0", all = TRUE)
```

**Comment by xiangzhu** [comment]
Here is a brand new `Rmd` file with code chunks. It seems that it is working again.

<img width="835" alt="screen shot 2018-04-20 at 11 14 42 am" src="https://user-images.githubusercontent.com/5986023/39067057-32698b96-448c-11e8-9835-5f33fbf3329c.png">

I feel a main takeaway for me is to remember to add `output: workflowr::wflow_html` in the preamble area. To confirm, is this one line required?

**Comment by xiangzhu** [comment]
> No. It's only required if you want to change the settings from the defaults for wflow_html that are specified in analysis/_site.yml.

That's great! Now I think I am totally ready to use 1.0.0. Thanks for helping with the transition!

**Comment by jdblischak** [comment]
> That's great! Now I think I am totally ready to use 1.0.0. Thanks for helping with the transition!

Of course!
