### ISSUE TITLE
Error of running `wflow_publish(file_1.Rmd)` when writing `file_2.Rmd` 

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#101]
I come across the following type of error multiple times, and I would appreciate your advice on this matter.

I finished writing `file_1.Rmd` and then I ran `wflow_publish("file_1.Rmd")`; since this file would take a while to complete, I opened another file `file_2.Rmd` and worked on it in the *same* Rstudio session. After a while I got the following error about `file_1.Rmd`:

```r
> wflow_publish("paper1_gene_size.Rmd")
Building 1 file(s):
Building paper1_gene_size.Rmd
Build failed. See log files for full details.
stdout: /private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmprORnTf/workflowr/paper1_gene_size.Rmd-2018-04-27-18h-33m-47s-out.txt
stderr: /private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmprORnTf/workflowr/paper1_gene_size.Rmd-2018-04-27-18h-33m-47s-err.txt
NA
Error: assert_that: assertion must return a logical value
In addition: Warning message:
In doTryCatch(return(expr), name, parentenv, handler) :
  restarting interrupted promise evaluation
``` 

I went to check the log files, but they were empty:

```bash
$ du /private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmprORnTf/workflowr/paper1_gene_size.Rmd-2018-04-27-18h-33m-47s-err.txt
0	/private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmprORnTf/workflowr/paper1_gene_size.Rmd-2018-04-27-18h-33m-47s-err.txt

$ du /private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmprORnTf/workflowr/paper1_gene_size.Rmd-2018-04-27-18h-33m-47s-out.txt
0	/private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmprORnTf/workflowr/paper1_gene_size.Rmd-2018-04-27-18h-33m-47s-out.txt
```

It seems that if I let `wflow_publish("paper1_gene_size.Rmd")` run, and did not write another `Rmd` file, I could avoid this error.

**Comment by jdblischak** [comment]
Very strange! Thanks for reporting this.

I wasn't able to replicate this with workflowr 1.0.1 on Ubuntu 17.10. I created a file called `file_1.Rmd` and added the line `system("sleep 60")`. I then ran `wflow_publish("analysis/file_1.Rmd")` in the R console of RStudio. While this was running, I created a new file `file_2.Rmd` and built it using the RStudio Knit button. The `wflow_publish` command then finished without an error.

Could you please provide some more details to help me investigate more:

1. What version of workflowr are you using?
2. Is the workflowr project pre-1.0 (i.e. using `chunks.R`) or post-1.0 (i.e. using `wflow_site` and `wflow_html`)?
3. What exactly are you doing with `file_2.Rmd` while `wflow_publish` is running? Are you using the RStudio Knit button?
4. When you say it has happened multiple times, it is always the same files? Is this happening across multiple projects? Would it be possible to create a minimal reproducible example that always triggers the error?

**Comment by xiangzhu** [comment]
> 1. What version of workflowr are you using?

1.0.1 installed by calling `devtools::install_github("jdblischak/workflowr")`

> 2. Is the workflowr project pre-1.0 (i.e. using chunks.R) or post-1.0 (i.e. using wflow_site and wflow_html)?

post-1.0

> 3. What exactly are you doing with file_2.Rmd while wflow_publish is running? Are you using the RStudio Knit button?

No, I did not knit anything. I was simply writing codes in `file_2.Rmd`.

> 4. When you say it has happened multiple times, it is always the same files? Is this happening across multiple projects? Would it be possible to create a minimal reproducible example that always triggers the error?

For me it happened in multiple files of multiple repos (but not very often). I feel this type of error is hard to reproduce: if I re-ran the same file this error just disappeared; in addition, the log files are empty.

I suspect this may be just a glitch in Rstudio IDE?

**Comment by jdblischak** [comment]
OK. Some more ideas:

1. Try updating RStudio (go to Help -> Check for Updates)

1. How computationally intensive is the code in the file being published? Does it involve reading and/or writing a big file (> 1GB) or lots of small files (> 100)? Do you notice a lag when you press save on the new file being edited? Does any sort of error message from RStudio appear? The fact that the log files are empty indicates that the code fails quite drastically (i.e. if it was a normal error caused the code being run in the file, the log files would be written prior to exiting). Could you try running `top` in the Terminal while you run `wflow_publish()` to see how stressed the CPUs are?

**Comment by xiangzhu** [comment]
> Try updating RStudio (go to Help -> Check for Updates)

It seems that I am on an older Rstudio. I will let you know if I see this type of error on the latest Rstudio.
<img width="578" alt="screen shot 2018-04-30 at 1 24 09 pm" src="https://user-images.githubusercontent.com/5986023/39448493-ecdcb76a-4c79-11e8-907b-589134af926a.png">

> How computationally intensive is the code in the file being published? Does it involve reading and/or writing a big file (> 1GB) or lots of small files (> 100)? Do you notice a lag when you press save on the new file being edited? Does any sort of error message from RStudio appear? The fact that the log files are empty indicates that the code fails quite drastically (i.e. if it was a normal error caused the code being run in the file, the log files would be written prior to exiting). Could you try running top in the Terminal while you run wflow_publish() to see how stressed the CPUs are?

I will monitor these when this error occurs again (as I mentioned above, this type of error does not occur very often).

In general these files contain codes that manipulate data frames or matrices of size 100-by-20000.
