### ISSUE TITLE
Accommodating bibliographies into wflow_build() 

### ISSUE THREAD

**Issue by docmanny** [workflowr/workflowr#102]
Currently, the behavior of rmarkdown/pandoc is to append the bibliography to the very end of the file when citing in a document using a bibliography file in the YAML header as such:
```
---
title: "An example"
output: html_document
bibliography: bibliography.bib
---
Hello world. [@Citationetal]  

##Bibliography
``` 
Since in the 1.0 update, the `Session Info` and other aspects of the workflowr analysis files are automatically appended - but are appended before the bibliography it seems - the bibliography gets oddly appended to the end without any preamble.

There's a relatively simple fix [I found online](https://stackoverflow.com/questions/28815781/how-to-move-the-bibliography-in-markdown-pandoc):
```
---
title: "An example"
output: html_document
bibliography: bibliography.bib
---
Hello world. [@Citationetal]  

##Bibliography
<div id="refs"></div>
``` 

Considering the brevity of the fix, would it be possible to add that line to the template used by wflow_build() to make sure that, when a bibliography is included, that it is appended before the rest of the workflowr sections?

**Comment by jdblischak** [comment]
Thanks for reporting this, @docmanny! I like your solution, and I think it should be straightforward for me to implement. To confirm, would you always want the bibliography to appear prior to the session information? That arrangement definitely makes it easier on my end (otherwise I'd have to try and find the section header that the user used, which would be more error-prone).

**Comment by jdblischak** [comment]
I've pushed a fix to this to the dev branch. The improved behavior will be included in the next release. For now I'd recommend manually inserting `<div id="refs"></div>`.

**Comment by docmanny** [comment]
Yeah, ideally it should be the first thing appended to the document as a whole, so that if one states a "Bibliography" header as the last line, the bibliography appears immediately afterwards. Looking forward to the next update! I really like the new V1 format!

**Comment by jdblischak** [comment]
> Yeah, ideally it should be the first thing appended to the document as a whole, so that if one states a "Bibliography" header as the last line, the bibliography appears immediately afterwards.

Perfect. That is what I implemented in the dev version. It also checks for the presence of `<div id="refs"></div>`, so you won't need to change your current files after the update (i.e. workflowr won't add it a second time).

> Looking forward to the next update! I really like the new V1 format!

Thanks! I'm really glad you like it!
