### ISSUE TITLE
Error: trying to get slot "sha" from an object (class "git_commit") that is not an S4 object

### ISSUE THREAD

**Issue by egouldo** [workflowr/workflowr#104]
Very suddenly I am no longer able to knit markdown documents in a workflowr project, the following error is returned in the RMarkdown console:

```
Error in check_vc(input, r, s, opts$github) : 
  trying to get slot "sha" from an object (class "git_commit") that is not an S4 object 
Calls: <Anonymous> ... <Anonymous> -> overlay -> create_report -> check_vc
Execution halted
```
The same error is thrown when executing any of: `wflow_build()`, `wflow_status()`, `wflow_publish()`. 

Creating a new workflowr project from scratch yields the same error.

I executed `wflow_build` and then `wflow_paths` in debug mode. The issue seems to be stemming from the object `r`, which is created by `r <- try(git2r::repository(o$root, discover = TRUE), silent = TRUE)`.

In line 44 of function `flow_paths()`, `o$git <- absolute(r@path)` throws the error. I recreated the error in debug mode in the console upon executing `r@path`.

`r` returns details about the project's local and remote git repository, as follows:

```
Browse[3]> r
Local:    master /Users/Elise/Documents/PhD/ReproEcoDecisions
Remote:   master @ origin (git@github.com:egouldo/ReproEcoDecisions.git)
Head:     [317871a] 2018-05-08: update about
```

Any clues as to what's going on here? 

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] clipr_0.4.0     reprex_0.1.2    workflowr_1.0.1
[4] rmarkdown_1.9  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16      rstudioapi_0.7    knitr_1.20       
 [4] whisker_0.3-2     magrittr_1.5      devtools_1.13.5  
 [7] debugme_1.1.0     R6_2.2.2          stringr_1.3.0    
[10] tools_3.5.0       R.oo_1.22.0       git2r_0.21.0.9002
[13] withr_2.1.2       htmltools_0.3.6   assertthat_0.2.0 
[16] yaml_2.1.19       rprojroot_1.3-2   digest_0.6.15    
[19] crayon_1.3.4      callr_2.0.3       R.utils_2.6.0    
[22] memoise_1.1.0     glue_1.2.0        evaluate_0.10.1  
[25] stringi_1.2.2     compiler_3.5.0    backports_1.1.2  
[28] R.methodsS3_1.7.1
```

**Comment by jdblischak** [comment]
Thanks for the detailed bug report, @egouldo!

The culprit is `git2r_0.21.0.9002`. The development version of git2r is backwards-incompatible with the stable release. This is because the package is migrating from using S4 classes to S3 classes.

When they release the new version of git2r, I will update workflowr to use this new version. Until then, workflowr requires `git2r <= 0.21.0`:

https://github.com/jdblischak/workflowr/blob/master/DESCRIPTION#L25

Therefore you should be able to fix your problem by re-installing git2r with `install.packages("git2r")`.

**Comment by egouldo** [comment]
Thanks for the quick reply, explanation and solution. Reverting to the non-devel version of git2r fixed the problem.

**Comment by jdblischak** [comment]
Glad that fixed things! Thanks for using workflowr!
