### ISSUE TITLE
wflow_build() repeatedly generating new views of the website in IE

### ISSUE THREAD

**Issue by MarkPlatts** [workflowr/workflowr#106]
This happens after running wflow_build() several times from rstudio. Once it starts happening, it is generating tabs in IE every 15-30 seconds. I've installed the latest version of workflowr a few days ago. Can you suggest anything else that I might need to try?

Many thanks,
Mark

**Comment by jdblischak** [comment]
Hi Mark. Thanks for the bug report!

I tried replicating this on my Windows 10 machine but wasn't able to. Some questions to help me troubleshoot:

1. What version of RStudio are you using? Desktop or Server edition?

1. When you run `wflow_build()` inside of RStudio, does the website first open in the Viewer pane? This is the default behavior, and this is what happens for me. It doesn't open in Internet Explorer unless I click on the "Show in new window" button in the Viewer pane.

1. What do you get when you run `getOption("browser")`?

1. What version of Windows are you running?

1. Do you observe the same behavior with another browser, e.g. Microsoft Edge, Google Chrome, Firefox, etc.?

1. Does it ever stop opening tabs in IE? Does the number of tabs opened in IE correspond in any way to the number of times you ran `wflow_build()`? Once the `wflow_build()` command finishes, there is no way for it to continue impacting your OS. So maybe it takes a long time for IE to start the first time, and then after that it processes the subsequent `wflow_build()` calls. Just a guess.

1. Are you able to replicate the same behavior by running `wflow_view()` multiple times in a row? (note: `wflow_build()` calls `wflow_view()`, so this bypasses the step of building the files first)

**Comment by jdblischak** [comment]
@MarkPlatts Are you still experiencing this behavior with Internet Explorer? If yes, please see my questions above to help me troubleshoot the issue.

**Comment by MarkPlatts** [comment]
Thanks for following up with me John. This was something I was experiencing
on a machine I'm not currently accessing, but when I do I'll check that
this is still an problem and get back to you.

Thanks

**Comment by jdblischak** [comment]
@MarkPlatts Please re-open if you experience this issue again.
