### ISSUE TITLE
Relationship between `wflow_publish()` time and repository size

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#109]
Hi John,

I wonder if there is an obvious relationship between `wflow_publish()` time and repository size. My limited observations are that the `wflow_publish()` time of the **same** `Rmd` file tends to be longer in a larger repository (with many files) than a smaller one.

If this is the case, then we should avoid having large `workflowr` repositories?

**Comment by jdblischak** [comment]
@xiangzhu Your observation is correct. However, it won't be for long because I have fixed this speed issue on the "dev" branch in commit https://github.com/jdblischak/workflowr/commit/c06e63fda8c83e7bd0e7eebc6042c6131f148dc6.

Could you please test it out and let me know if you get increased speeds? You can test it out with the following:

```
# Install the dev branch
devtools::install_github("jdblischak/workflowr@dev")
system.time(workflowr::wflow_status())
# Install the current release
install.packages("workflowr")
system.time(workflowr::wflow_status())
```
Note that you may need to restart your R session to make sure you are using newly installed version.

**Comment by xiangzhu** [comment]
Thanks! Look forward to this new release.

Please see the test results in my laptop.

```r
> # Install the dev branch
> devtools::install_github("jdblischak/workflowr@dev")
Downloading GitHub repo jdblischak/workflowr@dev
from URL https://api.github.com/repos/jdblischak/workflowr/zipball/dev
Installing workflowr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T/RtmppUnuz4/devtoolsd8a2647e6301/jdblischak-workflowr-e16dfd9'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library'  \
  --install-tests

* installing *source* package ‘workflowr’ ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (workflowr)
> system.time(workflowr::wflow_status())
   user  system elapsed
 12.290  10.518  70.900
> # Install the current release
> install.packages("workflowr")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/macosx/el-capitan/contrib/3.5/workflowr_1.0.1.tgz'
Content type 'application/x-gzip' length 254867 bytes (248 KB)
==================================================
downloaded 248 KB


The downloaded binary packages are in
	/var/folders/dm/39__1gf52_s_9xbqrfd_46lc0000gp/T//RtmppUnuz4/downloaded_packages
> system.time(workflowr::wflow_status())

   user  system elapsed
 12.757  10.842  73.962
```

Here is my session info in case you need.

```r
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.5

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] workflowr_1.0.1   Rcpp_0.12.17      digest_0.6.15     withr_2.1.2
 [5] rprojroot_1.3-2   R.methodsS3_1.7.1 R6_2.2.2          backports_1.1.2
 [9] magrittr_1.5      git2r_0.21.0      evaluate_0.10.1   httr_1.3.1
[13] stringi_1.2.3     curl_3.2          R.oo_1.22.0       R.utils_2.6.0
[17] rmarkdown_1.10    devtools_1.13.5   tools_3.5.0       stringr_1.3.1
[21] yaml_2.1.19       compiler_3.5.0    tcltk_3.5.0       memoise_1.1.0
[25] htmltools_0.3.6   knitr_1.20
```

**Comment by jdblischak** [comment]
Strange. You didn't see much improvement. This created a huge speedup for one of @pcarbo's workflowr projects. Is your workflowr project publicly available for me to experiment with?

Also, could you please run the function `odb_blobs` twice in your workflowr project and reports the results?

```
system.time(git2r::odb_blobs())
system.time(git2r::odb_blobs())
```

**Comment by xiangzhu** [comment]
The tested repo is private and contains many files.

Below are the results.

```r
> system.time(git2r::odb_blobs())
system.time(git2r::odb_blobs())

   user  system elapsed
  9.732  10.267  68.826
> system.time(git2r::odb_blobs())
   user  system elapsed
  9.774  10.563  70.937
```

**Comment by jdblischak** [comment]
Wow. How many is "many files"? Could you please run the following for me?

```
length(git2r::commits())
length(Sys.glob("analysis/*Rmd"))
nrow(git2r::odb_blobs())
```

Also, have you been using this repo for a long time, e.g. over a year? In that case, you could try running `git gc` in the Terminal to perform manual garbage collection.

**Comment by xiangzhu** [comment]
Yes, this is one of my main working repos, and I am decomposing it into multiple new smaller repos now.

Here are the results.

```
> length(git2r::commits())
[1] 1013
> length(Sys.glob("analysis/*Rmd"))
[1] 137
> nrow(git2r::odb_blobs())
[1] 2234
```

**Comment by jdblischak** [comment]
OK. 137 R Markdown files is a lot. Did you try running `git gc` in the Terminal? For one of my long-running workflowr projects, this made a huge improvement.

**Comment by xiangzhu** [comment]
Yes, and below is the output:

```bash
$ git gc
Counting objects: 5794, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5179/5179), done.
Writing objects: 100% (5794/5794), done.
Total 5794 (delta 3474), reused 920 (delta 531)
```

Thanks again for your help!

**Comment by jdblischak** [comment]
And did running the garbage collection improve the speed?

```
system.time(git2r::odb_blobs())
system.time(git2r::odb_blobs())
```

**Comment by xiangzhu** [comment]
Yes, it did! Thanks for teaching me this trick.

```r
> system.time(git2r::odb_blobs())
   user  system elapsed 
  1.503   0.035   1.545 
> system.time(git2r::odb_blobs())
   user  system elapsed 
  1.425   0.024   1.452
```

**Comment by jdblischak** [comment]
Phew! You had me worried! I'm glad that fixed it.

So in conclusion, in the next release of workflowr, projects with as many as 137 R Markdown files will not be a problem.

I have a to-do item to send a message when `wflow_status()` takes a long time. I'll need to include the tip to run `git gc`.

**Comment by pcarbo** [comment]
Also see [this](https://stackoverflow.com/questions/28720151/git-gc-aggressive-vs-git-repack).

**Comment by xiangzhu** [comment]
I just installed workflowr version 1.1.1, and found out that `wflow_publish()` was much faster in a large repository than before. Thanks!

**Comment by jdblischak** [comment]
@xiangzhu Awesome! Glad that fixed the issue.
