### ISSUE TITLE
template - indicate which material not to delete

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#11]
when I open a template the first thing I do is delete the additional stuff..
it would be helpful if this stuff is made clear by some demarcation.
Maybe also helpful if there were less of this stuff!
(I think we discussed this in person, but adding it here)

**Comment by jdblischak** [comment]
I can add documentation that doesn't appear in the final HTML using the HTML formatting for comments `<!-- comment here -->`. As for the boilerplate, I was just following the example of RStudio by having a small example. Presumably most potential users of workflowr have written a few R Markdown documents, so I can remove the boilerplate.

**Comment by jdblischak** [comment]
Comments added and boilerplate removed from template in f9425b3
