### ISSUE TITLE
GitHub pages site not found

### ISSUE THREAD

**Issue by davismcc** [workflowr/workflowr#116]
I have followed the "getting started" instructions in the [vignette](https://jdblischak.github.io/workflowr/articles/wflow-01-getting-started.html) precisely, using `workflowr` 1.1.1 and R 3.5.1.

Everything worked seamlessly to create the `workflowr` project and connect it to GitHub. You can see my repository here: https://github.com/davismcc/fibroblast-clonality/.

However, the step to deploy the website with GitHub Pages is not working for me. Again, I followed the instructions in the vignette to the letter, but when I click the website link produced by GitHub (https://davismcc.github.io/fibroblast-clonality) I get a 404 "Site not found" error. 

Do you have any idea what's going wrong here? 

It looks like, perhaps, it's an issue with using https? This [GitHub help page](https://help.github.com/articles/securing-your-github-pages-site-with-https/) suggests there could be a problem with serving "mixed content" (http and https?). Unfortunately, I don't know enough about website building to diagnose if that's the root cause here or not. 

Fantastic package and initiative, so I'm excited to use `workflowr` in earnest - any advice for getting the website working would be very gratefully received!

Best wishes,
Davis

**Comment by davismcc** [comment]
Apologies, I was a bit quick on the trigger here. The site now appears on GH Pages - looks like it was just a little slow setting up/updating. Not a workflowr issue at all (and I didn't quite grok the FAQ that mentions that this might happen until just now).

Thanks for a great package, and outstanding setup documentation!

**Comment by jdblischak** [comment]
> Apologies, I was a bit quick on the trigger here. The site now appears on GH Pages - looks like it was just a little slow setting up/updating. Not a workflowr issue at all (and I didn't quite grok the FAQ that mentions that this might happen until just now).

@davismcc No worries! I'm glad it's working now. And for any future readers, the FAQ about GitHub Pages not loading is [here](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#why-isnt-my-website-displaying-online).

> Thanks for a great package, and outstanding setup documentation!

Thanks for the feedback! We put a lot of effort into the documentation, so it's great to know you found it helpful.

> However, the step to deploy the website with GitHub Pages is not working for me. Again, I followed the instructions in the vignette to the letter, but when I click the website link produced by GitHub (https://davismcc.github.io/fibroblast-clonality) I get a 404 "Site not found" error.
>
> Do you have any idea what's going wrong here?

I actually had this happen at a workshop I was teaching recently. It's unfortunate that GitHub Pages can sometimes take a few minutes when first creating the website. To their credit, it is usually less than a minute, and in my experience subsequent updates (i.e. when you push new changes) are incorporated into the website almost instantly.

A trick I figured out that you can use if this happens in the future. If the main URL https://github.com/davismcc/fibroblast-clonality/ gives a 404 error, you can try specifically requesting the index page with https://github.com/davismcc/fibroblast-clonality/index.html.
