### ISSUE TITLE
Rename the entire `workflowr` repo & site

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#118]
Hi John,

I wonder if there is a command/function in `workflowr` that allows me to systematically "re-name" an existing `workflowr` repo & site.

For example, I want to rename an existing project `mvp-cad` as `mvp-cad-grs`, due to a major change in the scientific aim of this work. I know how to do this in Github, as illustrated below:
<img width="668" alt="screen shot 2018-08-20 at 5 30 37 pm" src="https://user-images.githubusercontent.com/5986023/44373590-cfa0a580-a49e-11e8-8767-4648d30fa3db.png">

However, I don't know how to rename everything else (e.g. `mvp-cad.Rproj`) in the repo in a systematic way (I can always change the names manually though).

Thanks!

**Comment by pcarbo** [comment]
@jdblischak Maybe this is something for the FAQ.

@xiangzhu Note that the name of the directory containing the repo can be called whatever you want; this can be different from the name of the repo on GitHub. When you clone a repo, the call is `git clone <repository> <directory>`.

**Comment by pcarbo** [comment]
@xiangzhu Correct!

**Comment by jdblischak** [comment]
> I wonder if there is a command/function in workflowr that allows me to systematically "re-name" an existing workflowr repo & site.

@xiangzhu At the moment there is not a function to perform this. Do you feel like you end up changing the name mid-project often?

> However, I don't know how to rename everything else (e.g. mvp-cad.Rproj) in the repo in a systematic way (I can always change the names manually though).

Here are the manual steps to perform to change the name on both GitHub and locally:

1. Change the name on GitHub - [GitHub documentation](https://help.github.com/articles/renaming-a-repository/)
2. Change the name of the local directory:
    a. In the Terminal:
    ```
    mv mvp-cad/ mvp-cad-grs/
    ```
    b. In R:
    ```
    file.rename("mvp-cad/", "mvp-cad-grs/")
    ```
3. Update the remote URL:
    ```
    wflow_git_remote(remote = "origin", user = "xiangzhu", repo = "mvp-cad-grs",
                     action = "set_url")
    ```
4. Change the name of the Rproj file:
    a. In the Terminal:
    ```
    mv mvp-cad.Rproj mvp-cad-grs.Rproj
    ```
    b. In R:
    ```
    file.rename("mvp-cad.Rproj", "mvp-cad-grs.Rproj")
    ```
5. Change the name in the fields `name:` and `title:` in `analysis_site.yml`
6. Change the name in `README.md` (and you can search your project using either GitHub or RStudio to find other mentions of the project name that you may have added)
7. Publish the changes (republishing all the files will update the project title in the navigation bar and fix the links to past versions of the files)
    ```
    wflow_publish(c("mvp-cad-grs.Rproj", "README.md", "analysis/_site.yml"),
                  message = "Rename project.", republish = TRUE)
    ```

@xiangzhu Please let me know if these instructions work for you.

@pcarbo Have you gotten this question before? This is the first time I have. My plan is to let this Issue serve as the documentation for now. If we start to get this question a lot, I will re-consider adding it to the FAQ and/or creating a function to do this. My hesitation for creating a function is that there are many potential edge cases and a total rename is likely to be a rare event.

**Comment by pcarbo** [comment]
@jdblischak I agree we can let this serve as documentation for the moment. I don't see a strong need to have a separate functino for this.

**Comment by xiangzhu** [comment]
@jdblischak Thanks for the detailed guideline above. I will try it out and let you know if there is any question.

I agree with both you and @pcarbo that documentation should be enough for this use case.

(It seems to be a lot of work to wrap all the seven steps above into a stable function!)

**Comment by jdblischak** [comment]
@xiangzhu I had another request for this feature, so I created [`wflow_rename_proj()`](https://jdblischak.github.io/workflowr/reference/wflow_rename_proj.html) to perform all the local steps to rename the project. It was added in version 1.3.0 (see Issue #148).

**Comment by xiangzhu** [comment]
@jdblischak  Hi John -- I am revisiting this issue now and after reviewing another issue #148, I am a bit confused about the usage of `wflow_rename_proj()`.

My main question is when I should change the project name on GitHub: your replies above (https://github.com/jdblischak/workflowr/issues/118#issuecomment-414685660) suggests that this should be done at the beginning, wheres the list in #148 suggests that this should be done in the end.

Could you provide a small working example for this function?

Thanks a lot!

**Comment by jdblischak** [comment]
> My main question is when I should change the project name on GitHub

@xiangzhu You can change the repository name on GitHub before or after running `wflow_rename_proj()`. Since `wflow_rename_proj()` only affects local files, the name on GitHub has no effect. However, since `wflow_rename_proj()` changes the Git remote URL, you do have to change the name on GitHub before pushing.

In other words, either of these sequences will work fine:

1. Change repository name on GitHub
1. Run `wflow_rename_proj()`
1. Push to GitHub

or

1. Run `wflow_rename_proj()`
1. Change repository name on GitHub
1. Push to GitHub

I can update the [documentation for `wflow_rename_proj()`](https://jdblischak.github.io/workflowr/reference/wflow_rename_proj.html) to more explicitly explain this. Please let me know if there is still anything that remains unclear.

**Comment by xiangzhu** [comment]
@jdblischak  Many thanks for the explanation!

I think I understand the process. The key point is to ensure that "pushing to GitHub" occurs after "renaming in GitHub".

I will share my user experience of this function in this thread soon. Thanks a lot for adding this feature!

**Comment by xiangzhu** [comment]
@jdblischak Hi John,

I hope you had a great Thanksgiving!

I finally used `wflow_rename_proj()` on a real-world repo and I found it very easy to use. I hope others will feel the same.

Thanks again for adding this great feature!

**Comment by jdblischak** [comment]
Thanks for the feedback @xiangzhu! It's always nice to know which features are used and working well.
