### ISSUE TITLE
progress on output

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#12]
when rendering (using build or commit) it would be nice to have more information on progress,
and also more information on which files were successfully commited etc.

eg compared with:
wflow_commit(commit_files="MH-examples1.Rmd")
Rendering MH-examples1.Rmd

it would be nice to output things like "committing xx.Rmd... success"
etc.

**Comment by jdblischak** [comment]
Yes, I can output a message about which files have been successfully committed.

**Comment by jdblischak** [comment]
In [workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0), `wflow_publish()` provides a message as each file is built to indicate progress, and prints a detailed message upon completion. To suggest further improvements, please re-open this Issue or start a new one.
