### ISSUE TITLE
Make the "Session information" section "foldable"

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#120]
> Before posting your issue, please search the existing issues (both "open" and "closed") to check that a similar feature has not already been requested.

It seems that I didn't find any related issues here: https://github.com/jdblischak/workflowr/issues?utf8=%E2%9C%93&q=is%3Aissue+sessioninfo

> 1. Describe the suggested feature.

Currently the "Session information" section is automatically shown in the end of each page:
<img width="831" alt="screen shot 2018-08-31 at 6 25 41 pm" src="https://user-images.githubusercontent.com/5986023/44941049-6a28a080-ad4b-11e8-9b4a-45282d7bb72b.png">

However, I wonder whether this "Session information" section can be made "foldable" like the reproducible report:
<img width="833" alt="screen shot 2018-08-31 at 6 27 31 pm" src="https://user-images.githubusercontent.com/5986023/44941066-9d6b2f80-ad4b-11e8-89ff-9c0816c2aa13.png">

Further, I wonder if it is possible to move this section to the reproducible report.

> 2. Describe why you think this feature is needed.

First as a user I rarely read this section, unless I need to check something for debugging purpose. To save space (and potentially reduce distraction), perhaps we can "fold" this section most of time, and only manually "unfold" it when necessary?

Second, logically this section seems to be closely related to reproducibility. (Sometimes we need set the correct version of certain packages to reproduce things.) 

> 3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

```r
> packageVersion("workflowr")
[1] ‘1.1.1’
```

Thanks for your time on this question. Have a great long weekend!

**Comment by pcarbo** [comment]
> I wonder if it is possible to move this section to the reproducible report.

@jdblischak Do you know if that is possible? The issue is that this code chunk needs to be run last, right?

**Comment by xiangzhu** [comment]
@pcarbo  I think it's okay for me that the "Session information" still displays at the end of page; my major question is whether this section can be made "foldable" like the reproducible report section.

**Comment by pcarbo** [comment]
@xiangzhu I understand, but your request (and others) made me think that it might be interesting to have the sessionInfo inside the workflowr report, if that is realistic.

For your particular situation, try the attached R Markdown file.

[index.Rmd.gz](https://github.com/jdblischak/workflowr/files/2342667/index.Rmd.gz)

**Comment by xiangzhu** [comment]
@pcarbo  I agree -- it seems that "Session information" section should be a part of reproducible report.

However, if it complicates the implementation, I am happy that this section stays at the end.

Regarding the attached example, I think the main trick is using `code_folding: hide`, but this seems to fold all code chunks:
<img width="956" alt="screen shot 2018-09-01 at 12 01 35 pm" src="https://user-images.githubusercontent.com/5986023/44949070-d0123800-adde-11e8-9209-5a32c543db4b.png">

However an more ideal output for me would be as follows:
<img width="940" alt="screen shot 2018-09-01 at 12 02 22 pm" src="https://user-images.githubusercontent.com/5986023/44949074-ec15d980-adde-11e8-924f-eab87ce35177.png">

That is, only the "Session information" is folded. 

Thanks again for your time and help on this!

**Comment by pcarbo** [comment]
@xiangzhu I thought it would be easy to control this for individual chunks, but it turns out that [this feature is not currently available](https://github.com/rstudio/rmarkdown/issues/664). So the short answer is that this would be difficult to implement in workflowr.

**Comment by xiangzhu** [comment]
@jdblischak  Hi John -- related to `SessionInfo`, is it possible to add an option somewhere in `workflowr` so that users can opt to use `devtools::session_info()` to generate this section? Thanks!

**Comment by pcarbo** [comment]
@xiangzhu I think this is already on the list of things to do.

**Comment by jdblischak** [comment]
@xiangzhu This feature is already implemented. See the section [Change the session information function](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html#change-the-session-information-function) in the vignette [Customize your research website](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html).

**Comment by xiangzhu** [comment]
@jdblischak @pcarbo  Great, thanks!

I look forward the version where this section can be further "folded".

**Comment by xiangzhu** [comment]
Hi John -- Happy New Year! I have a follow-up question on this thread. Below is an example.

<img width="833" alt="screen shot 2019-01-04 at 6 24 11 pm" src="https://user-images.githubusercontent.com/5986023/50719220-325d9c80-104e-11e9-90b8-e77204340868.png">

There is an italic line "Expand here to see past versions of unnamed-chunk-1-1.png:" right under the figure. I understand this line is **very important** to keep track of previous versions of figures, but most of time readers (e.g. students who read the lecture notes) do not care it too much. On the contrary, this italic line sometimes might distract and possibly even confuse readers.

I wonder if it is straightforward to make this italic line less obvious so that most readers won't even pay attention to this line.

One simple idea is to make the font size of this line smaller. Another idea is to turn this line into a clickable icon.

In addition, do we have certain options in `workflowr` not to display these lines? 

This is in the similar vein of "folding" the reproducibility bullet points -- these reproducibility-related contents may be better "hidden" most of time.

Again this seems to be a nitpicking question. Please ignore it if too many programming efforts are required.

**Comment by jdblischak** [comment]
> One simple idea is to make the font size of this line smaller. Another idea is to turn this line into a clickable icon.

@xiangzhu I was thinking about turning it into a clickable button. But do you think that would be less distracting?

> On the contrary, this italic line sometimes might distract and possibly even confuse readers.

I could also try to add a help icon for explanation. Since incorporating version control is one of the central features of workflowr (as opposed to just using rmarkdown and Git separately), I'd prefer to keep these in workflowr generated HTML files.

**Comment by docmanny** [comment]
@xiangzhu, while it may go slightly against the goals and philosophy of reproducibility, a possible solution would be to collapse the mutliple commits leading up to the final figure into one [as shown here.](http://www.jancarloviray.com/blog/how-to-merge-multiple-commits-into-one-git-commit/) It should do away with the "prior versions of this chunk" popup. 
Doing this does kinda defeat the purpose of `workflowr`, however, and I would like to stress that if it a class, **this is actually a valuable teaching opportunity**. Instead of worrying that students will not care about this, and that they might find it confusing, explain to them in a paragraph or so the value of reproducibility, and create a mock example about how they can go through the prior versions to better understand the process of coding and data analysis in greater detail.

**Comment by xiangzhu** [comment]
@jdblischak  thanks for your reply!

> I was thinking about turning it into a clickable button. But do you think that would be less distracting?

I like this idea! I feel that it will become distracting only if the reader click the button.

> I'd prefer to keep these in workflowr generated HTML files.

I totally understand the importance of these reproducibility-related info, and I totally agree they should be always part of HTML output. My general point in this thread is that perhaps we can have reproducibility-related info shown in a less obvious place (e.g. foldable section, clickable button), and can check this info within the HTML when necessary (e.g. unfold the section, click the button).

@docmanny thanks for the pointer to merge multiple commits -- and I agree using this just defeats the purpose of using `workflowr`.

**Comment by pcarbo** [comment]
My personal view is that the sessionInfo is fine as it is (at the bottom of the page, and not foldable). Certainly, improvements are possible, but doesn't seem like a high priority at this stage.

Often what I do is toward the beginning of the R Markdown I will load all the R packages, and I will mention that the exact versions used are given at the bottom of the page.

**Comment by xiangzhu** [comment]
@jdblischak  many thanks for the update! The output of dev version is fantastic, and exactly satisfies my multiple requests above.

Below are screenshots from my test (macIOS and Chrome).

<img width="854" alt="screen shot 2019-01-09 at 12 37 07 pm" src="https://user-images.githubusercontent.com/5986023/50927028-6698da80-140b-11e9-92bb-61fa933b032f.png">
<img width="861" alt="screen shot 2019-01-09 at 12 37 18 pm" src="https://user-images.githubusercontent.com/5986023/50927029-6698da80-140b-11e9-9a13-8bb267bf62de.png">
<img width="795" alt="screen shot 2019-01-09 at 12 37 30 pm" src="https://user-images.githubusercontent.com/5986023/50927030-67317100-140b-11e9-82af-62375823f81b.png">
<img width="857" alt="screen shot 2019-01-09 at 12 37 39 pm" src="https://user-images.githubusercontent.com/5986023/50927031-67317100-140b-11e9-978e-48418ec0a169.png">

How long will these nice features show up in the CRAN release? Before the CRAN release, is it recommended to use this dev version for now (since I really like these output)?

I do not have any further question on this thread. Please feel free to close it as you see fit.

**Comment by jdblischak** [comment]
> many thanks for the update! The output of dev version is fantastic, and exactly satisfies my multiple requests above.

@xiangzhu Great! Thanks for the feedback.

> Below are screenshots from my test (macIOS and Chrome).

Thanks so much for testing this out for me.

> How long will these nice features show up in the CRAN release? Before the CRAN release, is it recommended to use this dev version for now (since I really like these output)?

I'm making a push now for a new CRAN release. I'll keep you updated, especially if I make a pre-release for testing. I don't recommend installing from the "dev" branch as this is likely unstable.

**Comment by jdblischak** [comment]
@xiangzhu This feature is now available in [workflowr 1.2.0](https://github.com/jdblischak/workflowr/releases/tag/v1.2.0). You can install it from the GitHub master branch or wait for it to be built and synced across the CRAN mirrors.

**Comment by xiangzhu** [comment]
@jdblischak  Great! I still remember how awesome it was in the test version, and really look forward to using the formal release!

I prefer to install from CRAN -- will you make an announcement once the CRAN release is up?

**Comment by jdblischak** [comment]
@xiangzhu I suspect the CRAN binaries should be built by tomorrow.

Don't you use Ubuntu? If yes, you can already download the source package from CRAN using either the RStudio mirror or the Berkeley mirror:

```
install.packages("workflowr", repos = "https://cloud.r-project.org/")
install.packages("workflowr", repos = "https://cran.cnr.berkeley.edu/")
```

My default setting is to use the Case Western mirror, which hasn't yet synced (i.e. it still downloads version 1.1.1):

```
install.packages("workflowr", repos = "https://cran.case.edu/")
```

**Comment by xiangzhu** [comment]
Thanks! I am using both Ubuntu (at home) and macIOS (at work). I will check both later today.
