### ISSUE TITLE
publish sites privately to aws S3 with http basic auth

### ISSUE THREAD

**Issue by edavidaja** [workflowr/workflowr#123]
In thinking about ways to publish workflowr sites privately, I happened across the following:

https://hackernoon.com/serverless-password-protecting-a-static-website-in-an-aws-s3-bucket-bfaaa01b8666

which has been mostly automated by a repository referenced in the article, and linked to [here](https://github.com/dumrauf/serverless_static_website_with_basic_auth).

Introducing it to the package would add some aws dependencies, but if nothing else it might be worth a mention in the docs as a way to accomplish that goal if you really want a private workflowr website.

**Comment by jdblischak** [comment]
> https://hackernoon.com/serverless-password-protecting-a-static-website-in-an-aws-s3-bucket-bfaaa01b8666

@edavidaja Thanks for the tip! Have you tried following the instructions to set up a password-protected site yourself?

> Introducing it to the package would add some aws dependencies, but if nothing else it might be worth a mention in the docs as a way to accomplish that goal if you really want a private workflowr website.

Yes, I see 3 possible options. Ordered in increasing complexity:

1. Add this URL to the [FAQ on private web hosting](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#can-i-make-my-workflowr-website-private)
1. Include longer-form documentation tailored to workflowr users on how to implement this solution
1. Write a new function to deploy the site to Amazon S3 using the [aws.s3](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#can-i-make-my-workflowr-website-private) package

Would you be interested in helping implement any of these solutions?

**Comment by edavidaja** [comment]
I'll send a PR updating the FAQ in a few hours. Once I've had an opportunity to actually get a demo site up and running, I can also add a vignette about private deployments. I suspect 3 is slightly outside my level of package development skill, so no commitments there, but if I make it happen, I'm happy to submit that later as well.

**Comment by jdblischak** [comment]
> I'll send a PR updating the FAQ in a few hours.

@edavidaja Great! Let's start small. Please make the change to the R Markdown file on the "dev" branch, but there's no need to rebuild the documentation (I do that myself before each release).

https://github.com/jdblischak/workflowr/blob/dev/vignettes/wflow-05-faq.Rmd

> Once I've had an opportunity to actually get a demo site up and running, I can also add a vignette about private deployments.

Please check back once you have this working. I am planning on starting a new vignette on alternative deployment options, and this would be a good fit (see this [comment](https://github.com/jdblischak/workflowr/issues/119#issuecomment-418361260)).

> I suspect 3 is slightly outside my level of package development skill, so no commitments there, but if I make it happen, I'm happy to submit that later as well.

No worries! That would be pushing my skills, too. I don't think it is necessary to build a dedicated function until there are sufficient users that are interested in hosting with AWS.

**Comment by jdblischak** [comment]
The FAQ entry was added by @edavidaja in PR #124.

@edavidaja Please post to this Issue once you have a working demo, and then we can discuss the plan for more long-form workflowr-specific documentation. Thanks!

**Comment by jdblischak** [comment]
@edavidaja Your documentation on hosting on AWS is now included in the official docs now that workflowr 1.2.0 has been released. I moved it to a new vignette on alternative deployment options. Thanks again for your contribution!

https://jdblischak.github.io/workflowr/articles/wflow-08-deploy.html#amazon-s3-password-protected

I'm going to close this Issue since it's been acted on. Please feel free to re-open in the future (or open a new Issue that references this old one) if you'd like to discuss adding more documentation or features.
