### ISSUE TITLE
Add text below SessionInfo header

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#125]
A small thing that bugs me: having a heading with code but no text in it. Maybe the "session info" section could look something like this?

## Session information

Print version information about R, the operating system, and attached or loaded packages.

```R
sessionInfo()
```

Print version information about R, the OS and attached or loaded
     packages.
```

**Comment by jdblischak** [comment]
@pcarbo This doesn't bother me. I prefer to be as minimalist as possible when it comes to inserting boiler plate into a user's analysis. And I'd argue the output from `sessionInfo()` is quite self-documenting.

But ultimately this will likely soon be a non-issue. As discussed in #120, I am planning on collapsing the session information chunk, which will likely mean also removing the h2 heading.

**Comment by jdblischak** [comment]
As of [workflowr 1.2.0](https://github.com/jdblischak/workflowr/releases/tag/v1.2.0), the session information chunk no longer has an H2 header. It is only a collapsible button.
