### ISSUE TITLE
wflow_commit a single file

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#13]
my typical use case is that i finished a file so i want to commit it (and only it as there are often other rmd files i'm currently working on that are not yet ready for commiting).

so it would be nice if `wflow_commit("test.Rmd")` would work, rather than having to use
`commit_file ="test.Rmd"`.

**Comment by jdblischak** [comment]
Agreed that makes sense. I'll change the API for both `wflow_commit` and `wflow_build` so that the files argument precedes the `all` argument.

**Comment by jdblischak** [comment]
This has been implemented in [workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0). The first argument to any function that works on files is `files`, and thus the argument does not need to be named. For example, these all work: `wflow_open("file.Rmd")`, `wflow_build("file.Rmd")`, `wflow_view("file.Rmd")`, `wflow_commit("file.Rmd")`, `wflow_publish("file.Rmd")`, and `wflow_status("file.Rmd")`.
