### ISSUE TITLE
Automatically generated URLs for sections

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#131]
Hi John -- I am not sure whether this is a `workflowr` question or a `rmarkdown` question. My sincere apology if it is just a `rmarkdown` question.

I am curious whether I can decide the URL for a *section* or *subsection* in a given `workflowr` page.

For example, if I click the following subsection "Run phenome-wide association studies (PheWAS) on GRS", then I get the following URL: https://xiangzhu.github.io/mvp-cad/#run_phenome-wide_association_studies_(phewas)_on_grs, which is indeed the subsection title.

![screenshot from 2018-11-13 16-11-44](https://user-images.githubusercontent.com/5986023/48451344-eb92ab00-e75e-11e8-85ef-8bc94aeb5ea9.png)

Clearly this URL is too long (and somewhat not tidy especially due to the `(phewas)` part). I hope that I can do something, either by `workflowr` or `rmarkdown`, that allows myself to adjust these URLs.

Thanks in advance for your time and help!

**Comment by jdblischak** [comment]
@xiangzhu This isn't workflowr-specific, but I'm happy to help.

The link `#run_phenome-wide_association_studies_(phewas)_on_grs` is auto-generated by Pandoc based on the title of the section. The most straightforward way to customize the link would be to give an explicit internal link for Pandoc to use (explained [here](https://stackoverflow.com/a/39293457/2483477) and in the [Pandoc manual](http://pandoc.org/MANUAL.html#header-identifiers)). The syntax is:

```
## Run phenome-wide association studies (PheWAS) on GRS {#custom-link}
```

Then the URL would be https://xiangzhu.github.io/mvp-cad/#custom-link.

Another option would be to directly use HTML anchor tags, as explained [here](https://stackoverflow.com/a/7015050/2483477). This would allow you to create a custom link, but it wouldn't update the link used in the table of contents.
