### ISSUE TITLE
Fixing legacy rawgit links

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#134]
[rawgit](https://rawgit.com/) is shutting down ([tweet](https://twitter.com/rawgit/status/1049360165030567937)). I was already planning on switching to [raw.githack](https://raw.githack.com/) to be able to support GitLab repos. However, it would be nice to be able to provide upgrade support for existing workflowr sites.

Luckily, this may be done automatically by [jsDelivr CDN](https://www.jsdelivr.com/):

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Our jsDelivr Bot is now scanning GitHub for broken <a href="https://twitter.com/rawgit?ref_src=twsrc%5Etfw">@rawgit</a> links and sending PRs with JsDelivr alternatives. Makes migration as easy as clicking the merge button 🙌</p>&mdash; jsDelivr CDN (@jsDelivr) <a href="https://twitter.com/jsDelivr/status/1071066416739246080?ref_src=twsrc%5Etfw">December 7, 2018</a></blockquote>

**Comment by jdblischak** [comment]
I can't use the jsDelivr CDN to serve HTML files. From the section [Restrictions](https://github.com/jsdelivr/jsdelivr#restrictions):

> HTML files are served with `Content-Type: text/plain` for security reasons.

Also, there bot got shut down anyways:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">It appears that our bot&#39;s account has, without any warning, just vanished from <a href="https://twitter.com/github?ref_src=twsrc%5Etfw">@github</a> 😅 Waiting for more info from <a href="https://twitter.com/GitHubHelp?ref_src=twsrc%5Etfw">@GitHubHelp</a> <a href="https://t.co/uMAZt9vFv8">https://t.co/uMAZt9vFv8</a></p>&mdash; jsDelivr CDN (@jsDelivr) <a href="https://twitter.com/jsDelivr/status/1072246456860454913?ref_src=twsrc%5Etfw">December 10, 2018</a></blockquote>

Thus the plan is to proceed with raw.githack.

**Comment by jdblischak** [comment]
For GitHub:
* The URL to a specific HTML file is https://github.com/user/repo/blob/commit/path/file.html, e.g. https://github.com/jdblischak/dc-bioc-limma/blob/ef5ea09f1d2e12af8757d2d77a68e16466947a65/docs/index.html
* This is converted by raw.githack.com to https://rawcdn.githack.com/user/repo/commit/path/file.html, e.g. https://rawcdn.githack.com/jdblischak/dc-bioc-limma/ef5ea09f1d2e12af8757d2d77a68e16466947a65/docs/index.html

For GitLab:
* The URL to a specific HTML file is https://gitlab.com/user/repo/blob/commit/path/file.html, e.g. https://gitlab.com/jdblischak/wflow-gitlab/blob/f3b96cfd498ad1b6fb177fa9ae5ad1a2e2ca7261/public/index.html
* This is converted by raw.githack.com to https://glcdn.githack.com/user/repo/raw/commit/path/file.html, e.g. https://glcdn.githack.com/jdblischak/wflow-gitlab/raw/f3b96cfd498ad1b6fb177fa9ae5ad1a2e2ca7261/public/index.html

**Comment by lo2811** [comment]
Hi,
I ran into the rawgit error and wanted to know if you have updated workflowr to use with raw.githack.
Thank you!
Linh

**Comment by jdblischak** [comment]
@lo2811 Sorry for the inconvenience. This will be fixed soon. I am preparing the next release to CRAN, so hopefully the new version will be available sometime next week. If you'd like to be notified when it is ready, please join the [workflowr-announce](https://groups.google.com/forum/#!forum/workflowr-announce) mailing list.

> I ran into the rawgit error and wanted to know if you have updated workflowr to use with raw.githack.

 Could you please send me a link to your project and the specific rawgit URL that failed? Thanks!

**Comment by lo2811** [comment]
https://lo2811.github.io/IPF_LB/

Here is my test project, and the rawgit URL that failed is the one under "Expand here to see past versions". Thank you!

**Comment by jdblischak** [comment]
@lo2811 Thanks! I confirmed that rawgit is officially down. Here is the updated link using raw.githack.com:

https://rawcdn.githack.com/lo2811/IPF_LB/17760e6e38b2a813999e9aa0a95a1df35f2032c8/docs/index.html

When the new version of workflowr is released, you can republish your analyses with `wflow_publish(republish = TRUE)`. This will update all the links from raw to raw.githack.

**Comment by FedericoComoglio** [comment]
Hi @jdblischak, a related issue for me is that links to HTML files do not work from self-hosted GitLab repositories. Since other files can be rendered directly from gitlab (setting the `github` parameter in the YAML file to my gitlab repository URL worked as expected), I wonder if there is an easy fix specific for HTML files.

Let me know.
Thanks!

**Comment by jdblischak** [comment]
> I wonder if there is an easy fix specific for HTML files.

@FedericoComoglio Unfortunately there is not anything I can do about this. `raw.githack.com` is a free service that only supports the following URLs: `raw.githubusercontent.com`, `gist.githubusercontent.com`, `bitbucket.org`, and `gitlab.com`.

Long term I'd like to replace raw.githack.com with a workflowr-specific service that could handle cases like custom GitLab instances. But this will require the time to write a dedicated web application and also the money to pay for hosting both the app and the websites. So I can't promise this will be done anytime soon or even at all.

**Comment by FedericoComoglio** [comment]
I understand - thanks a lot. This is currently not a big issue, as all other files that can be directly accessed from a self-hosted GitLab instance can be correctly accessed/rendered.

**Comment by jdblischak** [comment]
@FedericoComoglio I added a note to the GitLab vignette in 315c09e about custom GitLab instances (this new vignette will be included in the next release).

**Comment by jdblischak** [comment]
@lo2811 This fix is now available in [workflowr 1.2.0](https://github.com/jdblischak/workflowr/releases/tag/v1.2.0). You can install it from the GitHub master branch or wait for it to be built and synced across the CRAN mirrors.
