### ISSUE TITLE
Default directory for knitting an rmd file in `analysis/`

### ISSUE THREAD

**Issue by LSun** [workflowr/workflowr#136]
Hi John and Peter,

When I read a data set from the `data/` directory, say, the rmd doesn't knit. For example, if I have a code chunk like this:
```
r <- readRDS("../data/data.rds")
```
this rmd file will not be knitted unless I change the directory to `"data/data.rds"`.

I remember older versions of `workflowr` was not like this. So you changed it?
It may create some inconvenience, as `r <- readRDS("data/data.rds")` doesn't work interactively in R Studio.

Any ideas? Many thanks.

**Comment by jdblischak** [comment]
@LSun In workflowr 1.0+, the directory where the code is executed (referred to as the "knit directory" or `knit_root_dir` in the workflowr documentation) is customizable. The default is to execute the code in the root of the project directory. This means a user doesn't have to manually change the working directory (or run `wflow_open()`) every time they open a workflowr project in RStudio.

Here is the relevant explanation from the [Getting Started vignette](https://jdblischak.github.io/workflowr/articles/wflow-01-getting-started.html#start-the-project):

> The workflowr-specific configuration file is _workflowr.yml. It will apply the workflowr reproducibility checks consistently across all your R Markdown files. The most critical setting is knit_root_dir, which determines the directory where the files in analysis/ will be executed. The default is to execute the code in the root of the project where _workflowr.yml is located (i.e. "."). To instead execute the code from analysis/, change the setting to knit_root_dir: "analysis". See ?wflow_html for more details.

To change the knit directory to `analysis/`, follow these steps:

1. Edit the file `_workflowr.yml` to change `knit_root_dir: "."` to `knit_root_dir: "analysis/"`
1. Change any file paths in your R Markdown files to use the relative path to data, i.e. `../data/`
1. Publish the changes with `wflow_publish(c("../_workflowr.yml"), message = "Change the knit directory to analysis", republish = TRUE)` (note: this assumes your current working directory is `analysis`)

You can read more details at [?wflow_html](https://jdblischak.github.io/workflowr/reference/wflow_html.html#reproducibility-features). Please let me know if you have any questions or have any difficult getting this setup.

**Comment by LSun** [comment]
Thanks a lot!
