### ISSUE TITLE
wflow_build() fails while attempting sessioninfo - cannot allocate memory

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#138]
I am not sure if this is a workflowr issue. This is my first attempt at using workflowr.

I have an analysis - just reading three large CSVs (~3M rows each), concatenating them, and saving one large data frame (~10M rows) as an RDS file. I am using RStudio and workflowr.

That works fine if I execute the analysis in the R console a chunk at a time, but it fails if I use the RStudio knit button or wflow_build().

The error appears to occur in the workflowr session-info-chunk, that is, *after* my code has finished.

Tail of output log:
```
  |                                                                       
  |......................................................           |  82%
label: save_raw_data

  |                                                                       
  |.........................................................        |  88%
  ordinary text without R code


  |                                                                       
  |.............................................................    |  94%
label: session-info-chunk-inserted-by-workflowr
```

It appears to be an out-of-memory error.

Error log:
```
Error in system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE) : 
  cannot popen '/usr/bin/which 'uname' 2>/dev/null', probable reason 'Cannot allocate memory'
Warning message:
system call failed: Cannot allocate memory 
```
 
At the point my code finishes ~20GB RAM is free according to the OS, ~40GB RAM is allocated to R by the OS, and of that ~20GB is used by the big data frame, with ~20GB free for reallocation in R. So there seems to be plenty of spare memory sloshing around for a system call.

Any help to diagnose what is going on here would be much appreciated.

Thanks.

**Comment by jdblischak** [comment]
> I am not sure if this is a workflowr issue. This is my first attempt at using workflowr.
>
> I have an analysis - just reading three large CSVs (~3M rows each), concatenating them, and saving one large data frame (~10M rows) as an RDS file. I am using RStudio and workflowr.
>
> That works fine if I execute the analysis in the R console a chunk at a time, but it fails if I use the RStudio knit button or wflow_build().

@rgayler Thanks for the detailed bug report! Hopefully we can get this resolved quickly.

> Any help to diagnose what is going on here would be much appreciated.

Some questions:

1. What operating system are you using? Is this a local or remote machine? Are you using Docker?
1. How are you monitoring the memory usage? Are you tracking it in real time as the code executes?
1. What version of workflowr and rmarkdown are you using?

Some ideas to help diagnose the problem. Please let me know which of the below succeed or fail:

1. Create a new R Markdown file with some arbitrary fast-running code chunks. Run `wflow_build()` specifically on that file (or hit Knit HTML in RStudio).
1. Run `wflow_build()` on the problematic Rmd file with the argument `local = TRUE`. (Make sure you have a clean R session first, i.e. running `ls()` should report no objects currently defined)
1. Manually add a chunk with a call to `sessionInfo()` at the beginning the problematic Rmd file. Does this chunk execute successfully?
1. Manually add a chunk with a call to `sessionInfo()` at the very end the problematic Rmd file. Does this chunk execute successfully?
1. If it's not too much trouble, copy the problematic Rmd file to a temporary location, update the file paths to the data files, and execute it with `rmarkdown::render()`. This will determine if it is a workflowr error or rmarkdown error.

**Comment by jdblischak** [comment]
> It appears to be an out-of-memory error.

Also, I agree that this appears to be a memory issue. Here's a related issue that came to the same conclusion: https://github.com/opencpu/opencpu/issues/142

**Comment by rgayler** [comment]
Thanks @jdblischak.

FWIW I have been able to work around the problem by including a final chunk in my analysis documents:

```
rm(list = ls())
gc(full = TRUE)
```

I have now convinced myself that this not a `workflowr`, `markdown`, or RStudio issue. It appears to be an issue with the R `system()` function that only arises when the R session uses up more than ~75% of the available RAM. The problem is that the  R system() function, for whatever reason, fails with an out of memory error, even though there is  ~15GB free on my PC according to the OS.

This was a problem for `workflowr` because it inserts a `sessioninfo()` chunk at the end of the analysis document and `sessioninfo()` makes at least one `system()` call.

I have now asked this question on [StackOverflow](https://stackoverflow.com/questions/54034171/r-system-cannot-allocate-memory-even-though-the-same-command-can-be-run-from-a)

I have created a reprex that shows this problem in a naked R session. I will show the reprex here because somebody else may bump into the same problem, but it can be closed as a `workflowr` issue.

> What operating system are you using?

Ubuntu 18.04.1 LTS - x86_64-pc-linux-gnu (64-bit)

> Is this a local or remote machine? 

local - it's a *big* desktop PC (64GB RAM, 32 thread AMD CPU)

> Are you using Docker?

nope - R is being executed directly  
R version 3.5.2 (2018-12-20)  

Here is the reprex directly in an R session. The size of the data frame `d` needs to be adjusted to be as small as possible and still provoke the error. This will depend on how much RAM you have and what else is running at the same time. 

R gets an error that persists after garbage collection.

```
ross@doppio:~$ R

R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> n <- 5e8
> d <- data.frame(
+   v0 = rep_len(1.0, n),
+   v1 = rep_len(1.0, n),
+   v2 = rep_len(1.0, n),
+   v3 = rep_len(1.0, n),
+   v4 = rep_len(1.0, n),
+   v5 = rep_len(1.0, n),
+   v6 = rep_len(1.0, n),
+   v7 = rep_len(1.0, n),
+   v8 = rep_len(1.0, n),
+   v9 = rep_len(1.0, n)
+ )
> 
> dim(d)
[1] 500000000        10
> system("free -m", intern = FALSE)
Warning messages:
1: In system("free -m", intern = FALSE) :
  system call failed: Cannot allocate memory
2: In system("free -m", intern = FALSE) : error in running command
> gc()
             used    (Mb) gc trigger    (Mb)   max used    (Mb)
Ncells     260857    14.0     627920    33.6     421030    22.5
Vcells 5000537452 38151.1 6483359463 49464.2 5000559813 38151.3
> system("free -m", intern = FALSE)
Warning messages:
1: In system("free -m", intern = FALSE) :
  system call failed: Cannot allocate memory
2: In system("free -m", intern = FALSE) : error in running command
> 
```
The call to `gc()` indicates R has only allocated ~38GB out of 64 GB RAM and a running `free -m` in a terminal at the same time (see below)  shows that the OS thinks there is ~16GB free.

So `free -m` can't be run from within R, but it can be run at the same time from a terminal.

```
ross@doppio:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:          64345       44277       15904         461        4162       18896
Swap:           975           1         974
ross@doppio:~$ 
```

**Comment by jdblischak** [comment]
> So free -m can't be run from within R, but it can be run at the same time from a terminal.

@rgayler Interesting! (though frustrating) Thanks for tracking down the issue. Hopefully someone can help explain this behavior.

**Comment by rgayler** [comment]
In case anyone gets here later via a search - problem identified and solved at: [https://stackoverflow.com/a/54048421/1504572](https://stackoverflow.com/a/54048421/1504572)

The underlying linux call needs to know that there is enough RAM + swap to duplicate the entire memory of the R process in case it needs to (which it doesn't). The  work-around solution is to increase the swap size enough.

**Comment by jdblischak** [comment]
@rgayler Thanks for following up here with the solution!
