### ISSUE TITLE
allow setting header level (per analysis document) of session info chunk

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#139]
I enable section number in analysis document because I find it helpful when speaking with remote collaborators to be able to refer to a section number.

The sessioninfo chunk automatically inserted at the end of every analysis document has an H2 header. If I use H1 headers for my sections, then the sessioninfo chunk is rendered as a subsection of my last H1 section, which is usually not logical. If I use H2 for my top level headers, then all the headers are rendered as 0.n, which looks odd.

It would be helpful to be able to specify the header level of the sessioninfo chunk - preferably per analysis file.

**Comment by rgayler** [comment]
Thanks, John. I will almost certainly use option1 (explicitly call sessioninfo), because that has been my standard practice for a while and I generally use devtools::session_info.

**Comment by rgayler** [comment]
> The function wflow_html() will only insert a session information chunk (with an H2 header) if it detects code chunks but no call to sessionInfo() (or session_info() from devtools). 

What version of workflowr was that introduced? I am using CRAN workflowr v1.1.1 and don't get that behaviour. I have tried inserting calls to sessionInfo() and devtools::session_info() and even naming the chunk session-info (as in your example) and none of them suppressed the automatic sessinfo.

**Comment by jdblischak** [comment]
> What version of workflowr was that introduced? I am using CRAN workflowr v1.1.1 and don't get that behaviour.

This was introduced in v1.0.0.

> I have tried inserting calls to sessionInfo() and devtools::session_info() and even naming the chunk session-info (as in your example) and none of them suppressed the automatic sessinfo.

My apologies. I only gave you half of the solution. The full solution is documented in the section [Change the session information function](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html#change-the-session-information-function) in the vignette [Customize your research website](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html). You need to add the entry `sessioninfo: ""` to the file `_workflowr.yml`. This will prevent the automatic insertion by workflowr. Once you confirm this works (e.g. with `wflow_build()` or the Knit HTML button), you can publish (i.e. commit) these changes with `wflow_publish("_workflowr.yml", republish = TRUE)`.

**Comment by rgayler** [comment]
Gotcha. I misinterpreted you as saying that workflowr *searched* for an occurrence of `sessionInfo()` in the document code.

Tested. Works. Done. Thanks!

**Comment by jdblischak** [comment]
> I misinterpreted you as saying that workflowr searched for an occurrence of sessionInfo() in the document code.

@rgayler Not your fault. I did say that, and I was mistaken. This is because workflowr does search the document code when deciding whether or not the file should pass the reproducibility check (displayed at the top of the file). However, for the mechanism to insert the session info chunk, it currently requires the user to explicitly disable it in `_workflowr.yml` (perhaps I'll change this strict requirement in the future).

> Tested. Works. Done. Thanks!

Glad it's working!

**Comment by jdblischak** [comment]
@rgayler Also note that I am considering getting rid of the level 2 header altogether. Instead the Session Information would be included as a collapsible button at the very end of each analysis. See https://github.com/jdblischak/workflowr/issues/120#issuecomment-452457503 for discussions and screenshots.

This change is part of an overhaul of the workflowr styling to be less intrusive. See https://github.com/jdblischak/workflowr/issues/110#issuecomment-453233028 for how the workflowr report is changing.
