### ISSUE TITLE
working directory for interactive evaluation of code in analysis documents

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#140]
workflowr sets the R session working directory to the project directory. Workflowr also sets the working directory to the project directory in the R session spawned for knitting an analysis document.

However, when interactively executing code from an analysis document (e.g. run chunk, or select-ctl-enter) the working directory is set to respect the RStudio knit directory parameter, which in my case defaults to Document Directory, which is inconsistent with the other ways of executing analysis code.

Would it be possible to automatically set the Knit Directory parameter to Project Directory for wflowr projects?

**Comment by pcarbo** [comment]
@rgayler The `knit_root_dir` parameter in the `_workflowr.yml` controls this; see `help(wflow_html)`  in R for advice on how to change this setting to suit your RStudio setup.

**Comment by rgayler** [comment]
@pcarbo I believe `knit_root_dir` is already set correctly.

Here is how I reproduced the behaviour:

I opened a fresh RStudion session.

**demonstrate RStudio default setting of Knit Directory for Rmarkdown**

I created a new Rmarkdown file.
The default setting of RStudio > Knit > Knit Directory is Document Directory

**demonstrate workflowr behaviour for 4 use cases**

I created a brand new workflowr test project.
`_workflowr.yml` contains `knit_root_dir: "."`
I created a new analysis document `analysis/test_file.Rmd`
The default setting of RStudio > Knit > Knit Directory is still Document Directory
I edit the contents of the chunk to be `getwd()`

1 If I click RStudio > Knit I get `[1] "/home/ross/test"` (working directory set to project directory)

2 If I copy and paste the code into the R console and execute it I get `[1] "/home/ross/test"` (working directory set to project directory)

3 If I click the Run Chunk button in `analysis/test_file.Rmd` I get `[1] "/home/ross/test/analysis"` (working directory set to document directory)

4 If I select the code in `analysis/test_file.Rmd` and ctl-enter I get `[1] "/home/ross/test/analysis"` (working directory set to document directory)

5 If I click RStudio > Knit > Knit Directory > Current Working Directory then test cases 1 through 4 all return `[1] "/home/ross/test"`

So the out of the box behaviour on my system ignores the `_workflowr.yml` setting for `knit_root_dir: "."` when manually executing code *from* the analysis document.

**Comment by jdblischak** [comment]
> However, when interactively executing code from an analysis document (e.g. run chunk, or select-ctl-enter) the working directory is set to respect the RStudio knit directory parameter, which in my case defaults to Document Directory, which is inconsistent with the other ways of executing analysis code.

Unfortunately there is not much I can do as an R package author to prevent this unfortunate new behavior of RStudio. This option is not exposed in the rstudioapi package. Also, the RStudio developers are aware of this Issue but haven't exposed a solution that I could try. I commented in the Issue from last April https://github.com/rstudio/rstudio/issues/2595.

The two options are 1) change the Knit Directory to Project Directory or 2) disable the inline preview of code chunks. Here is a screenshot of the box to uncheck in the Global Options pane:

![screenshot from 2019-01-07 11-13-03](https://user-images.githubusercontent.com/1608317/50779038-5945e980-126d-11e9-8480-6e9855451c61.png)

Note that you'll likely need to restart RStudio for this to go into effect. Once an R Markdown file has inline previews, I find it difficult to get rid of them.

I personally disable the inline preview of R Markdown code chunks. Thus when I press Ctrl-Enter, the code is sent directly to the R console (which makes it easy to further experiment with the code interactively).

**Comment by jdblischak** [comment]
Here's another related issue: https://github.com/rstudio/rstudioapi/issues/75 It is requesting an option to be able to detect if a chunk is being executed inside of a document for inline preview.

**Comment by rgayler** [comment]
I find the inline results previews helpful, in that I don't have to go looking at another document will developing an analysis document.

The difference in behaviour is only visible if you are doing something that depends on the working directory, which for me is limited to file paths for I/O. I use the "here" package to allow me to explicitly specify all file paths relative to the project root. (And I also have a preference for being more explicit in my code.)

Maybe it's worth a mention in the documentation that although workflowr sets the working directory in the R console session and for knitting each analysis file, interactive execution of code from an analysis file may differ, and it's safest to never rely on the working directory being correctly set.

**Comment by Robinlovelace** [comment]
My 10 cents on this: it would be very useful to be able to change these settings using the command line, e.g. via the `rstudioapi` package. Would that be possible? Developing .Rmd documents with the output going in-line is very confusing to me and many other users I think, so it would be great if this could be set somewhere durable, e.g. in a `.Rprofile` file.

**Comment by jdblischak** [comment]
> Developing .Rmd documents with the output going in-line is very confusing to me and many other users I think

@Robinlovelace I agree 100%. I find it very frustrating that this "notebook" style is the default even when opening an R Markdown file (I think it should only be activated when opening an R Notebook file).

> it would be great if this could be set somewhere durable, e.g. in a .Rprofile file.

Also agree 100%. The RStudio developers have been discussing this for over a year, but there is still no implementation. Please add your :+1: to the issue here: https://github.com/rstudio/rstudio/issues/1607

Some other R users and I were recently commiserating about the difficulty of disabling displaying inline code on Twitter:

https://twitter.com/jdblischak/status/1098270686404067330
https://twitter.com/jdblischak/status/1098278827434930176

**Comment by jdblischak** [comment]
I've done some more research on this Issue.

> Developing .Rmd documents with the output going in-line is very confusing to me and many other users I think, so it would be great if this could be set somewhere durable, e.g. in a .Rprofile file.

@Robinlovelace I found a plain-text option for disabling inline output. Adding the following to the YAML header of the R Markdown file will disable inline output (even if the Global Options has it activated):

```
editor_options:
  chunk_output_type: console
```

The downside is that it has to be specified in each individual R Markdown file.

I am considering adding the above to the default R Markdown files that get added with `wflow_start()` and also `wflow_open()`.

Users that prefer inline code chunks can either delete those two lines or explicitly enable inline output with:

```
editor_options:
  chunk_output_type: inline
```

**Comment by jdblischak** [comment]
> Maybe it's worth a mention in the documentation that although workflowr sets the working directory in the R console session and for knitting each analysis file, interactive execution of code from an analysis file may differ, and it's safest to never rely on the working directory being correctly set.

@rgayler Another option for maintaining the correct working directory when using inline output is to specify `root.dir` in the special "setup" chunk.

https://twitter.com/ma_salmon/status/1113725572759339008
https://community.rstudio.com/t/what-defines-the-setup-chunk/27595
https://community.rstudio.com/t/knitr-opts-knit-set-root-dir-ignored-when-chunk-output-type-console/27665

Below is a minimal example. First in RStudio, change the "Knit Directory" setting to "Document Directory". Thus we would expect the inline code to always be run from `analysis/`. However, the setup chunk in the Rmd file below ensures that the inline code chunks are also executed in the root of the project.

````
---
output: workflowr::wflow_html
editor_options:
  chunk_output_type: inline
---

```{r setup}
knitr::opts_knit$set(root.dir = "..")
```

```{r}
getwd()
```
````

And of course all this extra setup assumes that the user wants to execute the code from the project directory. If instead you'd prefer to have the code execute from `analysis/`, you can always set `knit_root_dir: "analysis/"` in `_workflowr.yml`, or delete `knit_root_dir` entirely.
