### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by wlandau** [workflowr/workflowr#145]
I recommend adding a [pull request template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository) to the [`.github` folder](https://github.com/jdblischak/workflowr/tree/master/.github), maybe with a [checklist](https://github.com/ropensci/drake/blob/master/.github/PULL_REQUEST_TEMPLATE.md#checklist) adapted from the bullet points in [`CONTRIBUTING.md`](https://github.com/jdblischak/workflowr/blob/master/CONTRIBUTING.md#contributing). I see this as a a nice beginner issue for the [Chicago R Unconference](https://chirunconf.github.io/). The issue itself may even help unconf attendees contribute to `workflowr` in other ways.

**Comment by jdblischak** [comment]
@wlandau Great idea! I do need a PR template for workflowr.
