### ISSUE TITLE
Fix spacing before "session info" button

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#157]
@jdblischak This is a minor "bug", but it would be good if you could somehow adjust the spacing between the "session info" button and the text so that it is more consistent. I'm not sure how the rendering works exactly, but I'm attaching an example where there is too much spacing. In this case it occurred because I added some non-display R Markdown to the end of my `.Rmd` file:

```markdown
The "Session information" button below gives the version of R and the
packages that were used to generate these results. This listing
includes the R packages that were also used to run the DSC.

[github-repo]:     https://github.com/stephenslab/dsc-linreg
[susie]:           https://doi.org/10.1101/501114
[varbvs]:          https://projecteuclid.org/euclid.ba/1339616726
[zou-hastie-2005]: https://doi.org/10.1111/j.1467-9868.2005.00503.x
```

My workaround was to put the links in a different place. This example comes from [here](https://github.com/stephenslab/dsc-linreg).

<img width="942" alt="screenshot" src="https://user-images.githubusercontent.com/1503904/55878974-2f99a880-5b63-11e9-995c-26ce20005589.png">

**Comment by jdblischak** [comment]
Wow. Strange. Thanks for reporting. I was able to replicate the bug.

If there are markdown links at the bottom of the Rmd:

````

```{r}
1+1
```

The "Session information" button below gives the version of R and the
packages that were used to generate these results. This listing
includes the R packages that were also used to run the DSC.

[github-repo]:     https://github.com/stephenslab/dsc-linreg
[susie]:           https://doi.org/10.1101/501114
[varbvs]:          https://projecteuclid.org/euclid.ba/1339616726
[zou-hastie-2005]: https://doi.org/10.1111/j.1467-9868.2005.00503.x
````

The corresponding HTML is:

```
<p>The “Session information” button below gives the version of R and the packages that were used to generate these results. This listing includes the R packages that were also used to run the DSC.</p>
<br> <br>
<p>
<button type="button" class="btn btn-default btn-workflowr btn-workflowr-sessioninfo" data-toggle="collapse" data-target="#workflowr-sessioninfo" style="display: block;">
```

In contrast, if there are no markdown links at the bottom of the Rmd:

````

```{r}
1+1
```

[github-repo]:     https://github.com/stephenslab/dsc-linreg
[susie]:           https://doi.org/10.1101/501114
[varbvs]:          https://projecteuclid.org/euclid.ba/1339616726
[zou-hastie-2005]: https://doi.org/10.1111/j.1467-9868.2005.00503.x

The "Session information" button below gives the version of R and the
packages that were used to generate these results. This listing
includes the R packages that were also used to run the DSC.
````

The corresponding HTML is:

```
The “Session information” button below gives the version of R and the packages that were used to generate these results. This listing includes the R packages that were also used to run the DSC. <br> <br>
<p>
<button type="button" class="btn btn-default btn-workflowr btn-workflowr-sessioninfo" data-toggle="collapse" data-target="#workflowr-sessioninfo" style="display: block;">
```

Essentially, the ending of the file is affecting the distribution of `p` and `br` elements. I'll investigate.

**Comment by pcarbo** [comment]
@jdblischak Simply adding extra blank lines to the end will also add extra spacing before the "session info", which isn't ideal.

**Comment by jdblischak** [comment]
@pcarbo This appears to be another issue generated by pandoc 2.0.

The extra spacing is actually supposed to be the default behavior. I purposefully did this because I felt that the session information button is too easily missed when it is immediately next to a block of text (or code chunk or plot). Offsetting it made it standout. If you re-run `wflow_build()` with pandoc 1.x, you should see the offset consistently applied across all of your files.

The problem appears to be that pandoc 2.0 only sometimes fails to surround the final sentence of text in `p` elements. This disrupts the intended spacing, leading to the appearance you prefer.

Could you please run `rmarkdown::pandoc_version()` and report the version you are using?

**Comment by pcarbo** [comment]
@jdblischak 

```
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
```

**Comment by jdblischak** [comment]
@pcarbo Thanks for confirming. That rules out that hypothesis (I got confused b/c I had made some experimental edits and forgot to remove them prior to testing pandoc 1.x vs 2.x).

**Comment by jdblischak** [comment]
Well now I realize why I hadn't noticed this before. Apparently I tend to end my R Markdown files with a code chunk or figure!

I used my [dc-bioc-limma](https://github.com/jdblischak/dc-bioc-limma) project while implementing the new Bootstrap layout of workflowr 1.2.0. There is only [one Rmd file](https://jdblischak.github.io/dc-bioc-limma/linear-models.html) in that whole project that 1) contains code and 2) ends in a sentence of text. And it does have the issue of not being surrounded by `p` tags:

https://github.com/jdblischak/dc-bioc-limma/blob/6f4d83b51640a0b5af65f590f35cfbf00ef45b92/docs/linear-models.html#L1007

And thus its button is much closer compared to the other files:

![Screenshot from 2019-04-10 16-26-05](https://user-images.githubusercontent.com/1608317/55910844-62688e80-5bad-11e9-8a01-62fa79c6b3fd.png)

**Comment by jdblischak** [comment]
@pcarbo Could you please test out the dev branch? The spacing for the session info button should now be consistent across the files, no matter if it ends in code, figure, text, or link. Also, I reduced it from 2 `<br>` to only 1. Please let me know what you think.

**Comment by pcarbo** [comment]
@jdblischak Yes, looks good now with the fix.
