### ISSUE TITLE
Question: set bibliography field in the _site.yml, but it doesn't work

### ISSUE THREAD

**Issue by JiaxiangBU** [workflowr/workflowr#158]
I find a related issue, https://github.com/jdblischak/workflowr/issues/102, but I want to set the bibliography field as a default option for each analysis document. Thus, I put it in the `_site.yml` but it doesn't work.

1. only when I write `bibliography: add.bib` in a specific document, it works in this specific document.
1. I don't know too much about the `_site.yml` function, seemingly it works like an setting for all analysis document.

For the reproducible purpose, I create a workflowr project, https://github.com/JiaxiangBU/test-workflowr.

1. in the document [learn-literate-prog.Rmd](https://github.com/JiaxiangBU/test-workflowr/blob/master/analysis/learn-literate-prog.Rmd), I specify `bibliography: add.bib
`, thus the bibtex works in this pages [learn-literate-prog](https://jiaxiangbu.github.io/test-workflowr/learn-literate-prog)
1. in the document [learn-literate-prog-2.Rmd](https://github.com/JiaxiangBU/test-workflowr/blob/master/analysis/learn-literate-prog-2.Rmd), I don't specify `bibliography: add.bib
` and set it in the [_site.yml](https://github.com/JiaxiangBU/test-workflowr/blob/master/analysis/_site.yml), but the bibtex works in this pages [learn-literate-prog-2](https://jiaxiangbu.github.io/test-workflowr/learn-literate-prog-2)

**Comment by jdblischak** [comment]
> only when I write bibliography: add.bib in a specific document, it works in this specific document.

When you specify `bibliography` in the YAML header of the R Markdown file, this gets passed directly to pandoc.

> I don't know too much about the _site.yml function, seemingly it works like an setting for all analysis document.

The rmarkdown package does not support sharing pandoc options across R Markdown files using the `_site.yml` file. You can only share options to the output format function (`wflow_html()` in the case of workflowr).

Thus the workaround is to pass the pandoc arguments via the rmarkdown output format function using the argument `pandoc_args` (see `?rmarkdown::html_document`):

```
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    pandoc_args: ["--bibliography=add.bib"]
```

> For the reproducible purpose, I create a workflowr project, https://github.com/JiaxiangBU/test-workflowr.

Thank you for the very clear example! I sent PR https://github.com/JiaxiangBU/test-workflowr/pull/1 to your repo to demonstrate how to use a common bibliography.

**Comment by jdblischak** [comment]
The downside of using `pandoc_args` to specify a common bibliography is that workflowr does not currently notice this, and thus the session information button will be inserted before the references. The fix to #102 in 3f2f9604dc8d5db8a9fbb44312f776118d67393a only handles the case where the bibliography is specified in the YAML header. The quickest workaround is to manually insert `<div id="refs"></div>` to specify the location of the bibliography.

https://github.com/jdblischak/workflowr/blob/c959fd84256b648a2ea5ac0b5c8eedfb6d94d0ec/R/wflow_html.R#L385-L393

**Comment by JiaxiangBU** [comment]
> Thank you for the very clear example! I sent PR [JiaxiangBU/test-workflowr#1](https://github.com/JiaxiangBU/test-workflowr/pull/1) to your repo to demonstrate how to use a common bibliography.

Hi, John, thanks for your clear explanation, not only fix this issue but also I learn a lot from this option `pandoc_args`.

**Comment by JiaxiangBU** [comment]
Next question, can I share the author name in the sort of `_site.yml` fora non-workflowr-project? 
I know, *the analysis document created by the function `wflow_open` include an author name option*.

Simply I try to add a line `author: xxx` in the `_site.yml` but it doesn't work.

https://github.com/JiaxiangBU/test-workflowr/blob/5ddd8a87cd954e931c967ab98108aa8dc637ab62/analysis/_site.yml#L3

Also I find the option `author` is not included in the `pandoc_args`.

```
>pandoc --help
pandoc [OPTIONS] [FILES]
  -f FORMAT, -r FORMAT  --from=FORMAT, --read=FORMAT
  -t FORMAT, -w FORMAT  --to=FORMAT, --write=FORMAT
  -o FILENAME           --output=FILENAME
                        --data-dir=DIRECTORY
  -R                    --parse-raw
  -S                    --smart
                        --old-dashes
                        --base-header-level=NUMBER
                        --indented-code-classes=STRING
  -F PROGRAM            --filter=PROGRAM
                        --normalize
  -p                    --preserve-tabs
                        --tab-stop=NUMBER
                        --track-changes=accept|reject|all
                        --file-scope
                        --extract-media=PATH
  -s                    --standalone
                        --template=FILENAME
  -M KEY[:VALUE]        --metadata=KEY[:VALUE]
  -V KEY[:VALUE]        --variable=KEY[:VALUE]
  -D FORMAT             --print-default-template=FORMAT
                        --print-default-data-file=FILE
                        --dpi=NUMBER
                        --no-wrap
                        --wrap=auto|none|preserve
                        --columns=NUMBER
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
                        --no-highlight
                        --highlight-style=STYLE
  -H FILENAME           --include-in-header=FILENAME
  -B FILENAME           --include-before-body=FILENAME
  -A FILENAME           --include-after-body=FILENAME
                        --self-contained
                        --html-q-tags
                        --ascii
                        --reference-links
                        --reference-location=block|section|document
                        --atx-headers
                        --chapters
                        --top-level-division=section|chapter|part
  -N                    --number-sections
                        --number-offset=NUMBERS
                        --no-tex-ligatures
                        --listings
  -i                    --incremental
                        --slide-level=NUMBER
                        --section-divs
                        --default-image-extension=extension
                        --email-obfuscation=none|javascript|references
                        --id-prefix=STRING
  -T STRING             --title-prefix=STRING
  -c URL                --css=URL
                        --reference-odt=FILENAME
                        --reference-docx=FILENAME
                        --epub-stylesheet=FILENAME
                        --epub-cover-image=FILENAME
                        --epub-metadata=FILENAME
                        --epub-embed-font=FILE
                        --epub-chapter-level=NUMBER
                        --latex-engine=PROGRAM
                        --latex-engine-opt=STRING
                        --bibliography=FILE
                        --csl=FILE
                        --citation-abbreviations=FILE
                        --natbib
                        --biblatex
  -m[URL]               --latexmathml[=URL], --asciimathml[=URL]
                        --mathml[=URL]
                        --mimetex[=URL]
                        --webtex[=URL]
                        --jsmath[=URL]
                        --mathjax[=URL]
                        --katex[=URL]
                        --katex-stylesheet=URL
                        --gladtex
                        --trace
                        --dump-args
                        --ignore-args
                        --verbose
                        --bash-completion
                        --list-input-formats
                        --list-output-formats
                        --list-extensions
                        --list-highlight-languages
                        --list-highlight-styles
  -v                    --version
  -h                    --help
```

**Comment by JiaxiangBU** [comment]
I read a issue here, https://github.com/rstudio/rmarkdown/issues/297 .
Seemingly the `_output.yaml` and `_site.yml` have the similar function, but the latter has a larger scope and broaden the setting except the `output` option. Does it make sense?

**Comment by JiaxiangBU** [comment]
Hi @jdblischak John, I am trying to use `here::here()` inside the `pandoc_args`. But it doesn't work.
Do you know whether this option supports the r inline code? 

```
pandoc_args: ["--bibliography=`r here::here(...)`"]
```

**Comment by jdblischak** [comment]
> Do you know whether this option supports the r inline code?

@JiaxiangBU I don't think inline R code is supported for arguments that are passed to R Markdown output formats (e.g. `wflow_html()`, `html_document()`, etc.). Instead of using `here::here()`, you can specify the relative path from the R Markdown file to the bibliography file. For example, if the file `add.bib` is in the same subdirectory as the R Markdown file, you would write `["--bibliography=add.bib"]`. If `add.bib` is one directory upstream (e.g. in the root directory of the workflowr project), you would write `["--bibliography=../add.bib"]`.

**Comment by jdblischak** [comment]
> can I share the author name in the sort of _site.yml fora non-workflowr-project?

@JiaxiangBU You can specify arbitrary metadata values using the `--metadata` argument to pandoc.

For example, the `output` section below will add the bibliogaphy and the author name to every R Markdown file:

```
output:
  workflowr::wflow_html:
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
    pandoc_args: ["--bibliography", "add.bib",
                  "--filter", "pandoc-citeproc",
                  "--metadata", "author=Jiaxiang Li"]
```

**Comment by jdblischak** [comment]
@JiaxiangBU I think we've addressed all of your questions. Please feel free to open a new issue if there are still pandoc options you are having trouble using with workflowr. Also, if you have time, I'd welcome a Pull Request that explains some of these strategies in the vignette [Customize your research website](https://github.com/jdblischak/workflowr/blob/master/vignettes/wflow-02-customization.Rmd).
