### ISSUE TITLE
Suggestion for including an image in the analysis document

### ISSUE THREAD

**Issue by JiaxiangBU** [workflowr/workflowr#159]
> Before posting your issue, please search the existing issues (both "open" and "closed") to check that a similar feature has not already been requested.

I read some created issues

1. the issues https://github.com/jdblischak/workflowr/issues/103 and https://github.com/jdblischak/workflowr/issues/37#issuecomment-387744317
1. the discussion in the issue https://github.com/jdblischak/workflowr/issues/119
1. the tips under https://github.com/jdblischak/workflowr/commit/3f6f104d50a8d600efef799ad5ec5934b76bf988

The @jdblischak advice helps the users create `docs/assets` and see the external images in the HTML document by knitting the analysis document or the function  `wflow_build`.

But since the image document is under the  `docs/assets` , the users cannot preview this image under the analysis document. Also, the relative path of this image is not under `docs/assets` .
The users cannot use <kbd>tab</kbd> to quickly get the image path.

> 1. Describe the suggested feature.

Just use the absolute path? the image is stored in a public repo.

> 2. Describe why you think this feature is needed.

If the image is stored in a public path, the users just copy the absolute path and they can 

1. preview it in the analysis document
1. see it in the HTML document after knitted.

> 3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

```
> packageVersion("workflowr")
[1] ‘1.2.0’
```

**Comment by jdblischak** [comment]
@JiaxiangBU Sorry for the delay. I lost track of this Issue. I liked your suggestion, and I updated the FAQ response in commit 196ba9e.
