### ISSUE TITLE
Cannot detect workflowr project

### ISSUE THREAD

**Issue by FangBigSheep** [workflowr/workflowr#161]
@pcarbo and I identified the following bug on my computer (Windows). I am in the workflowr project directory, but `wflow_build` does not recognize it. I get the following error:

```
> wflow_build("analysis/index.Rmd")
Error: Unable to detect a workflowr project. This could be due to one of
the following reasons:

1) The function was not executed inside a workflowr project. Run
`getwd()` to determine the current working directory. Is the
working directory a workflowr project or one of its
subdirectories?

2) The RStudio .Rproj file was deleted. workflowr requires an
RStudio .Rproj file to be located at the root of the project. Was
it deleted?
```

But I am definitely in a workflowr project (created with `wflow_start`):

```
> getwd()
[1] "C:/Users/fangz/Documents/GitHub/myproject"
> list.files()
[1] "_workflowr.yml"  "analysis"        "code"           
[4] "data"            "docs"            "myproject.Rproj"
[7] "output"          "README.md"      
```

Here is more info about my setup:

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.3.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.3  magrittr_1.5    htmltools_0.3.6 tools_3.5.3    
 [5] fs_1.2.6        yaml_2.2.0      Rcpp_1.0.1      stringi_1.4.3  
 [9] rmarkdown_1.12  knitr_1.22      stringr_1.4.0   xfun_0.5       
[13] digest_0.6.18   evaluate_0.13  
```

**Comment by pcarbo** [comment]
An update on this: we were able to get it working after upgrading all the dependencies using `devtools::install_github`. I'm not sure what the problem was, but there was probably some fundamental issue, and I wonder whether you are suppressing errors or warnings that could be useful for understanding the issue.

**Comment by jdblischak** [comment]
This behavior is implemented in the package rprojroot. Could you please
check the date that package was updated? You can do this by looking at the
modification date of the rprojroot directory in your R library directory.

**Comment by jdblischak** [comment]
The most recent release of [rprojroot](https://cran.r-project.org/package=rprojroot) was in January 2018. Thus it has been stable for awhile. I looked at the [NEWS entry for the GitHub version 1.3.2.900](https://github.com/r-lib/rprojroot/blob/master/NEWS.md#rprojroot-1329000-2018-03-29), and I didn't see anything that was likely a problem.

@FangBigSheep Could you please try the following?

1. Install rprojroot from CRAN with `install.packages("rprojroot")`
2. Create a test project with `wflow_start()`
3. Run `wflow_build()`

**Comment by FangBigSheep** [comment]
@jdblischak Thanks for your reply. The issue has been solved by updating all the dependencies, and it is working now. However, I cannot reproduce how this problem arises. I'm afraid I don't have information about what causes this.

**Comment by jdblischak** [comment]
@FangBigSheep OK. Thanks for reporting the issue! I'm going to close it for now. Please re-open if you experience similar errors in the future.
