### ISSUE TITLE
Workflowr assumes https protocol instead of http - broken links to old versions

### ISSUE THREAD

**Issue by antass** [workflowr/workflowr#163]
1. Give the exact command or line of code you ran that caused the issue, e.g., `wflow_publish(republish = TRUE)`.

2. Describe the result of running the command or code, including any warning or error messages.

The links to old versions / git commits are broken. Paths assume `https` protocol. I can manually edit the path to the whole repo in public/_site.yml, which then works. But there is nowhere to change the path for the individual commit links (I assume they get rendered by pasting `https://`, `$domain`, `$user.name`, `$repo.name`.

3. Tell us about your computing environment, including the version of R, RStudio and workflowr you are using. The simplest way to do this is to run `sessionInfo()` in R (and `RStudio.Version()` if you are using RStudio) and copy the output here.

I am using a custom install of GitLab at `http://mycompany.com`.

```
> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 os       Ubuntu precise (12.04.4 LTS)
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-05-03                  

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package                        * version    date       lib source        
 AG120.C.001.cholangio.20190116 * 0.0.0.9000 2019-05-03 [1] local         
 assertthat                       0.2.1      2019-03-21 [1] CRAN (R 3.4.2)
 backports                        1.1.4      2019-04-10 [1] CRAN (R 3.4.2)
 callr                            3.2.0      2019-03-15 [1] CRAN (R 3.4.2)
 cli                              1.1.0      2019-03-19 [1] CRAN (R 3.4.2)
 crayon                           1.3.4      2017-09-16 [1] CRAN (R 3.4.2)
 desc                             1.2.0      2018-05-01 [1] CRAN (R 3.4.2)
 devtools                         2.0.2      2019-04-08 [1] CRAN (R 3.4.2)
 digest                           0.6.18     2018-10-10 [1] CRAN (R 3.4.2)
 evaluate                         0.13       2019-02-12 [1] CRAN (R 3.4.2)
 fs                               1.3.0      2019-05-02 [1] CRAN (R 3.4.2)
 getPass                          0.2-2      2017-07-21 [1] CRAN (R 3.4.2)
 git2r                            0.25.2     2019-03-19 [1] CRAN (R 3.4.2)
 glue                             1.3.1      2019-03-12 [1] CRAN (R 3.4.2)
 htmltools                        0.3.6      2017-04-28 [1] CRAN (R 3.4.2)
 knitr                            1.22       2019-03-08 [1] CRAN (R 3.4.2)
 magrittr                         1.5        2014-11-22 [2] CRAN (R 3.4.2)
 memoise                          1.1.0      2017-04-21 [1] CRAN (R 3.4.2)
 pkgbuild                         1.0.3      2019-03-20 [1] CRAN (R 3.4.2)
 pkgload                          1.0.2      2018-10-29 [1] CRAN (R 3.4.2)
 prettyunits                      1.0.2      2015-07-13 [1] CRAN (R 3.4.2)
 processx                         3.3.0      2019-03-10 [1] CRAN (R 3.4.2)
 ps                               1.3.0      2018-12-21 [1] CRAN (R 3.4.2)
 R6                               2.4.0      2019-02-14 [1] CRAN (R 3.4.2)
 Rcpp                             1.0.0      2018-11-07 [1] CRAN (R 3.4.2)
 remotes                          2.0.4      2019-04-10 [1] CRAN (R 3.4.2)
 rlang                            0.3.1.9000 2019-03-05 [1] local         
 rmarkdown                        1.12       2019-03-14 [1] CRAN (R 3.4.2)
 rprojroot                        1.3-2      2018-01-03 [1] CRAN (R 3.4.2)
 rstudioapi                       0.10       2019-03-19 [1] CRAN (R 3.4.2)
 sessioninfo                      1.1.1      2018-11-05 [1] CRAN (R 3.4.2)
 stringi                          1.4.3      2019-03-12 [1] CRAN (R 3.4.2)
 stringr                          1.4.0      2019-02-10 [1] CRAN (R 3.4.2)
 testthat                       * 2.1.1      2019-04-23 [1] CRAN (R 3.4.2)
 usethis                        * 1.5.0      2019-04-07 [1] CRAN (R 3.4.2)
 withr                            2.1.2      2018-03-15 [1] CRAN (R 3.4.2)
 workflowr                      * 1.3.0      2019-04-15 [1] CRAN (R 3.4.2)
 xfun                             0.6        2019-04-02 [1] CRAN (R 3.4.2)
 yaml                             2.2.0      2018-07-25 [1] CRAN (R 3.4.2)

[1] /home/nfs/ania.tassinari/R/x86_64-pc-linux-gnu-library/3.4
[2] /data2/software/R/3.4.2/lib/R/library
```

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.4 LTS)

Matrix products: default
BLAS: /data2/software/R/3.4.2/lib/R/lib/libRblas.so
LAPACK: /data2/software/R/3.4.2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.3.0                           AG120.C.001.cholangio.20190116_0.0.0.9000
[3] testthat_2.1.1                            usethis_1.5.0                            

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0        compiler_3.4.2    git2r_0.25.2      prettyunits_1.0.2 remotes_2.0.4     tools_3.4.2      
 [7] getPass_0.2-2     digest_0.6.18     pkgbuild_1.0.3    pkgload_1.0.2     evaluate_0.13     memoise_1.1.0    
[13] rlang_0.3.1.9000  cli_1.1.0         rstudioapi_0.10   yaml_2.2.0        xfun_0.6          withr_2.1.2      
[19] stringr_1.4.0     knitr_1.22        desc_1.2.0        fs_1.3.0          devtools_2.0.2    rprojroot_1.3-2  
[25] glue_1.3.1        R6_2.4.0          processx_3.3.0    rmarkdown_1.12    sessioninfo_1.1.1 callr_3.2.0      
[31] magrittr_1.5      backports_1.1.4   ps_1.3.0          htmltools_0.3.6   assertthat_0.2.1  stringi_1.4.3    
[37] crayon_1.3.4    
```

**Comment by antass** [comment]
BTW, I am using a custom install of GitLab at `http://mycompany.com`.

**Comment by jdblischak** [comment]
Hi Ania! Sorry that HTTP is not currently supported. That is an artifact of
the development history of workflowr. You're the first to request this,
which is why I hadn't added it earlier. I'll add support for this in the
next release.

**Comment by jdblischak** [comment]
@antass A quick follow-up. I realized there might be a quick short-term solution you can use to fix this immediately for your current workflowr project.

Are you using HTTP or SSH for pushing and pulling to and from your custom install of GitLab? You can run the code below to confirm. If the remote URL starts with `git@`, then it is SSH. If it starts with `http://mycompany.com`, then it is HTTP.

```
library(git2r)
r <- repository()
remote_url(r, remote = "origin")
```

If you're using HTTP, then you can manually set the URL for your Git repository to use the HTTP address of your custom GitLab install. You can do this by running the following in your R console (after updating `<repo.name>`.

```
remote_set_url(r, name = "origin", url = "http://mycompany.com/antass/<repo.name>.git")
```

Since workflowr uses the URL for "origin" to create the links to past versions of the R Markdown files and figures, this should fix everything. Please let me know if this works for you.

**Comment by jdblischak** [comment]
@antass A few more follow-ups. I am pretty certain that you are using the SSH protocol. If you rely on workflowr to guess the URL to the remote repository, it guesses HTTPS. You can override this by specifying the exact URL to use in the `_workflowr.yml`file. For example, you can add the following line:

```
github: http://mycompany.com
```

And then republish the files with:

```
wflow_publish("_workflowr.yml", republish = TRUE)
```

This will fix all the links to past versions to start with `http://mycompany.com`.

The name `github` is an anachronism from when workflowr only officially supported GitHub. I plan to update it to something more generic (e.g. `git_url`) in the future, but I'll maintain the `github` option for backwards-compatibility.

Please try this and let me know if it fixes your URLs.

**Comment by antass** [comment]
@jdblischak thanks so much for looking into this!

Yes, I am using the SSH protocol, mostly because I don't want to have to type my username and password more often than I need to. 

Adding `github: http://mycompany.com` to `_workflowr.yml` definitely solved the problem of the domain in links to past versions. Previewing the URLs now gives:

```
http://mycompany.com/blob/511f5670afe3949bea08e47cacbcc415fe674c1e/public/index.html
```

However, the link throws gitlab-specific 404 error. I'm wondering if the way these blob URLs are built might be specific to GitHub.  It looks like for GitLab, the link assumes that `blob` is a user.

The way these links (*I think*) should look like for GitLab is:

```
http://mycompany.com/user.name/repo.name/tree/511f5670afe3949bea08e47cacbcc415fe674c1e
```

![Screen Shot 2019-05-08 at 1 00 12 PM](https://user-images.githubusercontent.com/1278698/57393545-5282a100-7191-11e9-8ed3-767f6575521f.png)


I don't know exactly where the links to previous versions are *supposed* to lead, though, so this might not be very helpful.

**Comment by jdblischak** [comment]
> However, the link throws gitlab-specific 404 error. I'm wondering if the way these blob URLs are built might be specific to GitHub. It looks like for GitLab, the link assumes that blob is a user.

@antass Sorry. That was bad advice on my part. The URL in `_workflowr.yml` needs to include the username and repo. Thus `_workflowr.yml` should contain something like the following:

```
github: http://mycompany.com/user.name/repo.name
```

The reason for this is that this is meant to override the setting of the remote URL for "origin". For example, if multiple collaborators are building a workflowr project, they would want to use the URL to the main repository, and not the URL to their own fork of the repo. See `?wflow_html` for more information.

Also, the URL leads to the HTML file at that commit, which is why `blob` is in the URL. Your URL with `tree` leads to the top-level of the repository at that given commit, which would require then manually navigating to the file of interest.

**Comment by jdblischak** [comment]
I added an FAQ entry in commit b7a192a03c610908c4ed24a6c1211e0f3488b1d9 on how to use the HTTP protocol.
