### ISSUE TITLE
Workflowr in linux

### ISSUE THREAD

**Issue by Heroico** [workflowr/workflowr#166]
Hi there!

I'm using workflowr in linux, on an environment built with conda for reproducibility.

Whenever I run `workflowr::wflow_build()`, I get at the end:
```
> Couldn't get a file descriptor referring to the console
```
I believe this is caused by workflowr doing a command line call to `open` and expecting it to be Mac OSX `open` utility. This seems to cause some instability as I get random errors that go away when I restart the R session.

One of these is that knittr's cache gets corrupted. I typically use the cache while writing the R markdown to save time, and disable it when I'm done.

I noticed that the travis test suite tests only in Mac. Are there specific steps I need to do to have workflowr setup in linux?

Thansk in advance!

**Comment by jdblischak** [comment]
> I'm using workflowr in linux, on an environment built with conda for reproducibility.

@Heroico Sounds like a great strategy! I also regularly use the combination of linux+conda+workflowr :-)

> I noticed that the travis test suite tests only in Mac. Are there specific steps I need to do to have workflowr setup in linux?

The package is regularly tested on all 3 main operating systems:

* Linux: https://circleci.com/gh/jdblischak/workflowr/tree/master
* macOS: https://travis-ci.org/jdblischak/workflowr
* Windows: https://ci.appveyor.com/project/jdblischak/workflowr

> Whenever I run workflowr::wflow_build(), I get at the end:

Could you please try the following and report your results?

* What is the output of `getOption("browser")` when you run it inside of R in your conda environment?
* What happens if you run `workflowr::wflow_build(view = FALSE)`? Please include the command and all the output in addition to the final error message.

Some further questions about your setup:

* What versions of conda, R, and workflowr are you using?
* What flavor of Linux are you using? You can check with `sessionInfo()`. Also, are you running this on a desktop computer or remote server?

I wasn't able to reproduce the bug on my Ubuntu desktop:

```
## Creating conda environment
conda --version
## conda 4.6.14
conda create -y -n issue-166 r-workflowr
source activate issue-166
```

```
## Running in R
packageVersion("workflowr")
## [1] ‘1.1.1’
library(workflowr)
## This is workflowr version 1.1.1
## Run ?workflowr for help getting started
wflow_start(tempfile())
## wflow_start:
## - New directory created at /tmp/RtmpgdTLy6/file2e6744ec868e
## - Project name is "file2e6744ec868e"
## - Working directory changed to /tmp/RtmpgdTLy6/file2e6744ec868e
## - Git repo initiated at /tmp/RtmpgdTLy6/file2e6744ec868e
## - Files were committed in version 6296363
wflow_build()
## Building 3 file(s):
## Building analysis/about.Rmd
## Building analysis/index.Rmd
## Building analysis/license.Rmd
## Summary from wflow_build
## 
## Settings:
##  make: TRUE
## 
## The following were built externally each in their own fresh R session: 
## 
## docs/about.html
## docs/index.html
## docs/license.html
## 
## Log files saved in /tmp/RtmpgdTLy6/workflowr
getOption("browser")
## [1] ""
sessionInfo()
## R version 3.5.1 (2018-07-02)
## Platform: x86_64-conda_cos6-linux-gnu (64-bit)
## Running under: Ubuntu 18.04.2 LTS
## 
## Matrix products: default
## BLAS/LAPACK: /home/jdb-work/miniconda3-conda-forge/envs/issue-166/lib/R/lib/libRblas.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] workflowr_1.1.1
## 
## loaded via a namespace (and not attached):
##  [1] Rcpp_1.0.1        ps_1.3.0          rprojroot_1.3-2   digest_0.6.19    
##  [5] R.methodsS3_1.7.1 R6_2.4.0          backports_1.1.4   magrittr_1.5     
##  [9] git2r_0.25.2      evaluate_0.14     stringi_1.4.3     rstudioapi_0.10  
## [13] callr_3.2.0       R.oo_1.22.0       R.utils_2.8.0     rmarkdown_1.12   
## [17] tools_3.5.1       stringr_1.4.0     glue_1.3.1        processx_3.3.1   
## [21] yaml_2.2.0        xfun_0.7          compiler_3.5.1    htmltools_0.3.6  
## [25] knitr_1.23      
```

> One of these is that knittr's cache gets corrupted. I typically use the cache while writing the R markdown to save time, and disable it when I'm done.

I'm not sure how this is related. If workflowr fails, the knitr cache should not be invalidated. If this issue persists, please provide a minimal reproducible example so that I can investigate. Using [RStudio Cloud](https://rstudio.cloud/) is a convenient way to share an example workflowr project.

**Comment by jdblischak** [comment]
@Heroico Are you still having Issues with workflowr on Linux?

**Comment by Heroico** [comment]
Hi John,

I apologize for the delay in answering.

I'm running on a remote linux server (CRI):
```
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux ComputeNode release 6.7 (Santiago)

Matrix products: default
BLAS/LAPACK: /home/abarbeira3/.conda/envs/pyr/lib/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.3.0

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  backports_1.1.2 magrittr_1.5    rprojroot_1.3-2
 [5] tools_3.5.1     htmltools_0.3.6 Rcpp_0.12.18    stringi_1.2.4  
 [9] rmarkdown_1.10  knitr_1.20      stringr_1.3.1   digest_0.6.15  
[13] evaluate_0.11 
```
I'm using `miniconda 2 / 4.4.10`, `R / 3.5.1`. `workflowr 1.3.0`

```
> getOption("browser")
[1] "/usr/bin/firefox"
```
(I login with `ssh -Y` to enable X applications)


The cache corruption is intermittent and I still haven't figured out a pattern. 

However I've been running `workflowr::wflow_build(view = FALSE)` for a few hours and it hasn't happened yet. The `> Couldn't get a file descriptor referring to the console` message went away with `view = FALSE`.

**Comment by jdblischak** [comment]
> However I've been running workflowr::wflow_build(view = FALSE) for a few hours and it hasn't happened yet. The > Couldn't get a file descriptor referring to the console message went away with view = FALSE.

Great! As I suspected, workflowr was failing to open a browser. One option is to continue to run `wflow_build()` and `wflow_publish()` with the argument `view = FALSE`. Another option is to add the line `options(browser = "")` to the `.Rprofile` file inside of your workflowr project. When the option `browser` is set to the empty string, workflowr does not attempt to open a browser.

> (I login with ssh -Y to enable X applications)

Did you expect workflowr to be able to open a browser window? Are you able to open Firefox from your SSH session? For example, does either of the following work?

1. `/usr/bin/firefox docs/index.html`
1. `Rscript -e 'system("/usr/bin/firefox docs/index.html")'`

**Comment by Heroico** [comment]
I fire up `/usr/bin/firefox` from the command line.

I'll keep using the `view = FALSE` option.

**Comment by jdblischak** [comment]
> I fire up /usr/bin/firefox from the command line.

@Heroico Does that mean that both of my suggestions worked? Did they both produce a browser that was X-forwarded from the remote server to your local machine?

> I'll keep using the view = FALSE option.

That resolves the main issue, so I'll close this for now. I'll look into making it easier to disable `view` (e.g. perhaps an option such as `workflowr.view` that can be set to `FALSE`).

> The cache corruption is intermittent and I still haven't figured out a pattern.

If you are able to isolate the cache problem, please open a new issue.

**Comment by Heroico** [comment]
Hi John,

I apologize for being unclear. What I meant is that I regularly use `usr/bin/firefox` on the cluster (to open a jupyter notebook for example).

I just tried `Rscript -e 'system("/usr/bin/firefox docs/index.html")'` at the command line and it opened workflowr products.

The cache issue has not occurred again since I started using `view = FALSE`.

**Comment by jdblischak** [comment]
> I apologize for being unclear. What I meant is that I regularly use usr/bin/firefox on the cluster (to open a jupyter notebook for example).
>
>I just tried Rscript -e 'system("/usr/bin/firefox docs/index.html")' at the command line and it opened workflowr products.

@Heroico Thanks for confirming.

> The cache issue has not occurred again since I started using view = FALSE.

If you'd prefer that the site was automatically opened in the browser, you could explicitly set the option `browser`. I was able to successfully open a workflowr website via firefox from the UChicago RCC Midway server by adding the following lines to the `.Rprofile` inside the workflowr project:

```
firefox <- Sys.which("firefox")
if (firefox != "") {
  options(browser = firefox)
}
```
