### ISSUE TITLE
Self-defined Rmd template within workflowr

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#169]
> Before posting your question, please search the existing issues (both "open" and "closed") to check that a similar question has not already been posted.

I did this suggested search, and it seems that I cannot find any related discussions.

Hi John @jdblischak  I wonder if you could help me find a better way to deal with the following scenario.

During my `workflowr` practice, I have encountered many scenarios where I have to create multiple `Rmd` files with the **same** structure but **different** content. Below is a recent example from teaching.

https://xiangzhu.github.io/stanford-stats116/review_2.html
![Screenshot from 2019-07-31 12-43-06](https://user-images.githubusercontent.com/5986023/62242791-d31bfc80-b390-11e9-809e-5ae88baa6b47.png)

https://xiangzhu.github.io/stanford-stats116/review_6.html
![Screenshot from 2019-07-31 12-44-46](https://user-images.githubusercontent.com/5986023/62242876-02cb0480-b391-11e9-9019-73ebc6b0494a.png)

You can see that these two pages have exactly the same structure, and the only different parts are the bullet points under the section "Review Materials".

Currently I simple copy `review_2.Rmd` to `review_6.Rmd`, and then modify the contents in `review_6.Rmd`. This solution is not optimal because if I need to apply a global change to these same-structured pages, I will have to **manually** modify `review_*.Rmd` one by one.

I wonder if I could simply define a "template" within a `workflowr` repo, and then use this template to create the same-structured files. If any global change is needed, I can simply update the "template" only, and then `wflow_publish(review_*.Rmd)` to reflect the global change.

Thanks in advance for your time and help on this issue.

**Comment by jdblischak** [comment]
@xiangzhu Thanks for the feedback! The template functionality you are describing reminds me of a static site generator, e.g. Jekyll, Pelican, Hugo, etc.

A static site generator has template files, e.g. something like:

```
> Instructor’s Note: **all** review materials below are **required** for the
in-class quizzes and/or final exam. However, TAs only have 50 minutes available
for each review session, and thus they will discuss select materials at their
discretion. If time permits, TAs may discuss questions from Canvas Discussion
Page.

## Review materials

{% materials %}
```

And then each file that uses this template would look something like:

```
{% inherit review-template %}

{% begin materials %}
* The multinomial theorem and its proof (page 10)
* Examples 5a, 5b, 5c and 5e (page 10-12)
* All examples from page 33 to 42, except those discussed during lectures
* Examples 2a to 2f (page 57-60)
{% end materials %}
```

That way if you wanted to change something common to all the files, you could edit the template and then regenerate the entire site. Is this the kind of functionality that you were envisioning? Note that I just made up the syntax (though it was inspired by Jekyll).

My initial impression is that this is too far out of scope for workflowr.

I suggest reading the vignette on [Sharing common code across analyses](https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html). It's purpose is to share code chunks, but I think you should be able to use a similar strategy to share prose as well. For example, you could add your "Instructor's note" to a child R Markdown file, and then import the child at the beginning of each of the individual review files.

**Comment by xiangzhu** [comment]
@jdblischak  Many thanks for your replies!

>  Is this the kind of functionality that you were envisioning?

Yes, what you described above is exactly what I hope to achieve. I am not familiar with "static site generator". Is it hard to implement within Rmd?

> My initial impression is that this is too far out of scope for workflowr.

If this feature complicates the (very appealing) simplistic nature of workflowr, I totally agree not to consider it at all. Indeed I think there is already a solution for me; please see below.

> I suggest reading the vignette on Sharing common code across analyses. It's purpose is to share code chunks, but I think you should be able to use a similar strategy to share prose as well. For example, you could add your "Instructor's note" to a child R Markdown file, and then import the child at the beginning of each of the individual review files.

Thanks for the pointer! I was not aware of this vignette. I think this part (https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html#share-child-documents-with-chunk-option) basically gives what I want, without using the  "static site generator". Please feel free to close this ticket.

**Comment by jdblischak** [comment]
> I think this part (jdblischak.github.io/workflowr/articles/wflow-07-common-code.html#share-child-documents-with-chunk-option) basically gives what I want

@xiangzhu Great! If you implement it, could you please follow up with a link here? It will be helpful for me to see another example of how a power user like yourself uses this more advanced feature.

**Comment by xiangzhu** [comment]
@jdblischak  Yes, I will definitely try out this solution very soon, since my Autumn class will start on 2019-09-24. What kind of links should I provide here? E.g. the link to the `Rmd` file?

**Comment by jdblischak** [comment]
As long as you share at least one link, I should be able to find what I need. But if you have the time, I will explore the main Rmd files, the shared child Rmd file, and the HTML files they create. Thanks!

**Comment by xiangzhu** [comment]
@jdblischak  Hi John -- I just try out the solution based on <https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html#share-child-documents-with-chunk-option>, and it works exact the way I want!

- Main `Rmd`: <https://github.com/xiangzhu/stanford-stats60/blob/master/analysis/review_1.Rmd>
- Child `Rmd`: <https://github.com/xiangzhu/stanford-stats60/blob/master/analysis/review_header.Rmd>
- Output `html`: <https://xiangzhu.github.io/stanford-stats60/review_1>

I did not create a sub-folder to organize child `Rmd` files because I only have this one in this particular repo.

**Comment by jdblischak** [comment]
> it works exact the way I want!

Great! I'm glad I thought to suggest it :-) And thanks for sharing your site. It looks great!

> I did not create a sub-folder to organize child Rmd files because I only have this one in this particular repo.

This strategy is fine (i.e. it won't hurt anything). The main downside is that the child Rmd `review_header.Rmd` gets treated as if it is a main analysis file, so workflowr will report that it is unpublished:

```
> wflow_status("analysis/review_header.Rmd")
Status of 1 files

Totals:
 1 Unpublished

The following files require attention:

Unp analysis/review_header.Rmd

Key: Unp = Unpublished

To publish your changes as part of your website, use `wflow_publish()`.

To commit your changes without publishing them yet, use `wflow_git_commit()`.
```

Whereas if you put it in a subdirectory of `analysis/`, then workflowr will ignore it.

**Comment by xiangzhu** [comment]
> The main downside is that the child Rmd review_header.Rmd gets treated as if it is a main analysis file, so workflowr will report that it is unpublished:

Is it possible to have a `wflow_ignore` file to list all these `Rmd` files that are not supposed to be published? This is motivated by the `gitignore` file.

Currently the simplest and most effective solution is to create a sub-folder for these child `Rmd` files.

**Comment by jdblischak** [comment]
> Is it possible to have a wflow_ignore file to list all these Rmd files that are not supposed to be published? This is motivated by the gitignore file.

I don't think this is necessary because there are multiple options for ignoring Rmd files.

> Currently the simplest and most effective solution is to create a sub-folder for these child Rmd files.

This is one option. Workflowr only detects Rmd files that are in the same exact subdirectory as the file `_site.yml`. Thus you could put `review_header.Rmd` in `analysis/templates/`, `templates/`, etc.

You can also change the name of the file. For example, workflowr only recognizes the extensions `.Rmd` and `.rmd`. Thus you could change it to `review_header.txt`. Also, workflowr follows the convention of the rmarkdown package and ignores R Markdown files that begin with an underscore. Thus you could name it `_review_header.Rmd`.
