### ISSUE TITLE
Prevent "dumb" behaviour in wflow_start

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#17]
For example, suppose I run the following:

```R
> wflow_start("myproject","~/")
```

This will automatically populate my home directory with the workflowr files and directories, which doesn't seem desirable. This seems like something a beginning user could do accidentally. To prevent this behaviour, by default I suggest having an additional option in `wflow_start` in which the default behaviour is to create a new directory from scratch (e.g., `new.project = FALSE`).

**Comment by jdblischak** [comment]
Fixed by 0ca27ee
