### ISSUE TITLE
Workflowr stuck in Rmd with BigRQuery

### ISSUE THREAD

**Issue by Heroico** [workflowr/workflowr#174]
Hi there!

I wrote an R markdown analysis that relies on google big query, through `r-dbi/bigrquery`.  

Currently, `r-bigrquery` relies on another library, `r-gargle` to handle authentication with Google API. This asks for user input to handle some login options, causing no problems in interactive sessions or running via Rscript (user input is handled appropriately).

However, the same code gets stuck when trying to build with workflowr:
```
 wflow_build("analysis/miscellaneous_statistics_2.Rmd")
Current working directory: /home/numa/Documents/Projects/gtex_paper/gtex-gwas-analysis
Building 1 file(s):
Building analysis/miscellaneous_statistics_2.Rmd
# <It gets stuck here and doesn't progress>
```
I'm convinced it has something to do with each file being built in its own session, and `r-gargle` chocking in the external session. When I run `wflow_build("analysis/miscellaneous_statistics_2.Rmd", local=TRUE)`, `r-gargle` prompts its question and the file is successfully built.

I was wondering if there is a way to redirect the input from the external R sessions to the current one (where I run the build command). I tried a few quick hacks on workflowr to no avail, and if I could get a few pointer on how to implement this I would be happy to give it a shot.

Here is my session info:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bigrquery_1.2.0.9000 readr_1.2.0          dplyr_0.8.0.1       
[4] workflowr_1.2.0     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2         later_0.7.3        pillar_1.4.2       compiler_3.4.4    
 [5] git2r_0.25.2       prettyunits_1.0.2  progress_1.2.2     tools_3.4.4       
 [9] zeallot_0.1.0      digest_0.6.20      bit_1.1-12         gargle_0.3.1.9000 
[13] jsonlite_1.6       evaluate_0.13      tibble_2.1.3       pkgconfig_2.0.2   
[17] rlang_0.4.0        DBI_1.0.0          curl_4.0           yaml_2.2.0        
[21] xfun_0.5           withr_2.1.2        stringr_1.4.0.9000 httr_1.4.1        
[25] knitr_1.22         askpass_1.1        fs_1.3.1           vctrs_0.2.0       
[29] hms_0.5.0          rprojroot_1.3-2    bit64_0.9-7        tidyselect_0.2.5  
[33] glue_1.3.1.9000    R6_2.4.0           processx_3.3.0     rmarkdown_1.12    
[37] callr_3.2.0        purrr_0.3.2        magrittr_1.5       promises_1.0.1    
[41] backports_1.1.4    ps_1.3.0           htmltools_0.3.6    assertthat_0.2.0  
[45] httpuv_1.4.5       stringi_1.4.4      openssl_1.4.1      crayon_1.3.4      

```

**Comment by jdblischak** [comment]
Thanks for reporting this. I will investigate further.

> This asks for user input to handle some login options, causing no problems in interactive sessions or running via Rscript (user input is handled appropriately).

A few quick follow-up questions:

1. What exactly do you run when you use `Rscript`?
1. What happens when you hit the Knit HTML button in RStudio?
1. Have you tried any of the strategies detailed in the gargle vignette [Non-interactive auth](https://gargle.r-lib.org/articles/non-interactive-auth.html)? For example, I'd recommend trying to set the following option in the `.Rprofile` that is in the workflowr directory: `options(gargle_oauth_email = "<your email address>")`

**Comment by Heroico** [comment]
Thanks for the quick response!

1. The minimal script I tested was like the following:
```
suppressPackageStartupMessages(library(bigrquery))

gwas_metadata <- (function(){
  query <- "SELECT * FROM my_data_set_name.my_table"
  query_exec(query, project = "my_project", use_legacy_sql = FALSE, max_pages = Inf)
})()
```
(I actually copy-pasted all the code contained in the R Markdown into an ordinary R session and it worked)

2. I get a login prompt in RStudio's console

3. I did try some options from that article, but I got errors like:
```
Current working directory: /home/numa/Documents/Projects/gtex_paper/gtex-gwas-analysis
Building 1 file(s):
Building analysis/miscellaneous_statistics_2.Rmd
Build failed. See log files for full details.
```

And error logs look like this:
```
createTcpServer: address already in use
Error : Can't get Google credentials.
Are you running bigrquery in a non-interactive session? Consider:
  * Call `bq_auth()` directly with all necessary specifics.
```
And while I explored the possibility of `bq_auth()`, I reached the conclusion that I would need to store credentials in a file. This means that either I make the credentials file available to whomever runs my workflowr project, or I must provide instructions for them to build them themselves.

I was hoping to use the standard `bigrquery` login mechanism (upon prompting the user, it opens a browser tab to login and then moves on to processing). This way collaborators would only download the workflowr and run it.

**Comment by Heroico** [comment]
There was an update to one of `bigrquery`'s dependencies, and the following option now works on my end:
```
options(gargle_oauth_email = TRUE)
```

**Comment by jdblischak** [comment]
Great! I'm glad that you were able to find a work around. Otherwise, I was thinking your idea of "provide instructions for them to build them themselves" would be the only solution since they need to authenticate with Google somehow if they want to execute your workflowr project.
