### ISSUE TITLE
Provide warning if index.Rmd does not contain wflow_site

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#177]
1. Describe the suggested feature.

Let the user know if they are missing the following line in the YAML header of `index.Rmd`:

```
site: workflowr::wflow_site
```

Thanks to @pcarbo for the idea.

2. Describe why you think this feature is needed.

The workflowr site generator is needed to properly handle the copying of files from the R Markdown directory to the website directory.

An obvious place would be to warn in `wflow_status()`. But it might be better to include the warning in `wflow_build()` as well.

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

```
> packageVersion("workflowr")
[1] ‘1.4.0’
```

**Comment by pcarbo** [comment]
Thanks. I would say giving the warning in `wflow_build` and `wflow_publish` is sufficient.
