### ISSUE TITLE
A function to check minimum required versions of dependencies

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#178]
1. Describe the suggested feature.

A function that will check the versions of the installed dependencies and warn the user if they do not have the minimum required version available. Furthermore, if it is an interactive session, the function could offer to update these packages. I think it makes sense to include this check in `.onAttach()` so that is is executed when the user attaches the package with `library(workflowr)`.

2. Describe why you think this feature is needed.

`install.packages()` only installs missing dependencies. It does not check to see if a package that is already installed meets the minimum version required by the package. Thus if a user has stringr 1.2.0 installed prior to installing workflowr, `wflow_start()` will fail because stringr >=1.3.0 is required.

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.

1.4.0

**Comment by pcarbo** [comment]
It is surprising that `install.packages` allows this to happen. 

Something like this must have already been implemented. Maybe send an email to the `R-pkg-devel` mailing list?

**Comment by jdblischak** [comment]
> It is surprising that install.packages allows this to happen.

I agree it's unfortunate. I hadn't realized this either until I specifically tested it.

> Something like this must have already been implemented. Maybe send an email to the R-pkg-devel mailing list?

I don't think it has. See for example this [SO discussion](https://stackoverflow.com/questions/21010705/update-a-specific-r-package-and-its-dependencies).

**Comment by jdblischak** [comment]
@pcarbo The branch "check-deps" has my proposed solution. The first time that workflowr is attached, it quickly checks for any dependencies that don't meet the minimum required version, and warns the user.

Could you please review this new feature? Below is a demonstration:

```
# remotes::install_version("rstudioapi", "0.1")
> library(workflowr)
This is workflowr version 1.5.0.9000
Run ?workflowr for help getting started
Warning message:
Please update package "rstudioapi": version 0.1 is installed, but 0.6 is required 
```

**Comment by pcarbo** [comment]
@jdblischak Yep, seems to work:

```
> library(workflowr)
This is workflowr version 1.5.0.9000
Run ?workflowr for help getting started
Warning message:
Please update package "git2r": version 0.25.2 is installed, but 0.26.0 is required
```

**Comment by pcarbo** [comment]
And:

```
> install.packages("git2r")
> packageVersion("git2r")
> library(workflowr)
This is workflowr version 1.5.0.9000
Run ?workflowr for help getting started
```
