### ISSUE TITLE
Must save updates before running `wflow_publish()`

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#179]
> Before posting your question, please search the existing issues (both "open" and "closed") to check that a similar question has not already been posted.

I did this search and did not seem to find anything relevant.

Hi John,

This may be a minor thing but I would like to report it just for completeness.

It seems that if I make some updates in a Rmd file `test.Rmd`, do not save these updates, and use `wflow_publish('test.Rmd')`, then the resulting `test.html` will be the same as the previous version. It seems that I must manually save these updates in order to obtain the latest version of HTML file.

In contrast, the "knit button" built in Rstudio does not require this manual save. (That is, I make updates in a Rmd file, and then click the "knit button" to obtain the latest HTML.)

**Comment by jdblischak** [comment]
Your observation is correct. RStudio automatically saves the R Markdown file before building it. The reason `wflow_publish()` doesn't do that is because it's not part of RStudio.

But I could add this feature using the function `documentSave()` from the package [rstudioapi](https://cran.r-project.org/package=rstudioapi). I'll try it out to see how well it works.

**Comment by jdblischak** [comment]
@xiangzhu On the branch "autosave", I added the feature to `wflow_publish()` to automatically save the R Markdown file before publishing it. One caveat is that the R Markdown file has to be the current file selected in the source editor for this to work (which is a similar limitation to the Knit HTML button).

Is it sufficient to auto-save with `wflow_publish()`, or would you prefer that `wflow_build()` also have this behavior?

And could you please test it out for me by installing the version on the GitHub branch? Thanks!

```
remotes::install_github("jdblischak/workflowr@autosave")
```

**Comment by xiangzhu** [comment]
@jdblischak  thanks for adding this potential feature so fast!

> And could you please test it out for me by installing the version on the GitHub branch? 

Sure. I will test this feature soon. Will it be sufficient if I just take screenshots to report the results?

> Is it sufficient to auto-save with wflow_publish(), or would you prefer that wflow_build() also have this behavior?

For me `wflow_publish()` is enough, but if the implementation is simple it would be nice to have autosave in both functions.

On a related note, I rarely use `wflow_build()` myself, and I almost forget this function if you did not mention it above. (I feel whenever I should use `wflow_build()`, I simply click the knit button in Rstudio...)

**Comment by jdblischak** [comment]
> Sure. I will test this feature soon. Will it be sufficient if I just take screenshots to report the results?

@xiangzhu There's no need to include screenshots unless you feel it is necessary to explain something. Try it out and let me know if it behaves as you expected it would.

> For me wflow_publish() is enough, but if the implementation is simple it would be nice to have autosave in both functions.

I pushed another update to the "autosave" branch. Now `wflow_publish()`, `wflow_build()`, and `wflow_status()` will autosave the files open in RStudio.

Furthermore, I made the following changes:

* All files will be saved. Previously it was just the currently selected one (and only it is was explicitly passed to the argument `files`).
* There is a package option, `workflowr.autosave`. If a user didn't like the autosave feature, they can disable it.

> On a related note, I rarely use wflow_build() myself, and I almost forget this function if you did not mention it above. (I feel whenever I should use wflow_build(), I simply click the knit button in Rstudio...)

That is totally fine! They are meant to be interchangeable. One advantage of `wflow_build()` is that it is easier to build multiple files, e.g. with `wflow_build("analysis/*Rmd")`. But if you are usually working on one file at a time, using Knit HTML is perfectly compatible with workflowr.

**Comment by jdblischak** [comment]
@pcarbo Are there any edge cases that I should be considering for this feature? Overall I think it seems safe and desirable to autosave the files.

**Comment by pcarbo** [comment]
@jdblischak It is okay with me. To me the need to save a source code file before running it is obvious, but I can see how people who are only familiar with the RStudio IDE can fail to appreciate that.

**Comment by jdblischak** [comment]
@xiangzhu I did some more testing of this feature. I'm happy with it, and @pcarbo approves as well. Once you test it out and approve, I'll merge it into master.

**Comment by xiangzhu** [comment]
@jdblischak  I just tried this new autosave feature, and it works like a charm!

Many thanks for adding this new feature so fast, and I look forward to a CRAN release that includes this new feature.

Please feel free to close this ticket. 

Below are screenshots of this test in case you need.
![image](https://user-images.githubusercontent.com/5986023/68416037-85a9eb00-0148-11ea-8f3d-93101cea4640.png)
![image](https://user-images.githubusercontent.com/5986023/68416554-8c852d80-0149-11ea-8097-c8bb2e2d4ad4.png)
![image](https://user-images.githubusercontent.com/5986023/68416613-aaeb2900-0149-11ea-8f01-83e0c74fa4a3.png)
![image](https://user-images.githubusercontent.com/5986023/68416657-c7876100-0149-11ea-8e91-d0ea88e91ce4.png)

**Comment by jdblischak** [comment]
@xiangzhu Thanks! The autosave feature is now on the master branch.
