### ISSUE TITLE
Add license for materials other than software

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#18]
You will need a separate license (e.g., [CC-BY](https://creativecommons.org/licenses/by/4.0/legalcode)) for all text and materials that are not software/code. See [here](https://github.com/swcarpentry/r-novice-inflammation/blob/gh-pages/LICENSE.md) for an example.

**Comment by jdblischak** [comment]
Are you referring to the workflowr R package or to a workflowr-based project?

For the former, I am not familiar with any R package that puts a separate license on its vignettes. Is it common for a software project to specify a separate license for its documentation? As an example, [bedtools](https://github.com/arq5x/bedtools2) has extensive documentation, but no additional license. I see documentation (whether a fancy vignette or simple function comments) to be part of the code base.

For the latter, I encourage users to include a separate license for both their code and content. In contrast to documentation, the text of a workflowr project is a main product (i.e. the scientific results and interpretation). Thus in this context I think it makes sense to have separate licenses (similar to SWC having a separate license for their instructional content).

[LICENSE](https://github.com/jdblischak/workflowr/blob/master/inst/infrastructure/LICENSE)
[license.Rmd](https://github.com/jdblischak/workflowr/blob/bf10fcdd40dd674fca479a3421521f3cae360b0c/inst/infrastructure/analysis/license.Rmd)

**Comment by pcarbo** [comment]
Fair points. Up to you. Here are some additional thoughts:

+ I wouldn't necessarily use common behaviour as a guide; most researchers still don't include any license.

+ It might be good to include both MIT + CC-BY to "nudge" licensing behaviour in the projects; further, I could see the CC-BY license being useful later on as more content (e.g., data) is added to the vignettes. Therefore, provides a good safeguard.

+ I read that GPL and CC0 are compatible licenses (not sure if you can use GPL). CC0 is used by default by Data Dryad.

+ Finally, what about automatically providing a default license (again, [nudging is good](https://en.wikipedia.org/wiki/Default_effect_(psychology))!).

**Comment by jdblischak** [comment]
I'm closing this in favor of #30. I think licenses should be opt-in only. I don't think users would like having their content automatically licensed as open just because they started using workflowr.
