### ISSUE TITLE
Problem with filepaths that include a space (i.e. Google Drive)

### ISSUE THREAD

**Issue by wolfemd** [workflowr/workflowr#180]
Just following the Getting Started vignette, but wanted to create a project in my google drive folder, which unforutnately has a space in the filepath.

`wflow_start("~/Google Drive/new_workflow/")`
also tried `wflow_start("~/Google\ Drive/new_workflow/")`
then
`wflow_status()
`

> fatal: cannot change to '/Users/username/Google': No such file or directory
> Status of 3 Rmd files

> Totals:
> 3 Unpublished

> The following Rmd files require attention:

> Unp analysis/about.Rmd
> Unp analysis/index.Rmd
> Unp analysis/license.Rmd
> 
> Key: Unp = Unpublished
> 
> The current Git status is: working directory clean

> To publish your changes as part of your website, use `wflow_publish()`.
> To commit your changes without publishing them yet, use
> `wflow_git_commit()`.
> Warning message:
> In system(cmd, intern = TRUE) :
>   running command '/usr/bin/git -C /Users/username/Google Drive/new_workflow ls-files' had status 128

After that, if I do: 

`wflow_git_commit()` or `wflow_publish()` I get the same error. 

`sessionInfo()`

> R version 3.6.1 (2019-07-05)
> Platform: x86_64-apple-darwin15.6.0 (64-bit)
> Running under: macOS Mojave 10.14.6
> 
> Matrix products: default
> BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
> LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] workflowr_1.5.0
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.2      ps_1.3.0        crayon_1.3.4    rprojroot_1.3-2
>  [5] digest_0.6.21   later_1.0.0     R6_2.4.0        backports_1.1.5
>  [9] git2r_0.26.1    magrittr_1.5    evaluate_0.14   stringi_1.4.3  
> [13] rlang_0.4.0     rstudioapi_0.10 fs_1.3.1        promises_1.1.0 
> [17] callr_3.3.2     rmarkdown_1.16  tools_3.6.1     stringr_1.4.0  
> [21] glue_1.3.1      processx_3.4.1  yaml_2.2.0      httpuv_1.5.2   
> [25] xfun_0.10       compiler_3.6.1  htmltools_0.4.0 knitr_1.25

**Comment by jdblischak** [comment]
@wolfemd Thank you very much for filing this bug report. I was able to reproduce the problem.

**Explanation:** In workflowr 1.5.0, I added the ability for workflowr to use the native version of Git installed on the user's machine (if installed) to obtain the list of files committed in the Git repository. The motivation for this was increased speed compared to using the git2r package. Unfortunately, the call to Git breaks if there is a space in the path.

**Short-term solution:** To immediately fix the problem, you can disable this new feature. Add the following line to the file `.Rprofile` in your workflowr project:

```
options(workflowr.sysgit = "")
```

This will prevent workflowr from trying to use the system Git executable. I confirmed this worked on my Windows machine. Run `?workflowr` for more information on workflowr package options.

**Long-term solution:** I think I should be able to fix this by quoting the filepath passed to Git. I'll follow up here once I've fixed it.

**Comment by jdblischak** [comment]
@wolfemd I have fixed the issue in the development version on GitHub (as well as added some extra error handling and tests to catch future issues earlier).

You can install the development version using the line below:

```
remotes::install_github("jdblischak/workflowr")
```

**Comment by wolfemd** [comment]
Problem solved! Thanks so much for the super quick fix!
