### ISSUE TITLE
Unknown option with git interaction

### ISSUE THREAD

**Issue by jennysjaarda** [workflowr/workflowr#182]
Hello, 
First of all - thanks for the great package! I have a question about git interaction. When I use a function which interacts with git I'm getting the error/warning: 
`
wflow_use_github("user")
Unknown option: -C
`
...
`
Warning message:
In system(cmd, intern = TRUE) :
  running command '/usr/bin/git -C /my/path/new_project ls-files' had status 129
`

Any ideas?

**Comment by jdblischak** [comment]
@jennysjaarda Thanks for filing this bug report. Is your workflowr project in `/my/path/new_project` or was that just an example? If it was an example, does your file path include any spaces? Also, what operating system are you using?

For an immediate fix, you can disable the use of the system Git executable by adding the following line to the file `.Rprofile` in your workflowr project:

```
options(workflowr.sysgit = "")
```

This feature was added in workflowr 1.5.0. You can see more details about the workflowr package options by running [`?workflowr`](https://jdblischak.github.io/workflowr/reference/workflowr.html).

**Comment by jennysjaarda** [comment]
Hello, 
Thanks for the quick response. It was just an example, but there are no spaces. As for operating system, I am using linux and connecting to a remote HPC cluster. Do you see any issues with that? I have set `options("workflowr.view" = FALSE)` for this reason. Typically I interact with my code both locally (on my personal computer) and remotely (on the cluster) and have cloned my repositories on both so I can have my scripts in both places, but I was wondering if you see any limitation with this type of workflow and the workflowr package?

**Comment by jdblischak** [comment]
> Typically I interact with my code both locally (on my personal computer) and remotely (on the cluster) and have cloned my repositories on both so I can have my scripts in both places, but I was wondering if you see any limitation with this type of workflow and the workflowr package?

That is totally fine. I do the same myself. As long as you keep the two repositories in sync (using `git pull` or `wflow_git_pull()`), that should work well.

Some more questions:

1. Did setting `options(workflowr.sysgit = "")` remove the error message?
1. Could you try using the development version of workflowr by installing the master branch? You can do so with `remotes::install_github("jdblischak/workflowr")`. I've already pushed a patch to this code to fix Issue #180, so maybe that will also fix your issue.
1. Do you get the error on both your local machine and your HPC?

**Comment by jennysjaarda** [comment]
Hi John,

Yes your suggestion worked! Thanks a lot. One other quick question, do you
have any suggestions for viewing the compiled html from a remote server so
I don't have to constantly push and pull to my local machine?

Jenny

**Comment by jdblischak** [comment]
> suggestions for viewing the compiled html from a remote server

@jennysjaarda Here are various strategies you could investigate:

1. Mount your remote directory on your local machine, e.g. with [Samba](https://en.wikipedia.org/wiki/Samba_(software)) or [SSHFS](https://en.wikipedia.org/wiki/SSHFS)
1. Use a remote desktop server, e.g. [ThinLinc](https://www.cendio.com/thinlinc/what-is-thinlinc)
1. Use a GUI interface to transfer files. [WinSCP](https://en.wikipedia.org/wiki/WinSCP) works well for Windows. I've used [Filezilla](https://en.wikipedia.org/wiki/FileZilla) on Linux for transferring files from an FTP server, but I don't know of a GUI option for SCP transfer on Linux (you could always use `scp` directly)
1. Ask your systems admins to setup an RStudio Server instance
1. Check if you have a public directory on your HPC (on my HPC, any file I put in `public_html/` is publicly accessible online)

I highly recommend you setup a meeting with one of your HPC systems administrators. You certainly aren't the first user to need convenient access to their remote files. They can advise you on which software will work best on your HPC cluster.

**Comment by jdblischak** [comment]
> Yes your suggestion worked!

Which one? Did you try installing the development version? I'd really like to know if the problem has been fixed, so that more users won't have the same issue you did. Thanks!

**Comment by jennysjaarda** [comment]
Thanks a lot for the suggestions. Sorry for not being clear, this is what
worked for me `workflowr.sysgit = ""`

**Comment by jdblischak** [comment]
> Sorry for not being clear, this is what
worked for me `workflowr.sysgit = ""`

OK. I'm glad that worked. Make sure to add/commit `.Rprofile` if you want this option to apply to all clones of the project. You can do this with `wflow_git_commit(".Rprofile", "Don't use the system Git")`

But if you have a second, I'd appreciate if you could test the development version. These are the steps:

1. Install the development version with `remotes::install_github("jdblischak/workflowr")`
1. Remove the option `workflowr.sysgit` from `.Rprofile`
1. Restart the R session for the option to take effect (In RStudio: Ctrl+Shift+F10). You can confirm this by running `getOption("workflowr.sysgit")`. It should return the path to your Git executable.
1. Run `wflow_status()`. Did it work? If there is an error message, please copy-paste it here.

After running the test, you can restore your setup by:

1. Re-install the latest release with `install.packages("workflowr")`
1. Revert the change to `.Rprofile` by running this line in the terminal: `git checkout -- .Rprofile` (alternatively, you can manually add back the workflowr.sysgit option)

**Comment by jennysjaarda** [comment]
I just followed your steps and I didn't receive an error message so it
seems to be working!

By the way, I just setup SSHFS on my mac and it works great - thanks for
the tip. It's much better than filezilla, scp, or other solutions I have
used in the past.

Thanks again for the help!

**Comment by jdblischak** [comment]
> I just followed your steps and I didn't receive an error message so it
seems to be working!

Awesome! I'm glad the previous fix also fixes your bug.

> By the way, I just setup SSHFS on my mac and it works great - thanks for
the tip. It's much better than filezilla, scp, or other solutions I have
used in the past.
>
> Thanks again for the help!

You are welcome! Happy computing! :smile:

**Comment by jennysjaarda** [comment]
Hi John,
I just wanted to share one other small (potential) issue I came across when
initiating a new project. After creating the bare repository on git, using
the command `wflow_git_push()` gave the following error:

The error message from git2r::push() was:

Error in 'git2r_push': there is no TLS stream available

These sorts of errors are difficult to troubleshoot. If you have Git
installed on your machine, the easiest solution is to instead run `git
push` in the Terminal. This is equivalent to wflow_git_push().

I tried the instructions as provided (i.e. running `git push` in the
terminal), but it also did not work (I think because of it is the first
commit). Oddly, this didn't happen to me before, so perhaps it is with the
development version you provided yesterday? I was able to solve the problem
by running `git push --set-upstream origin master` from the Terminal
(within the project directory).

If you have any insights/fixes let me know, otherwise just sharing my
solution in case others have the proble.

Jenny

**Comment by jdblischak** [comment]
> Error in 'git2r_push': there is no TLS stream available

That's a new one for me. I added my ideas to your issue https://github.com/ropensci/git2r/issues/410

> I tried the instructions as provided (i.e. running `git push` in the
terminal), but it also did not work (I think because of it is the first
commit).

You are correct. Since it is the first time you pushed, Git is unable to guess where to push when you only type `git push`. I can make that error message more informative.

> . Oddly, this didn't happen to me before, so perhaps it is with the
development version you provided yesterday?

The development version hasn't made any changes to `wflow_git_push()` or related functionality. My guess is that you might have installed a new version of git2r, that then wasn't compiled properly.

**Comment by jdblischak** [comment]
@jennysjaarda I updated the error message for `wflow_git_push()` and `wflow_git_pull()` to report the exact Git command to run in the terminal. Using your previous error as an example, the message returned would now appear like below. Note that `-u` is equivalant to `--set-upstream`.

```
> wflow_git_push()
Error: Push failed for unknown reason.

The error message from git2r::push() was:

Error in 'git2r_push': there is no TLS stream available

These sorts of errors are difficult to troubleshoot. You can search for
similar errors on the git2r GitHub repository for advice on how to fix
it.

Alternatively, if you have Git installed on your machine, the easiest
solution is to instead run `git push` in the terminal. This is
equivalent to wflow_git_push(). Specifically, copy-paste the following
in the terminal:

git push -u origin master
```

Thanks for reporting your issues to help improve workflowr! I credited you in the [News](https://jdblischak.github.io/workflowr/news/index.html) bullet for this feature.
