### ISSUE TITLE
How to effectively use Git LFS within workflowr?

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#183]
> Before posting your question, please search the existing issues (both "open" and "closed") to check that a similar question has not already been posted.

I did this search and did not seem to find anything relevant.

Hi John @jdblischak 

I hope you had a great holiday!

Recently I have generated some large html files within a workflowr repo and I cannot push them to GitHub regularly due to file size limit (100.00 MB).

Somehow I find the following workaround based on Git LFS, but I am not sure this is the most effective way. I look forward to your thoughts/suggestions on this matter.

This is what I did in Rstudio.
```r
wflow_publish("big.Rmd")
``` 

Then, I run the following in Terminal. (I am sure some lines are redundant?)
```zsh
git lfs install
git lfs track "docs/big.html"
git add .gitattributes
git rm --cached "docs/big.html"
git commit -m "Convert last commit to LFS"
git lfs migrate import --include="docs/big.html"
git push
```

Now that `big.html` is pushed to workflowr repo, but it cannot be viewed like others ...

I wonder if you know about a way to display this large html?

**Comment by pcarbo** [comment]
@xiangzhu Do you know why your HTML file so large? It is not recommended to create such a large HTML file since it mightt be very difficult (if not impossible) to view conventionally in a Web browser.

**Comment by xiangzhu** [comment]
@pcarbo  yes, these large files are often due to i) large plots (scatter plots with millions of points) and/or ii) large tables (with millions of rows)

I agree these large display items cause inconvenience for web browsers.

**Comment by pcarbo** [comment]
Tables with millions of rows!!! These should not be included in your HTML!

As for plots, are these being saved to separate (e.g., jpg) files? I *believe* this is the default.

**Comment by xiangzhu** [comment]
@pcarbo  What about the interactive plots from `plotly`?

In general I am only curious whether Git LFS features could be effectively used within current workflowr ...

**Comment by pcarbo** [comment]
I don't think Git LFS is intended to be used for website files. In all cases, website files such as HTML, JavaScript as figures should never be large; this is a critical aspect of a well-functioning website.

**Comment by jdblischak** [comment]
> In general I am only curious whether Git LFS features could be effectively used within current workflowr 

@xiangzhu I think this depends on what you are trying to do. Since Git LFS works work Git, it by default will also work with workflowr. However, you are trying to use Git LFS with GitHub Pages. I don't believe this will work. The files that are versioned with Git LFS are stored on a separate GitHub server. Thus they are unlikely to be available to the server used by GitHub Pages to serve the static website. But as @pcarbo mentioned, even if it could, the file would be difficult to view in a web browser. What happens when you view it locally?

**Comment by xiangzhu** [comment]
Thanks!

I think the key issue (after some research on my end) is indeed the following:

> However, you are trying to use Git LFS with GitHub Pages. I don't believe this will work.

I think it's better to ask this question when GitHub Pages supports Git LFS.

However, I find Git LFS useful to share (moderately) large data files in workflowr `data/` and `output/` folders: that is, this allows me to put raw files and summarized results (website) in the same repo. Not sure any other workflowr users have similar feeling ...

I don't have any further question on this topic. Please feel free to close this ticket. Thanks!

**Comment by pcarbo** [comment]
> However, I find Git LFS useful to share (moderately) large data files in workflowr data/ and output/ folders.

Yes, that is exactly what Git LFS is intended for!

**Comment by jdblischak** [comment]
> this allows me to put raw files and summarized results (website) in the same repo.

Yes, I agree 100%. I have also used Git LFS with workflowr to version both the data and the results.

This question has come up enough times that it is probably worth adding an FAQ entry about Git LFS and other strategies for large data files.

> I think it's better to ask this question when GitHub Pages supports Git LFS.

As @pcarbo noted above, even if this were possible, it would not be ideal. For creating interactive widgets that require a large amount of data, it'd probably be a better idea to create a Shiny app, deploy it to shinyapps.io, and then embed it inside the web page. This overcomes the big disadvantage of a static site, which is that all the potential data has to be written directly to the HTML file. Of course the downside of using a Shiny app is that it is one more thing to try to keep in sync as the project evolves.

**Comment by xiangzhu** [comment]
@pcarbo @jdblischak  thanks for sharing these helpful thoughts!

**Comment by jdblischak** [comment]
@xiangzhu I added a new vignette that discusses strategies for versioning large data files in a workflowr project: https://jdblischak.github.io/workflowr/articles/wflow-10-data.html
