### ISSUE TITLE
Error after deleting subdirectory

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#185]
If my current working directory is deleted within a workflowr project, I get this error:

```
> wflow_status()
Error in path[!is_abs] <- path_norm(path(start, path[!is_abs])) :
  replacement has length zero
```

We just need to check for this possibility and report a more interpretable error.

**Comment by jdblischak** [comment]
@pcarbo Thanks for the bug report. I was able to reproduce the error message when the deleted current working directory was either the root of the workflowr project or a subdirectory. I also produced a new error if the deleted current working directory was outside of the project. Lastly, note that this behavior can be unpredictable in RStudio because it appears to reset the working directory once it is detected that it has been deleted.

``` r

# Delete the entire workflowr project
wflow_rootdir_deleted_error <- function() {
  cwd <- getwd()
  on.exit(setwd(cwd))
  path <- tempfile()
  workflowr::wflow_start(path, change_wd = TRUE)
  workflowr::wflow_status()
  unlink(path, recursive = TRUE, force = TRUE)
  workflowr::wflow_status()
}
wflow_rootdir_deleted_error()
#> Error in path[!is_abs] <- path_norm(path(start, path[!is_abs])): replacement has length zero

# Delete a subdirectory of the project
wflow_subdir_deleted_error <- function() {
  cwd <- getwd()
  on.exit(setwd(cwd))
  path <- tempfile()
  workflowr::wflow_start(path, change_wd = FALSE)
  subdir <- file.path(path, "sub")
  dir.create(subdir)
  setwd(subdir)
  workflowr::wflow_status()
  unlink(subdir, recursive = TRUE, force = TRUE)
  workflowr::wflow_status()
}
wflow_subdir_deleted_error()
#> Error in path[!is_abs] <- path_norm(path(start, path[!is_abs])): replacement has length zero

# Delete a directory outside of the project
wflow_extdir_deleted_error <- function() {
  cwd <- getwd()
  on.exit(setwd(cwd))
  path <- tempfile()
  workflowr::wflow_start(path, change_wd = FALSE)
  extdir <- tempfile()
  dir.create(extdir)
  setwd(extdir)
  workflowr::wflow_status(project = path)
  unlink(extdir, recursive = TRUE, force = TRUE)
  workflowr::wflow_status(project = path)
}
wflow_extdir_deleted_error()
#> Error in FUN(X[[i]], ...): start must be a character vector of length 1
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jdblischak** [comment]
Hmmm...this is unexpected. All the workflowr functions check that the directory pointed to by the argument `project` exists. By default this is `"."`. However both `dir.exists()` and `fs::dir_exists()` return `TRUE` when the current working directory doesn't exist.

``` r

cwd <- getwd()
path <- tempfile()
dir.create(path)
setwd(path)
unlink(path, recursive = TRUE, force = TRUE)
dir.exists(path)
#> [1] FALSE
dir.exists(".")
#> [1] TRUE
getwd()
#> NULL
setwd(cwd)

cwd <- fs::path_wd()
path <- fs::file_temp()
fs::dir_create(path)
setwd(path)
fs::dir_delete(path)
fs::dir_exists(path)
#> /tmp/RtmpJO9A8o/file3a52213b4a3e 
#>                            FALSE
fs::dir_exists(".")
#>    . 
#> TRUE
fs::path_wd()
#> character(0)
setwd(cwd)
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by jdblischak** [comment]
I opened an Issue on the fs repository to discuss this edge case: https://github.com/r-lib/fs/issues/240

The current check already exists in all the user facing functions. I would have expected it to have caught the case where the current working directory has been deleted.

https://github.com/jdblischak/workflowr/blob/a6cfa19c176875ba98dd65a6088bcd1389e9b8da/R/wflow_status.R#L142-L143

**Comment by pcarbo** [comment]
If the current directory is deleted, `getwd()` returns `NULL`. Is that helpful?

**Comment by jdblischak** [comment]
Yes, `getwd()` returns `NULL` and `fs::path_wd()` returns `character(0)`. Since I am trying to consistently use fs, I went with `length(fs::path_wd()) == 0`.

**Comment by jdblischak** [comment]
Note that it isn't possible to delete the current working directory on Windows, so this bug only applies to Linux/macOS.

**Comment by pcarbo** [comment]
@jdblischak The `no-wd-error` seems to work:

```
> getwd()
NULL
> wflow_status()
Error: The current working directory doesn't exist. Use setwd() to change to existing directory.
```
