### ISSUE TITLE
Update documentation of GitLab access controls

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#187]
As I was investigating GitLab for Issue #186, I noticed a few things about access control that we should document:

1. When a GitLab repository is created from a `git push`, e.g. `wflow_git_push()`, it is private by default. We should note this in the GitLab vignette and encourage users to [make their project public](https://gitlab.com/help/public_access/public_access) for the sake of open science.

1. GitLab.com provides [access control](https://gitlab.com/help/user/project/pages/pages_access_control.md) not only for the repository but also for the static site hosted on GitLab Pages. Thus this is an option for users that want to be able to have a private invite-only site. I'll note this in the FAQ, Deployment, and GitLab vignettes.

**Comment by jdblischak** [comment]
@xiangzhu I know you are interested in private hosting of workflowr sites. You should checkout GitLab (see links above). It provides granular control in which you can grant specific users access to the website or source repository.

**Comment by xiangzhu** [comment]
@jdblischak  thanks for sharing this. I will look into this option soon.

Is it straightforward to use workflowr in GitLab? I only have experience with GitHub.

**Comment by pcarbo** [comment]
@xiangzhu GitLab should is very user-friendly, like GitHub, but of course there are a few differences that will take some getting used to. 

An added benefit is that we would very much like to have workflowr properly tested on GitLab, so we would welcome any feedback, and we would be happy to help if you get stuck.

**Comment by jdblischak** [comment]
> Is it straightforward to use workflowr in GitLab? I only have experience with GitHub.

@xiangzhu All the workflowr features are fully supported by GitLab.com. You can setup the project with `wflow_use_gitlab()`. Also, the links to past versions of the HTML files will work with GitLab.com (they wouldn't work though with self-hosted GitLab, e.g. https://git.rcc.uchicago.edu).

In fact, you could argue that GitLab is easier to use with workflowr. The repository is created on GitLab automatically the first time you push, so there is no need for you or workflowr to create it beforehand. And the website is automatically deployed via the config file `.gitlab-ci.yml` (in contrast, this step has to be performed manually with GitHub).

See the vignette [Hosting workflowr websites using GitLab](https://jdblischak.github.io/workflowr/articles/wflow-06-gitlab.html) for more details.
