### ISSUE TITLE
Check for class with inherits()

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#189]
Instead of `class(x) == "classname"`, it is better practice to instead check with `inherits(x, "classname")`. This avoids any potential future errors if additional classes are added to an object, such as described below:

https://twitter.com/groundwalkergmb/status/1199039233563873280
https://twitter.com/edgarmerkle/status/1199324826059595778
https://t.co/AC2hOkwqNg?amp=1

**Comment by pcarbo** [comment]
Yes!
