### ISSUE TITLE
install_github should install most recent stable release

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#19]
It should be something like this:

```R
devtools::install_github("jdblischak/workflowr",
                        ref = "v0.3.0",
                        build_vignettes = TRUE)
```

**Comment by jdblischak** [comment]
I don't think this is necessary. My development plan is for the master branch to only ever contain the latest stable version. A user should be able to run `devtools::install_github("jdblischak/workflowr", build_vignettes = TRUE)` to install (or upgrade to) the latest stable version.

https://github.com/jdblischak/workflowr/blob/master/CONTRIBUTING.md

**Comment by pcarbo** [comment]
Sounds good. Feel free to close this.

**Comment by jdblischak** [comment]
I updated the text in both the README and the "Getting Started" vignette to clarify this. Thanks!

https://github.com/jdblischak/workflowr/commit/042b2cb8629116363c01e802b1a3a111fe3c45bd
