### ISSUE TITLE
Using workflowr with a Keybase encrypted git repo

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#191]
Does anyone have any experience using workflowr with a [Keybase encrypted git repo](https://keybase.io/blog/encrypted-git-for-everyone) or have any views on whether that's a reasonable idea?

My typical use case has a small number of distributed analysts and an end user working on a confidential analysis project that might run for many months. The data and the results must be kept private and will never be made public. Results are shared with the end user over the course of the project by sharing the _local_ static website generated by workflowr (that's just a secure file transfer problem). There's no need for the results website to be associated with the remote git repo, which is only used for synchronising the analysts.

I don't need or want a central workflowr site because it's a possible attack surface. So I'd prefer not to use any of the alternate deployment methods in the [vignette](https://jdblischak.github.io/workflowr/articles/wflow-08-deploy.html). I can do what I want deployment-wise just by distributing a copy of the local static website. I still need the remote git repo to synchronise the analysts. This would obviously need to be a private repo. However, I don't want to get into self-hosting the remote git repo because I don't have the security resources that a large service provider has. On the other hand, if I use a private repo on GitHub or GitLab, the repo code is stored in plaintext on the hosting system, so is vulnerable to the host being compromised.

Using a [Keybase encrypted git repo](https://keybase.io/blog/encrypted-git-for-everyone) should provide the analysts end-to-end encrypted access to the remote repo and the remote repo would be encrypted , so it's not vulnerable to the host being compromised.

I would appreciate any views on whether that's a reasonable or crazy proposal and any suggestions on how easy that would be to implement.

Thanks

**Comment by jdblischak** [comment]
Hi @rgayler! Thanks for raising this interesting use case.

From the workflowr perspective, this should be fine. The only limitation is that you won't be able to use `wflow_git_push()` and `wflow_git_pull()`. They require the remote repository URL to begin with `https` or `git@`. As long as you run `git push` and `git pull` in a shell (or use a Git GUI such as the one included with RStudio), it should work smoothly.

For example, the steps to create a workflowr site (named "example") on Keybase would look something like the following:

1. Create an encrypted Git repository on Keybase with the name "example"
1. Clone the repository to your local machine
    ```
    git clone keybase://private/rgayler/example.git
    cd example/
    ```
1. Start a workflowr project (assuming you are in the "example" directory)
    ```
    library(workflowr)
    wflow_start(".", existing = TRUE)
    ```
1. Publish the project
    ```
    wflow_publish("analysis/*Rmd")
    ```
1. Push to Keybase
    ```
    git push origin master
    ```

From a security perspective, this definitely appears to be more secure than an unencrypted private repository hosted on a third party website. However, I am not a security expert, so you'll have to make the call if an encrypted Git repository hosted on Keybase provides sufficient protection.

**Comment by rgayler** [comment]
Thanks for that @jdblischak , especially for the code examples.
I am playing around with an example workflowr project and keybase repo, following you code and all is going well so far. 

The only thing I have done differently is to associate the keybase git repo with a keybase subteam rather than create it as a private repo. This means that the repo can continue to exist even if I am no longer associated with it. I will play with this idea a bit and if I learn anything useful I will report back here and possibly update the deployment vignette.

I will ask around elsewhere to see if anyone with security expertise has any views on this use of keybase and report back here if I learn anything.

**Comment by jdblischak** [comment]
> I will play with this idea a bit and if I learn anything useful I will report back here and possibly update the deployment vignette.
> I will ask around elsewhere to see if anyone with security expertise has any views on this use of keybase and report back here if I learn anything.

I'm glad to hear it's going well. If you end up finding this solution useful, I would super appreciate a Pull Request to the deployment vignette so that other users can consider this deployment strategy.

I'm closing this Issue since there is nothing immediate that needs to be done. Please feel to reopen it if you encounter any issues. Also, please reference it if you decide to submit a PR.
