### ISSUE TITLE
wflow_start automatically moves working directory to project directory

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#20]
e.g., have an additional input argument `setwd` to `wflow_start` set to `TRUE` by default. Then you could skip one of the steps in the setup.

**Comment by jdblischak** [comment]
I like this idea. However, I'm not sure I'd want it to be the default. While it would be convenient for those using R directly from the R console, I want to encourage RStudio users to use the Project system. The `rstudioapi` does not have a function for opening a project, so they would need to do this manually anyways.

**Comment by pcarbo** [comment]
Maybe have `wflow_start` output a message explaining what to do next? (Then forget the `setwd` option.) You can give different instructions depending on the return value of `Sys.getenv("RSTUDIO")`, I think.

**Comment by stephens999** [comment]
i want to bump this - i just started a new project 
using wflow_start and then used wflow_open to get a new rmd, not realizing
that it actually opened in a different project...

**Comment by jdblischak** [comment]
OK. And since that is two votes now, I'll make this the default behavior.
