### ISSUE TITLE
How to create a journal paper to PDF that is not a workflowr page? #question

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#209]
I have set up a workflowr project to do some computational research. I intend to use the workflowr pages to develop the computational work and keep notes about it.

Eventually, I will want to write a paper in some journal's format and render to PDF. I hope to use one of the templates from {[rticle](https://CRAN.R-project.org/package=rticles)}. I would like to keep all the files relating to that paper in the workflowr project directory. As I understand it that paper can't be used as a workflowr page and will be a free-standing *.Rmd (and *.pdf) file somewhere in the project directory structure.

I want to use the workflowr analysis files to create data objects and figures that will be referenced from the paper. So, most of the computational work will occur in the analysis notebooks and the paper will only do whatever computation is necessary for presentation of the results. Obviously, I will need to make sure the workflowr-controlled analyses are up to date before knitting the paper.

Q1: Is there a better way of organising all that to the same effect?
Q2: Is there some recommended (or arguably reasonable) workflow for doing this (workflowr-tracked-computations + separate paper-presenting-results)?
Q3: Are there any publicly viewable examples of using workflowr for something like this?

Thanks

**Comment by jdblischak** [comment]
@rgayler Thanks for the great questions!

> Q1: Is there a better way of organising all that to the same effect?

I think your proposal is reasonable. For example, you could have a subdirectory named `paper/` that contains a file like `submission.Rmd`. It could load the data files in `data/` and/or `output/` to dynamically generate the results (e.g. ``This study included `r nrow(subjects)` subjects.``). For plots, you could either recreate them from the latest data, or you could insert the already-created workflowr figure files in `docs/figure/`.

Another workflow would be for the paper to be a workflowr page included in the workflowr website. Then when you want to create a PDF for journal submission, you could instead use one of the rticles output formats, e.g.

```
rmarkdown::render("analysis/submission.Rmd", rticles::jss_article())
```

This is similar to the strategy outlined in the FAQ entry [Can I create a single HTML or PDF file of one of my workflowr R Markdown files?](https://jdblischak.github.io/workflowr/articles/wflow-05-faq.html#can-i-create-a-single-html-or-pdf-file-of-one-of-my-workflowr-r-markdown-files). The main downside of this approach is that you couldn't use any LaTeX-specific formatting in the Rmd. If you suspect you'll need to make some LaTeX-specific formatting tweaks, you'd be better off having a separate document.

> Q2: Is there some recommended (or arguably reasonable) workflow for doing this (workflowr-tracked-computations + separate paper-presenting-results)?

See my response above.

> Q3: Are there any publicly viewable examples of using workflowr for something like this?

Off the top of my head, the best example I can think of is my [singleCellSeq](https://github.com/jdblischak/singleCellSeq) project. This was the precursor/inspiration for developing the workflowr package, so some things will look different. But the main point is that it has a `paper/` subdirectory, and the Rmd files it contains reference the data files to dynamically fill in the details, e.g. this [line](https://github.com/jdblischak/singleCellSeq/blob/4c917b1e1087d292a4cddfb7a6a4548f1ca16431/paper/methods.Rmd#L105).

Please let me know if you have any questions, and it'd be great if you could follow up here with a description of the workflow you decided on to write the paper.

**Comment by rgayler** [comment]
@jdblischak Thanks for the great answers ;-)

Given the tendency of journals to have their own idiosyncratic LaTeX-specific formatting I think that pretty much mandates not creating the paper as a `{workflowr}` analysis notebook.

(In a previous couple of day-job projects I used the `{workflowr}` analysis notebooks (~100 of them) to capture the stream of consciousness around the analytics, and embedded a `{bookdown}` site in `docs/` to write the more structured high-level documenttion,)

Thanks for the link to your early project. I will pillage that for project structure ideas.

I have set up the bones of my new project at https://github.com/rgayler/VSA_op_properties and the GitHub pages website is at https://rgayler.github.io/VSA_op_properties/

The output paper files are in `paper\`, which was set up from an `{rticle}` template. I have symlinked `paper/paper.pdf` to `docs/paper.pdf` so that I can link to the output paper from the `{workflowr}` generated website (locally and on GitHub pages).

So far the project is pretty content- and experience-free, so I can't yet comment on how it worked in practice.

**Comment by jdblischak** [comment]
> Given the tendency of journals to have their own idiosyncratic LaTeX-specific formatting I think that pretty much mandates not creating the paper as a {workflowr} analysis notebook.

I agree. I usually end up regretting it if I try to target more than one output format.

> I have set up the bones of my new project at rgayler/VSA_op_properties and the GitHub pages website is at rgayler.github.io/VSA_op_properties

Thanks for sharing! It's really informative (and inspiring) to see how users organize workflowr projects.

> The output paper files are in paper\, which was set up from an {rticle} template. I have symlinked paper/paper.pdf to docs/paper.pdf so that I can link to the output paper from the {workflowr} generated website (locally and on GitHub pages).

This is a clever use of symlinks! To clarify for other readers, the actual PDF is in `docs/` (to be viewable in the website), and the symlink is in `paper/` (to facilitate viewing the results when working locally).

@rgayler Since you have a plan to proceed, I'm going to close this Issue. But please do feel free to follow up in this thread. I look forward to hearing about your experience!
