### ISSUE TITLE
How to do cross-references in workflowr documents?

### ISSUE THREAD

**Issue by rgayler** [workflowr/workflowr#210]
Is it possible to do cross-references to sections/text/figures/tables/equations within and between `{workflowr}` documents?

Searching online it looks like I can only get those cross-references if I use `{bookdown}`, which I assume is not compatible with `{workflowr}`.

In a fit of reckless optimism I edited the YAML header of a test document to include:
```
output: 
  workflowr::wflow_html
  bookdown::html_document2
```
To my surprise it rendered, but it didn't enable the `{bookdown}` cross-reference capabilities. I only tried rendering the file and didn't test what else might have been broken.

If I just use `{workflowr}` via
```
output: workflowr::wflow_html
```
the within-file section header hyperlink syntax (e.g. `[see this section](#my-header)` ) works, but the `\@ref(my-header)` style of cross-references don't work.

**Comment by jdblischak** [comment]
@rgayler Great question. I'll split my answer in two parts: 1) cross-referencing sections, and 2) cross-referencing figures/tables/equations.

## Cross-referencing sections

You can cross reference sections both within and between documents. This is possible thanks to pandoc (which automatically assigns an `id` attribute to section headers) and HTML. Workflowr itself doesn't do anything to make this possible.

For example, let's say you have an H2 section like below in your Rmd file:

```
## An important section
```

When pandoc (called by the rmarkdown package), converts this to HTML, it will look like the following:

```
<div id="an-important-section" class="section level2">
<h2>An important section</h2>
<!-- section content would go here -->
</div>
```

The key is that the `div` element is automatically assigned the `id` attribute `an-important-section`. Thus to cross-reference this section within the same Rmd file, you could write:

```
As noted above in [the very important section](#an-important-section), ...
```

And to cross-reference the section from a different file, include the name of the HTML file:

```
As noted in [the very important section](filename.html#an-important-section), ...
```

Please let me know if you have any trouble getting the section cross-references to work.

## Cross-referencing figures/tables/equations

By default, you can **not** cross-reference figures/tables/equations using only `workflowr::wflow_html`. However, you can enable cross-referencing figures/tables/equations within a file. To my knowledge, bookdown is the only Rmd-based package that supports cross-referencing of figures/tables/equations between files.

To enable your workflowr website to cross-reference figures/tables/equations within files, update the output format in `analysis/_site.yml` to use the output format `bookdown::html_document2`:

```
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
    toc: yes
    toc_float: yes
    theme: cosmo
    highlight: textmate
```

By specifying `workflowr::wflow_html` as the base format, you will still get all the workflowr reproducibility features (please do let me know if you run into any problems). For more details on how this works, see the R Markdown Cookbook entry [Cross-referencing within documents](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html).

**Comment by rgayler** [comment]
@jdblischak thanks, I have tried your suggestions.

**1. Section header cross-reference within file (automatically supported by `pandoc`)**
```
## A nice section title

As I said [earlier](#a-nice-section-title)
```
That works with no YAML changes.

**2. Section header cross-reference between files (automatically supported by `pandoc`)**
```
As I said in the [other file](other_file.html#a-nice-section-title)
```
That works with no YAML changes.

**3. Figure/equation/table cross-reference within file (supported by `bookdown`)**
```
` ` ` {r my-label, fig.cap="A lovely caption."}
# R code to generate the figure
` ` `

Look at the lovely Figure \@ref(fig:my-label)
```
That works with `analysis/_site.yml` edited to use `bookdown`:
```
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
```
**4. Figure/equation/table cross-reference between file**
That doesn't appear work to work because although (presumably) `bookdown` supports between-file cross-references, the `bookdown/workflowr` hybrid formed by using `base_format: workflowr::wflow_html` does not. Is that correct?

**Comment by jdblischak** [comment]
> Is that correct?

@rgayler That is 100% correct. Thanks for the nice summary!

**Comment by UlvHare** [comment]
It will be a good idea to put that in _site.yml vignette as well as about bibliography references. I think not only me use workflowr for articles drafts, so references to figures, tables and biblio citations can be really helpful.

**Comment by jdblischak** [comment]
> It will be a good idea to put that in _site.yml vignette as well as about bibliography references. 

@UlvHare Thanks for the feedback. I agree it would be better to have this better documented. Which vignette are you referring to? I'm thinking of adding this to [Customize your research website](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html). Agreed?
