### ISSUE TITLE
wflow_build() doesn't work (rprojroot and callr unable to be loaded)

### ISSUE THREAD

**Issue by LearnUseZone** [workflowr/workflowr#217]
Hello, I wanted to put this into bug but maybe the problem is in my side.

As you can see from commands below (I executed them one by one), once I executed wflow_build(), I received an error. But I do not see a reason for that. After wflow_start(...) was executed my working directory was really changed to my project name. I kept the path to project short and without spaces and I didn't touch any of files within project folder and subfolders.
I didn't use wflow_git_config(...) because I already have a GitHub account and I didn't want to overwrite those credentials.

Based on provided credentials, my steps should be completely correct and I shouldn't have any problem with this quick building.
Can anybody please help me we what should I check? Maybe there's a problem with some installations but I doubt about that when wflow_start(...) worked.

Please let me know, if you need any further information from me.
Thank you in advance for your help.
Peter

> setwd("D:/Processing/GitHub_temp")

> library("workflowr")
This is workflowr version 1.6.2
Run ?workflowr for help getting started

> wflow_start("myTestProject")
wflow_start:
- New directory created at D:/Processing/GitHub_temp/myTestProject
- Project name is "myTestProject"
- Working directory changed to D:/Processing/GitHub_temp/myTestProject
- Git repo initiated at D:/Processing/GitHub_temp/myTestProject
- Files were committed in version 41ac0b1

> wflow_build()
Error: Unable to detect a workflowr project. This could be due to one of
the following reasons:

1) The function was not executed inside a workflowr project. Run
`getwd()` to determine the current working directory. Is the working
directory a workflowr project or one of its subdirectories?

2) The RStudio .Rproj file was deleted. workflowr requires an
RStudio .Rproj file to be located at the root of the project. Was it
deleted?
> getwd()
[1] "D:/Processing/GitHub_temp/myTestProject"

I rather put also image, to demonstrate that a root folder is also OK (e.g. that .Rproj isn't missing).
![image](https://user-images.githubusercontent.com/70752474/92647661-88d1b280-f2e8-11ea-8000-c796bea7d57d.png)

**Comment by jdblischak** [comment]
@LearnUseZone Thanks for the detailed bug report!

Overall what you have done looks correct, so I'm also surprised that you are receiving this error. The only thing I noticed was that you are using the `D:` drive for your workflowr project. This has caused issues in the past, but not recently.

Here are some diagnostics to get started troubleshooting. Please run the following and copy-paste the results:

```
R.home()
normalizePath("~")
tempdir()
```

And here is some test code to see if it can reproduce the bug. Please run it and copy-paste the results:

```
library(workflowr)
path <- tempfile()
wflow_start(path, change_wd = FALSE)
wflow_build(project = path)
sessionInfo()
```

**Comment by LearnUseZone** [comment]
@jdblischak thank you for advises. Please find results below:

1) I tried to do the same as I sent you yesterday in C drive but result is the same:
![image](https://user-images.githubusercontent.com/70752474/92685146-5dc27f80-f337-11ea-9640-f27110bd4a0d.png)

2) Results of your troubleshooting codes:
![image](https://user-images.githubusercontent.com/70752474/92685227-8b0f2d80-f337-11ea-9747-b4eca8707c6c.png)

3) Results of your test code:
![image](https://user-images.githubusercontent.com/70752474/92685473-0bce2980-f338-11ea-898e-a459041fdbe6.png)

![image](https://user-images.githubusercontent.com/70752474/92685520-286a6180-f338-11ea-9b62-59a929f683ac.png)

Created directories:
![image](https://user-images.githubusercontent.com/70752474/92685343-cf9ac900-f337-11ea-9672-08ae8f948a68.png)

![image](https://user-images.githubusercontent.com/70752474/92685668-839c5400-f338-11ea-8fca-d3379bbc8e04.png)

**Comment by jdblischak** [comment]
OK, so we've confirmed the bug is reproducible, and that it occurs for projects in both the C and D drives. Now let's try to isolate the exact source of the bug. Please run the code chunk below and report the results:

```
packageVersion("rprojroot")
library(rprojroot)
library(workflowr)
path <- tempfile()
wflow_start(path, change_wd = FALSE)
workflowr:::absolute(path)
find_rstudio_root_file(path = path)
find_root(criterion = has_file("_workflowr.yml"), path = path)
```

**Comment by LearnUseZone** [comment]
Results:
![image](https://user-images.githubusercontent.com/70752474/92729477-aba8a900-f372-11ea-9767-68888d64c4c2.png)

I saw a problem with library "rprojroot", so I reinstalled it
![image](https://user-images.githubusercontent.com/70752474/92729801-24a80080-f373-11ea-8897-82bfbf9b1a82.png)

I executed following code chunk again and it worked correctly:
- isolate the exact source of the bug
packageVersion("rprojroot")
library(rprojroot)
library(workflowr)
path <- tempfile()
wflow_start(path, change_wd = FALSE)
workflowr:::absolute(path)
find_rstudio_root_file(path = path)
find_root(criterion = has_file("_workflowr.yml"), path = path)
![image](https://user-images.githubusercontent.com/70752474/92729957-6769d880-f373-11ea-8aae-560a800a3904.png)


I executed also following code chunk again:
library(workflowr)
path <- tempfile()
wflow_start(path, change_wd = FALSE)
wflow_build(project = path)
sessionInfo()
![image](https://user-images.githubusercontent.com/70752474/92730022-7badd580-f373-11ea-8147-04c7d7bc28a3.png)
![image](https://user-images.githubusercontent.com/70752474/92730055-86686a80-f373-11ea-9ad6-f2d1751f9909.png)

So we moved further but there are other errors. I checked a relevant "docs" folder and it really contained only file ".nojekyll". Also I didn't find those .txt files with details.

**Comment by jdblischak** [comment]
Great! We're making progress. The original error was due to the fact that the R package rprojroot was not installed correctly on your machine. Re-installing it fixed the issue.

Your new error is the one previously reported in #216. It's a confusing error that multiple workflowr users have encountered. Essentially, the temporary directory used by the R session somehow gets corrupted (this is where workflowr writes its log files). We haven't been able to figure out what is causing this error yet. However, the [solution](https://github.com/jdblischak/workflowr/issues/216#issuecomment-677732622) that has worked for everyone so far is to update their R packages.

Before you update, please check the status of the callr package. I see that it is not included in the loaded namespaces section from `sessionInfo()`. This was also the case for rprojroot before you re-installed it, so I suspect this is causing the issue. Please run the code below:

```
packageVersion("callr")
library(callr)
```

Also, did you recently upgrade your version of R?

Now to update your packages, I recommend following the [advice from the R for Windows FAQ](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What_0027s-the-best-way-to-upgrade_003f):

```
update.packages(checkBuilt = TRUE, ask = FALSE)
```

After the packages have updated, please re-try the test code.

**Comment by LearnUseZone** [comment]
Regarding your question: "Also, did you recently upgrade your version of R?" - I've installed and used R version 4.0.2 all the time (my 1st R installation to a new computer).

I ran and based on message "there is no package called 'processx', I've installed 'processx'
packageVersion("callr")
library(callr)

![image](https://user-images.githubusercontent.com/70752474/92748709-b456aa80-f385-11ea-962b-1ee4f0089b6e.png)

After that library(callr) worked.

I also tried again 2 code chunks from above and everything included wflow_build() worked correctly.
![image](https://user-images.githubusercontent.com/70752474/92749010-fda6fa00-f385-11ea-89db-18624df6b35e.png)
![image](https://user-images.githubusercontent.com/70752474/92749058-0992bc00-f386-11ea-8f69-7cffd4edeae4.png)

Similar results as in the previous 2 pictures were with my original code chunk:
![image](https://user-images.githubusercontent.com/70752474/92749341-5080b180-f386-11ea-85bb-5ab0cb4d8685.png)

So the only problems really were in missing or wrongly installed packages.

Thank you very much for your quick responses and mainly that we found the problems quite fast.

**Comment by jdblischak** [comment]
Great! I'm glad we got this working for you. And I'm grateful to finally understand what was causing these cryptic error messages. Thank you for your persistence so that we could discover the true source of the error.

The reason the error messages were so cryptic was because of the error handling I am using. For both the call to rprojroot and callr, I wrap them in `tryCatch()`. That way if something goes wrong, I can try to give a more helpful hint of the problem. But this assumes that the packages are installed correctly. In these two cases above, the packages were incorrectly installed, so they triggered errors, but not because of the anticipated problems.

I already have code to detect if the minimum required versions are installed (since `install.packages()` doesn't guarantee this). To prevent future users from suffering from these errors, I'm going to additionally check that all the dependencies are able to be loaded.

https://github.com/jdblischak/workflowr/blob/7eae6fd0934c8d62a85646230e228e5035afd087/R/zzz.R#L27-L30

How do you install packages? Do you use `install.packages()`? I am really confused how you were able to install rprojroot (but not backports) and callr (but not processx). If you run `install.packages(c("rprojroot", "callr"))`, it will also install all the required dependencies. Do you ever use `remove.packages()` to manually delete packages? Any insights into how you manage your R package installations could be helpful.

**Comment by LearnUseZone** [comment]
I remember that I found your package but not in it's current version but in beta version (which couldn't be installed from CRAN) so I tried to install it and there were some messages like (I had this one copied) Error: Failed to install 'workflowr' from GitHub: (converted from warning) cannot remove prior installation of package ‘processx’, so I installed this package and also few more packages but then I found out that you already created version on CRAN so I uninstalled some packages like "processx" (at least I think so) because I thought that these packages were part of devtools (I think I reinstalled it too) so it could happen that during this installation and removal of packages, I did something wrong (which I didn't know that could be wrong) or something weren't reinstalled correctly - as we discovered above. I am not sure if I wrote it correctly because I don't remember what exactly I did but I think that my previous description is more-less correct.

I use install.packages(...) and remove.packages(...).

As you wrote, I think that a check saying if some package is missing could be helpful. Maybe for someone who works with R, RStudio, R packages daily, it's not needed but for someone who do few codes but it's not focused on R all the time, and want to use your package, it may really help - like it turns out in my case.

If you like to have more information, please feel free to ask.

**Comment by jdblischak** [comment]
>  Error: Failed to install 'workflowr' from GitHub: (converted from warning) cannot remove prior installation of package ‘processx’

@LearnUseZone Ah, ok. That makes sense. If there is an issue updating a dependency when attempting to install workflowr, I can see how that could lead to a situation where the required packages aren't installed. Thanks for the informative explanation of your setup!

Below I confirm the current behavior of workflowr 1.6.2 when its dependencies are unable to be loaded:

## rprojroot

``` r
# Behavior of workflowr 1.6.2 when dependency rprojroot is unable to be loaded

# Break rprojroot by removing one of its dependencies
suppressMessages(remove.packages("backports"))

# workflowr fails with misleading error message because
# rprojroot::find_rstudio_root_file() is called with try():
# https://github.com/jdblischak/workflowr/blob/7eae6fd0934c8d62a85646230e228e5035afd087/R/wflow_paths.R#L26
library(workflowr)
#> This is workflowr version 1.6.2
#> Run ?workflowr for help getting started
path <- tempfile()
wflow_start(path, change_wd = FALSE)
#> wflow_start:
#> - New directory created at C:/Users/john/AppData/Local/Temp/RtmpCWegkb/file335cf729f5
#> - Project name is "file335cf729f5"
#> - Working directory continues to be C:/Users/john/AppData/Local/Temp/Rtmps9yHDM/reprex3e802e057bb8
#> - Git repo initiated at C:/Users/john/AppData/Local/Temp/RtmpCWegkb/file335cf729f5
#> - Files were committed in version a4fc8d4
wflow_build(project = path)
#> Error: Unable to detect a workflowr project. This could be due to one of the
#> following reasons:
#> 
#> 1) The function was not executed inside a workflowr project. Run
#> `getwd()` to determine the current working directory. Is the working
#> directory a workflowr project or one of its subdirectories?
#> 
#> 2) The RStudio .Rproj file was deleted. workflowr requires an RStudio
#> .Rproj file to be located at the root of the project. Was it deleted?
```

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Error: .onLoad failed in loadNamespace() for 'pkgload', details:
#>   call: loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]])
#>   error: there is no package called 'backports'
```

</details>

## callr

``` r
# Behavior of workflowr 1.6.2 when dependency callr is unable to be loaded

# Break callr by removing one of its dependencies
suppressMessages(remove.packages("processx"))

# workflowr fails with uninformative error because callr::r_safe() is called
# with tryCatch():
# https://github.com/jdblischak/workflowr/blob/master/R/wflow_build.R#L471
library(workflowr)
#> This is workflowr version 1.6.2
#> Run ?workflowr for help getting started
path <- tempfile()
wflow_start(path, change_wd = FALSE)
#> wflow_start:
#> - New directory created at C:/Users/john/AppData/Local/Temp/RtmpMbyPhU/file28ec6e676d88
#> - Project name is "file28ec6e676d88"
#> - Working directory continues to be C:/Users/john/AppData/Local/Temp/RtmpmM86mS/reprex1ea0638542ca
#> - Git repo initiated at C:/Users/john/AppData/Local/Temp/RtmpMbyPhU/file28ec6e676d88
#> - Files were committed in version ac8734f
wflow_build(project = path)
#> Current working directory: C:/Users/john/AppData/Local/Temp/RtmpmM86mS/reprex1ea0638542ca
#> Building 3 file(s):
#> Building ../../RtmpMbyPhU/file28ec6e676d88/analysis/about.Rmd in C:/Users/john/AppData/Local/Temp/RtmpMbyPhU/file28ec6e676d88
#> Build failed. See log files for full details.
#> stdout: C:/Users/john/AppData/Local/Temp/RtmpMbyPhU/workflowr/about.Rmd-2020-09-11-10h-13m-59s-out.txt
#> stderr: C:/Users/john/AppData/Local/Temp/RtmpMbyPhU/workflowr/about.Rmd-2020-09-11-10h-13m-59s-err.txt
#> Warning in file(con, "r"): cannot open file 'C:/Users/john/AppData/Local/Temp/
#> RtmpMbyPhU/workflowr/about.Rmd-2020-09-11-10h-13m-59s-out.txt': No such file or
#> directory
#> Error in file(con, "r"): cannot open the connection
```

<sup>Created on 2020-09-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called 'processx'
```

</details>

**Comment by jdblischak** [comment]
These types of broken installation issues are now prevented on the GitHub version of workflowr. Below is the new behavior:

```
# missing rprojroot
> library(workflowr)
This is workflowr version 1.6.2.9000
Run ?workflowr for help getting started
Error: package or namespace load failed for ‘workflowr’:
  .onAttach failed in attachNamespace() for 'workflowr', details:
  call: check_dependencies()
error: The required dependency "rprojroot" is missing, please install it.

# rprojroot is installed, but can't be loaded (b/c backports is missing)
> library(workflowr)
This is workflowr version 1.6.2.9000
Run ?workflowr for help getting started
Error: package or namespace load failed for ‘workflowr’:
  .onAttach failed in attachNamespace() for 'workflowr', details:
  call: check_dependencies()
error: The required dependency "rprojroot" is unable to be loaded, please re-install it.

# rprojroot is installed, but it doesn't meet the minimum required version
> library(workflowr)
This is workflowr version 1.6.2.9000
Run ?workflowr for help getting started
Error: package or namespace load failed for ‘workflowr’:
  .onAttach failed in attachNamespace() for 'workflowr', details:
  call: check_dependencies()
error: Please update package "rprojroot": version 1.0.2 is installed, but 1.2 is required

# missing callr
> library(workflowr)
This is workflowr version 1.6.2.9000
Run ?workflowr for help getting started
Error: package or namespace load failed for ‘workflowr’:
  .onAttach failed in attachNamespace() for 'workflowr', details:
  call: check_dependencies()
error: The required dependency "callr" is missing, please install it.

# callr is installed, but can't be loaded (b/c processx is missing)
> library(workflowr)
This is workflowr version 1.6.2.9000
Run ?workflowr for help getting started
Error: package or namespace load failed for ‘workflowr’:
  .onAttach failed in attachNamespace() for 'workflowr', details:
  call: check_dependencies()
error: The required dependency "callr" is unable to be loaded, please re-install it.
```
