### ISSUE TITLE
Issue with creating projects in network-mounted folders (Windows)

### ISSUE THREAD

**Issue by philippbayer** [workflowr/workflowr#219]
Our work-machines are Windows machines with their `My Documents` folder on network storage which always leads to trouble. With workflowr, it triggers this error when trying to run anything:
```
> wflow_start('R_gene_analysis')
Error: [EISDIR] Failed to realize '//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents/R_gene_analysis': illegal operation on a directory
```

The workaround is to move the folder somewhere into C:\ and hope to never touch your Windows home.

```
 wflow_start('C:/temp/R_gene_analysis')
wflow_start:
- New directory created at C:/temp/R_gene_analysis
- Project name is "R_gene_analysis"
- Working directory changed to C:/temp/R_gene_analysis
- Git repo initiated at C:/temp/R_gene_analysis
- Files were committed in version 8a6560a
```

Interestingly setting `dry_run=TRUE` in `wflow_build` also makes it crash the same way.

Moving the folder back into the My Documents folder after `wflow_start()` on C:\ leads to the same error downstream:

```
> wflow_build()
Error: [EISDIR] Failed to realize '//uniwa.uwa.edu.au/userhome/staff3/STAFFID/My Documents/R_gene_analysis': illegal operation on a directory
```

Sessioninfo:
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] workflowr_1.6.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5      crayon_1.3.4    digest_0.6.25   later_1.1.0.1   R6_2.4.1        lifecycle_0.2.0 magrittr_1.5    evaluate_0.14   pillar_1.4.4   
[10] stringi_1.4.6   rlang_0.4.6     rstudioapi_0.11 fs_1.4.2        promises_1.1.1  vctrs_0.3.1     ellipsis_0.3.1  rmarkdown_2.3   tools_3.6.3    
[19] stringr_1.4.0   yaml_2.2.1      compiler_3.6.3  httpuv_1.5.4    xfun_0.15       pkgconfig_2.0.3 htmltools_0.5.0 knitr_1.29      tibble_3.0.2   
```

**Comment by jdblischak** [comment]
@philippbayer Thanks for the detailed bug report! Here are some ideas for troubleshooting.

The file path operations that workflowr performs are executed using the package [fs](https://cran.r-project.org/package=fs). The latest version is 1.5.0, and you have 1.4.2 installed on your machine. Could you please install the latest release with `install.packages("fs")` to make sure we aren't debugging a previously fixed bug? Even better, since Jim has been making lots of changes in preparation for the next release, would be to install the latest version from GitHub with `remotes::install_github("r-lib/fs")`. However, this requires that you have RTools installed to compile the C code, so don't worry if have to use version 1.5.0.

Let's pinpoint the problematic function by inspecting the traceback. Please run the following from `My Documents`:

```
library(workflowr)
wflow_start('R_gene_analysis')
traceback()
```

To assess how complicated the file path situation is, please run the following from `My Documents`:

```
#  base R path functions
(basePath <- getwd())
normalizePath(basePath)
dir.create("baseTest")
dir.exists("baseTest")
unlink("baseTest", recursive = TRUE)
dir.exists("baseTest")

# fs functions
library(fs)
(fsPath <- path_wd())
path_abs(fsPath)
dir_create("fsTest")
dir_exists("fsTest")
dir_delete("fsTest")
dir_exists("fsTest")
path_home()
path_home_r()
path_rel(fsTest, path_home())
```

> Interestingly setting `dry_run=TRUE` in `wflow_build` also makes it crash the same way.

This is because even in a dry run, `wflow_build()` still performs file path operations on the input. This is required for determining which files need to be built.

**Comment by philippbayer** [comment]
Thanks for the detailed answer! Here's a checklist:

- [x]  installed fs v1.5.0, restarted R. No change to wflow_build()
- [x] installed fs from github, it reports v1.5.0.9000 now.  Same error.
- [x] ran the traceback:

```
> wflow_start('R_gene_analysis')
Error: [EISDIR] Failed to realize '//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents': illegal operation on a directory
> traceback()
9: (function (..., call. = TRUE, domain = NULL) 
   {
       args <- list(...)
       if (length(args) == 1L && inherits(args[[1L]], "condition")) {
           cond <- args[[1L]]
           if (nargs() > 1L) 
               warning("additional arguments ignored in stop()")
           message <- conditionMessage(cond)
           call <- conditionCall(cond)
           .Internal(.signalCondition(cond, message, call))
           .Internal(.dfltStop(message, call))
       }
       else .Internal(stop(call., .makeMessage(..., domain = domain)))
   })(list(message = "[EISDIR] Failed to realize '//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents': illegal operation on a directory"))
8: fs::path_real(path)
7: resolve_symlink_(fs::path_join(parts[-len]))
6: fs::path_join(c(resolve_symlink_(fs::path_join(parts[-len])), 
       parts[len]))
5: FUN(X[[i]], ...)
4: vapply(path, resolve_symlink_, character(1), USE.NAMES = FALSE)
3: resolve_symlink(newpath)
2: absolute(directory)
1: wflow_start("R_gene_analysis")
```

Cccording to the traceback above, path_real is the culprit!

```
# this folder does not exist
> fs::path_real("R_gene_analysis")
Error: [ENOENT] Failed to realize 'R_gene_analysis': no such file or directory
# this folder exists, this is our workflowr error
> fs::path_real('Soybean_R_genes') 
Error: [EISDIR] Failed to realize 'Soybean_R_genes': illegal operation on a directory
> fs::path_real('C:/temp/R_gene_analysis')
C:/temp/R_gene_analysis
```

What's interesting is that there's a commit in workflowr fixing this issue in a different context: https://github.com/jdblischak/workflowr/commit/6d98dc985325b71f7ea2242d3db49c3b6fa38f2c

I guess the same fix should be applied to this line: https://github.com/jdblischak/workflowr/blob/18d2b840fe7c91eb2b82cab73acc21c4c293bcdc/R/utility.R#L135

Alternatively, that check for system = Windows doesn't fire but it should on my system:

```
> .Platform$OS.type
[1] "windows"
```

- [x] checked base R:

```
> (basePath <- getwd())
[1] "\\\\uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents"
> normalizePath(basePath)
[1] "\\\\uniwa.uwa.edu.au\\userhome\\staff3\\<STAFFID>My Documents"
> dir.create("baseTest")
> dir.exists("baseTest")
[1] TRUE
> unlink("baseTest", recursive = TRUE)
> dir.exists("baseTest")
[1] FALSE
```

That works fine!

- [x]  checked the fs code:

```> library(fs)
> (fsPath <- path_wd())
//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents
> path_abs(fsPath)
//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents
> dir_create("fsTest")
> dir_exists("fsTest")
fsTest 
  TRUE 
> dir_delete("fsTest")
> dir_exists("fsTest")
Error: [EPERM] Failed to stat 'fsTest': operation not permitted
> path_home()
C:/Users/<STAFFID>
> path_home_r()
//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents
> path_rel("fsTest", path_home())
../../../uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents/fsTest
```

So that dir_exists makes it complain, but I don't see the same error `wflow_build()` is giving me

**Comment by jdblischak** [comment]
Great! We've isolated the issue. It's `path_real()`.

Here's some more background: I use `path_real()` to resolve symlinks. Sometimes this is applied to files and directories that do not yet exist (e.g. the user has requested that a workflowr function create them). On Linux and macOS systems, I can directly apply `path_real()` to resolve symlinks in paths to non-existent files. However, I can't do that on Windows. Instead, I recursively peel back the file path until I get to an existing directory, and then I apply `path_real()`. This should work. Your system is properly recognized as Windows, but presumably because of the network drive, this causes an error.

I think the Issue is the [UNC path](https://en.wikipedia.org/wiki/Path_(computing)#Universal_Naming_Convention) to the network-mounted folder. Your issue looks similar to the existing issue https://github.com/r-lib/fs/issues/223. Could you please open an Issue on the fs repository to demonstrate that `path_real()` does not work on a network mounted drive? Please mention me so that I receive a notification. I believe the code below should reproduce the error:

```
library(fs)
path_wd()
dir_create("testDir")
dir_exists("testDir")
path_real("testDir")
dir_delete("testDir")
```

If this error can't be addressed directly in fs, then I can explore workarounds for workflowr.

**Comment by philippbayer** [comment]
Thanks very much, I've opened an issue with your minimal example. Until there's a followup I'll keep on running workflowr on folders in C:\, that's not the end of the world. Thanks for this great package and please say hi to your brother Paul from me :)

**Comment by jdblischak** [comment]
> Thanks very much, I've opened an issue with your minimal example.

Perfect! While we wait for a response, could you please try out the workaround that I've pushed to the branch [Issue219](https://github.com/jdblischak/workflowr/commits/Issue219)? You can install it with:

```
remotes::install_github("jdblischak/workflowr@Issue219")
```

Please test `wflow_start()`/`wflow_build()` on your network-mounted folder and in the C drive. Thanks!

> Thanks for this great package and please say hi to your brother Paul from me :)

Will do! :-)

**Comment by philippbayer** [comment]
The Issue219 branch works for me!

```
> wflow_start('hey')
wflow_start:
- New directory created at \\uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents/hey
- Project name is "hey"
- Working directory changed to \\uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents/hey
- Git repo initiated at //uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents/hey
- Files were committed in version 092431d
```

Hooray!

Opened the new .RProj file, then building:

```
 > wflow_build()
Current working directory: \\uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents/hey
Building 3 file(s):
Building analysis/about.Rmd
Build failed. See log files for full details.
stdout: C:/Users/<STAFFID>/AppData/Local/Temp/Rtmp0seI95/workflowr/about.Rmd-2020-09-18-22h-15m-57s-out.txt
stderr: C:/Users/<STAFFID>/AppData/Local/Temp/Rtmp0seI95/workflowr/about.Rmd-2020-09-18-22h-15m-57s-err.txt

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |......................................................................| 100%
  ordinary text without R code


"C:/Users/<STAFFID>/AppData/Local/CONTIN~1/ANACON~1/Library/bin/pandoc" +RTS -K512m -RTS about.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output about.html --email-obfuscation none --standalone --section-divs --template "C:\Users\<STAFFID>\AppData\Local\Continuum\anaconda3\Lib\R\library\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --include-before-body "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpQXDMOC\rmarkdown-str69ecc29b672fa.html" --variable navbar=1 --variable body_padding=51 --variable header_padding=56 --variable "theme:cosmo" --include-in-header "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpQXDMOC\rmarkdown-str69ecc78c67d37.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --lua-filter "C:/Users/<STAFFID>/AppData/Local/Continuum/anaconda3/Lib/R/library/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Users/<STAFFID>/AppData/Local/Continuum/anaconda3/Lib/R/library/rmarkdown/rmd/lua/latex-div.lua" --include-in-header "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpQXDMOC\header69ecc45864c5b.html" --include-after-body "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpQXDMOC\footer69ecc47c06a36.html" 
Error: callr subprocess failed: pandoc document conversion failed with error 1
```

But I think this is due to a slightly borked R-environment on my end - it shouldn't go into C:\Users\<STAFFID>, but that one comes from fs again as we have seen above:

```
> library(fs)
> path_home()
C:/Users/<STAFFID>
```

which i think comes from environment variables:

```
> Sys.getenv('HOME')
[1] " C:\\Users\\<STAFFID>\\Anaconda\\Lib\\site-packages\\rpy2"
> Sys.getenv('R_HOME')
[1] "C:/Users/<STAFFID>/AppData/Local/CONTIN~1/ANACON~1/Lib/R"
> Sys.getenv('R_USER')
[1] "//uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents"
> Sys.getenv('USERPROFILE')
[1] "C:\\Users\\<STAFFID>"
```

which I have to fix myself, but I think workflowr works fine now?

**Comment by jdblischak** [comment]
It looks like you are using R installed in a conda environment that is located in the mounted-network folder. Is that correct? If yes, would it be possible to instead move conda to the C drive? That might help.

I suspect the issue may be with R's temporary session directory. Workflowr needs to be able to read and write to files in this directory. Could you please test if R is able to read and write to its temporary directory:

```
fs::path_temp()
tmp <- fs::file_temp()
writeLines("test", con = tmp)
readLines(tmp)
```

On my Windows 10 machine, I get the following:

```
> fs::path_temp()
C:/Users/john/AppData/Local/Temp/RtmpMbW4QM
> tmp <- fs::file_temp()
> writeLines("test", con = tmp)
> readLines(tmp)
[1] "test"
```

Also, if possible, could you try to open the log files that `wflow_build()` mentions after it fails? There may be some clues in there.

**Comment by philippbayer** [comment]
Hi

This is definitely an issue unrelated to the first issue with fs,

```
> fs::path_temp()
C:/Users/<STAFFID>/AppData/Local/Temp/RtmpmuPzQ4
> tmp <- fs::file_temp()
> writeLines("test", con = tmp)
> readLines(tmp)
[1] "test"
```

That one works, with the weird C:\Users path!

This is the .err output:
```
Loading .Rprofile for the current workflowr project
This is workflowr version 1.6.2.9000
Run ?workflowr for help getting started
pandoc.exe: about.utf8.md: openBinaryFile: does not exist (No such file or directory)
Error : pandoc document conversion failed with error 1
```

This is the .out output:
```
  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |......................................................................| 100%
  ordinary text without R code


"C:/Users/<STAFFID>/AppData/Local/CONTIN~1/ANACON~1/Library/bin/pandoc" +RTS -K512m -RTS about.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output about.html --email-obfuscation none --standalone --section-divs --template "C:\Users\<STAFFID>\AppData\Local\Continuum\anaconda3\Lib\R\library\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --include-before-body "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpKCDA1m\rmarkdown-str41f60543f2acd.html" --variable navbar=1 --variable body_padding=51 --variable header_padding=56 --variable "theme:cosmo" --include-in-header "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpKCDA1m\rmarkdown-str41f6027901f2a.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" --lua-filter "C:/Users/<STAFFID>/AppData/Local/Continuum/anaconda3/Lib/R/library/rmarkdown/rmd/lua/pagebreak.lua" --lua-filter "C:/Users/<STAFFID>/AppData/Local/Continuum/anaconda3/Lib/R/library/rmarkdown/rmd/lua/latex-div.lua" --include-in-header "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpKCDA1m\header41f6029bb561a.html" --include-after-body "C:\Users\<STAFFID>\AppData\Local\Temp\RtmpKCDA1m\footer41f60eba2dc9.html" 
```

So the error is `pandoc.exe: about.utf8.md: openBinaryFile: does not exist (No such file or directory)`.

This seems to be a common error with network drives and knitr/pandoc, see for example https://stackoverflow.com/questions/48161177/r-markdown-openbinaryfile-does-not-exist-no-such-file-or-directory

It's definitely a different but related issue, and in there is the best workaround from that SO thread - open the rstudio project through an assigned drive letter, not the \\ path way.

So in my case:
```
> wflow_build()
Current working directory: H:/My Documents/hey
Building 3 file(s):
Building analysis/about.Rmd
Building analysis/index.Rmd
Building analysis/license.Rmd
Summary from wflow_build

Settings:
 make: TRUE

The following were built externally each in their own fresh R session: 

docs/about.html
docs/index.html
docs/license.html

Log files saved in C:/Users/<STAFFID>/AppData/Local/Temp/RtmpE3Zvld/workflowr
```

Bam! That works :) So this is another workaround that works for workflowr too:

```
> getwd()
[1] "\\\\uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents"
> # wflow_build() triggers the usual error, so let's switch over to H:\ and the same folder (if not existing: Open This PC, right-click anywhere, click 'Add a network location', then enter the \\ location as the path and whatever drive letter as the mount position)

> setwd('H:/My Documents')
> getwd()
[1] "H:/My Documents"
> wflow_start('hey2')
wflow_start:
- New directory created at H:/My Documents/hey2
- Project name is "hey2"
- Working directory changed to H:/My Documents/hey2
- Git repo initiated at H:/My Documents/hey2
- Files were committed in version 6a09f26
```

Tada :) It's another workaround but using H:\ or whatever drive letter instead of \\NETWORK_LOCATION definitely helps avoid a bucket of errors.

To set this permanently for anyone who comes here via Google - In RStudio, Tools -> Global Options. In my case the default working directory was set to ~ which for some reason becomes "\\\\uniwa.uwa.edu.au/userhome/staff3/<STAFFID>/My Documents". Manually setting that to "H:\My Documents" sets the above workaround up permanently.

**Comment by jdblischak** [comment]
@philippbayer Thanks for being persistent and finding a workaround to this issue! Now that you mentioned it, I recall having heard that trying to use knitr/rmarkdown/pandoc on a network drive was problematic. So it's probably advisable to avoid using UNC paths all together. If Jim offers a solution via fs in https://github.com/r-lib/fs/issues/296, then we can update this advice.

Summarizing your advice for using network-mounted drives on Windows:

1. Always start paths with the drive letter, e.g. `H:` and not `\\`
1. To change the default RStudio configuration, go to `Tools` -> `Global Options` and change the default working directory from `~` to a path that explicitly starts with the drive letter

**Comment by philippbayer** [comment]
Great! Yeah that's a good summary :) Thanks for your help!
