### ISSUE TITLE
Can't push using SSH protocol - error authenticating: failed connecting agent

### ISSUE THREAD

**Issue by LearnUseZone** [workflowr/workflowr#222]
Hello,

I encountered another issue. When I tried to use SSH, I received error authenticating: failed connecting agent. Can you please help me resolving it?

Relevant information/steps follows:
1) I used steps from https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html in subtitle "Setup SSH keys" where it was also mentioned to use https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh which I did.
If I summarize that, steps I did were:
1) I installed Git with Git Bash from https://git-scm.com/download/win  -> Git 2.28.0-64-bit  for Windows  (I have Windows 10 64-bit)
2) ls -al ~/.ssh  -  showed that I didn't have SSH keys
3) ssh-keygen -t rsa -b 4096 -C "myemailddress@email.com"      - my private and public key files were generated (I kept their default names)
4) eval $(ssh-agent -s)    - returned: Agent pid 277    - so my ssh-agent should be running
I also run:
if ps -p $SSH_AGENT_PID > /dev/null
then
   echo "ssh-agent is already running"
else
eval `ssh-agent -s`
fi

with result: ssh-agent is already running

5) ssh-add ~/.ssh/id_rsa      - I didn't choose password (simply pressed Enter) because I read at https://github.com/jdblischak/workflowr/pull/203 that it could cause problems
result: Identity added: /c/Users/Master/.ssh/id_rsa (myemailddress@email.com)

6) GitHub -> Settings -> SSH and GPG keys -> chose title -> copy-paste key
7) ssh -T git@github.com    - to test connection
![image](https://user-images.githubusercontent.com/70752474/94245682-eab22f00-ff1a-11ea-9fda-f791b0dd41da.png)

7) wflow_git_remote(remote = "origin", user = "LearnUseZone", repo = "myTestProject",
                 protocol = "ssh", action = "set_url")
![image](https://user-images.githubusercontent.com/70752474/94245843-264cf900-ff1b-11ea-9629-383a1ab5804b.png)

8) Added file (to have something to push)
9)
workflowr::wflow_build()
workflowr::wflow_publish(".", "publish testSSH.txt")

10) Until now everything seemed to be OK.
11) workflowr::wflow_git_push() returned error pointing "failed connecting agent"

Error: Push failed for unknown reason.

The error message from git2r::push() was:

Error in 'git2r_push': error authenticating: failed connecting agent

These sorts of errors are difficult to troubleshoot. You can search for
similar errors on the git2r GitHub repository for advice on how to fix
it.

Alternatively, if you have Git installed on your machine, the easiest
solution is to instead run `git push` in the terminal. This is
equivalent to wflow_git_push(). Specifically, copy-paste the following
in the terminal:

git push -u origin master

12) I found some other similar issues, but not exactly this one, which I tried to apply in case that could solve my problem
12a) I run following (based on https://github.com/jdblischak/workflowr/issues/98 and https://github.com/jdblischak/workflowr/issues/173)

> library(git2r)
> r <- repository()
> push(r, name = "origin", refspec = "refs/heads/master")
Error in push(r, name = "origin", refspec = "refs/heads/master") : 
  Error in 'git2r_push': error authenticating: failed connecting agent

12b) I run following (based on https://github.com/jdblischak/workflowr/issues/98)
> library("git2r")
> libgit2_features()$ssh
[1] TRUE

12c) I run following (based on https://github.com/jdblischak/workflowr/pull/203)
> git2r::cred_ssh_key()
$publickey
[1] "C:\\Users\\Master\\.ssh\\id_rsa.pub"

$privatekey
[1] "C:\\Users\\Master\\.ssh\\id_rsa"

$passphrase
character(0)

attr(,"class")
[1] "cred_ssh_key"

12d) I have reinstalled "git2r" and recheck again (based on https://github.com/jdblischak/workflowr/issues/98)
> library("git2r")
> libgit2_features()$ssh
[1] TRUE

12e) result error message still remains.
when I run
workflowr::wflow_use_github("LearnUseZone", "myTestProject")
workflowr::wflow_git_push()

then after I entered my credentials, push worked correctly.

13) I rather also send sessionInfo()
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Slovak_Slovakia.1250  LC_CTYPE=Slovak_Slovakia.1250   
[3] LC_MONETARY=Slovak_Slovakia.1250 LC_NUMERIC=C                    
[5] LC_TIME=Slovak_Slovakia.1250    
system code page: 1252

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] git2r_0.27.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5      rstudioapi_0.11 knitr_1.29      magrittr_1.5   
 [5] workflowr_1.6.2 R6_2.4.1        rlang_0.4.7     stringr_1.4.0  
 [9] tools_4.0.2     xfun_0.17       htmltools_0.5.0 ellipsis_0.3.1 
[13] yaml_2.2.1      digest_0.6.25   rprojroot_1.3-2 tibble_3.0.3   
[17] lifecycle_0.2.0 crayon_1.3.4    later_1.1.0.1   vctrs_0.3.2    
[21] promises_1.1.1  fs_1.5.0        glue_1.4.2      evaluate_0.14  
[25] rmarkdown_2.3   stringi_1.5.3   compiler_4.0.2  pillar_1.4.6   
[29] backports_1.1.9 httpuv_1.5.4    pkgconfig_2.0.3

**Comment by jdblischak** [comment]
@LearnUseZone Thanks for the detailed bug report! Below is my summary of the issue and some suggestions on how to proceed:

1. This issue is caused by the new OpenSSH formatting of SSH keys. It is not currently supported by git2r, which is the package that workflowr uses for all Git-related operations (discussed in https://github.com/ropensci/git2r/issues/421#issuecomment-627090309). The update to git2r is a work-in-progress (https://github.com/ropensci/git2r/pull/422). I'd prefer the problem be fixed there instead of trying to create a temporary, fragile workaround in workflowr.

1. As you have discovered, pushing directly in Git Bash with `git push` works fine. The functions `wflow_git_push()` and `wflow_git_pull()` are provided purely as convenience functions for those that don't have Git installed. They don't provide any extra workflowr-specific functionality. Since you've already taken the time to install Git Bash, you can avoid this problem entirely by always pushing and pulling from Git Bash. If you don't want to have to open a separate window, you can configure RStudio to use Git Bash as the default terminal (it will probably do this by default), and then open a terminal in RStudio (`Tools` -> `Terminal` -> `New Terminal`).

1. If you really want to use `wflow_git_push()` directly in R, you can change the format of your SSH keys. Try the advice in https://github.com/ropensci/git2r/issues/421#issuecomment-627090309 by running the following in Git Bash:

    ```
    ssh-keygen -p -m PEM -f C:\Users\Master\.ssh\id_rsa
    ```

   And then run `wflow_git_push()` in R. If you attempt this solution, please let me know how it goes.

**Comment by LearnUseZone** [comment]
@jdblischak , thank you for advises. I did 3 tests. You can skip Test 1 and 3 (I made them just to be absolutely sure that there couldn't be any other problem).

_Test 1 - using GitHub Desktop -> Push origin (brief steps)_
* Add testFile.txt to “docs” folder.
* Git Bash -> if ps -p $SSH_AGENT_PID > /dev/null ...... fi  (see step 5 in my original comment)
* wflow_git_remote  (see step 8 in my original comment)
* workflowr::wflow_publish(".", "add testFile.txt")  # to make a commit
* GitHub Desktop -> Push origin
* Result of Test1: Everything worked correctly.

_Test 2 - using workflowr -> workflowr::wflow_git_push()_
* Add testFile2.txt to “docs” folder.
* Git Bash
   * if ps -p $SSH_AGENT_PID > /dev/null ...... fi  (see step 5 in my original comment)
   * ssh-keygen -p -m PEM -f /c/Users/Master/.ssh/id_rsa -> press Enter to have no passphrase
![image](https://user-images.githubusercontent.com/70752474/94335341-5a87ee80-ffdb-11ea-807f-18e738c00532.png)
* Test SSH connection with Git Hub remote repository -> ssh -T git@github.com
![image](https://user-images.githubusercontent.com/70752474/94335360-7b504400-ffdb-11ea-975f-f0ba46ae13a1.png)
* RStudio
  * wflow_git_remote  (see step 8 in my original comment)
  * workflowr::wflow_publish(".", "add testFile2.txt")  # to make a commit
  * workflowr::wflow_git_push()  
![image](https://user-images.githubusercontent.com/70752474/94335426-e7cb4300-ffdb-11ea-96c0-930d7ba1a465.png)
* Result of Test2: Failed again.

_Test 3 - using using Git and Git Bash -> git push -u origin master (brief steps)_
* Add a new file to folder “docs”
* Do steps in Test 2 except workflowr::wflow_git_push()
* Some Git settings:
  * cd D:/Cloud/Sync/Study/Programming/R/Work/Projects/GitHub/myTestProject
  * `# git init  # didn’t used because my repository is already initialized
  * git status  # result: Your branch is ahead of 'origin/master' by 1 commit (that’s correct)
  * git remote add origin 'git@github.com:LearnUseZone/myTestProject.git'  # fatal: remote origin already exists (but that's OK)
  * git push -u origin master
* Result of Test3: Everything worked correctly.

**Comment by LearnUseZone** [comment]
Hello again,
I quickly made also the 4th test of using Git Bash terminal in RStudio as you adviced. I used similar steps like in Test 1 but the last step was running "git push -u origin master" in RStudio Git Bash Terminal. Result of this Test 4: Everything worked correctly.

I like the approach of waiting to proper solution instead of using workaround especially when we talk about only one line of code that can be easily executed in RStudio Git Bash Terminal (or alternatively pushing "Push origin" button in GitHub Desktop) although it's still slightly better (at least for me) to use as less additional software (or steps) as possible.

If you have any other idea what we can test, feel free to let me know and I can try but as I mentioned above, maybe it's not worth it when we talk only about pushing that is one line of code.

One more question (slightly out of this topic): If I looked correctly there's no possibility of adding some kind of description to commits using workflowr::wflow_publish (like it's available e.g. in GitHub Desktop). Is there a possibility to add it somehow using workflowr package?

**Comment by jdblischak** [comment]
> Result of Test2: Failed again.

Thanks for another round of detailed tests. That's frustrating that after you updated the format of your SSH key, the error was still the same (`error authenticating: failed connecting agent`).

> Test SSH connection with Git Hub remote repository -> ssh -T git@github.com

This was a good idea! This eliminates the possibility that there was a problem with the keys themselves.

> One more question (slightly out of this topic): If I looked correctly there's no possibility of adding some kind of description to commits using workflowr::wflow_publish (like it's available e.g. in GitHub Desktop). Is there a possibility to add it somehow using workflowr package?

Are you referring to the Git commit message? This is the second argument of both `wflow_publish()` and `wflow_git_commit()`.

https://jdblischak.github.io/workflowr/reference/wflow_publish.html
https://jdblischak.github.io/workflowr/reference/wflow_git_commit.html

Users are highly encouraged to write informative commit messages with workflowr. See this section of the Getting Started vignette:

https://jdblischak.github.io/workflowr/articles/wflow-01-getting-started.html#publish-the-website

**Comment by LearnUseZone** [comment]
Fortunately this "error authenticating: failed connecting agent" is not a big deal when Git Bash can be used as my RStudio terminal.

The picture below shows "Description" option (basically as additional place where to write commit message) of GitHub Desktop.
![image](https://user-images.githubusercontent.com/70752474/94671968-de601480-0314-11eb-8713-b679ed956db9.png)
I was only curious if there's something like that implemented also in your workflowr package, but based on your encouragement I will simply write more information if needed to wflow_publish() and wflow_git_commit() to parameter "message".

**Comment by jdblischak** [comment]
> The picture below shows "Description" option (basically as additional place where to write commit message) of GitHub Desktop.

Ah, ok. Now I understand. GitHub Desktop is strongly encouraging the use of a summary line and a separate description. These are then combined into one commit message. The summary line is a useful convention for writing commit messages. For example, GitHub will show the summary line when displaying the list of commits. And if you run `git log --oneline`, it only displays the summary line.

At the moment, the best way to achieve this directly in the R console is to manually include the line breaks with `\n\n`, e.g.

```
wflow_publish("analysis/test.Rmd", "This is the summary line\n\nThis is the description")
```

However, if you like the GUI experience of GitHub Desktop, you can use a similar interface for workflowr directly in RStudio. The workflowr package includes RStudio addins for common workflowr functions.

![image](https://user-images.githubusercontent.com/1608317/94677351-bf4c8d00-02ea-11eb-8a40-561737c211d9.png)



To obtain a summary line and description, you can simply separate the two with a blank line, as shown below:

![image](https://user-images.githubusercontent.com/1608317/94677238-95936600-02ea-11eb-8aca-5177a38e871c.png)

If you strongly prefer using `wflow_publish()` directly in the R console, I have an Issue open, #33, about improving the experience of writing commit messages directly in workflowr. If you have any thoughts about how this could be done, please feel free to share them there.

**Comment by LearnUseZone** [comment]
Thank you very much. It works.
If I have more "message" related questions/ideas especially for wflow_publish() I will write to https://github.com/jdblischak/workflowr/issues/33

**Comment by LearnUseZone** [comment]
Just to have all tests together - I tested today pushing to GitLab using SSH key and the result were the same as for GitHub so in both cases "git push -u origin master" has to be used, but it's mentioned above, it's quite simple when RStudio Terminal opens with Git Bash.

**Comment by jdblischak** [comment]
@LearnUseZone A quick update on your question about the `message` argument. Now that #225 has been merged, it is now easier to create a commit message using the style recommended by GitHub Desktop (and in general a good idea). If you pass a character vector to `message`, the first element will be used as the title, and the remaining elements will be used for the body, e.g.

```
wflow_publish("analysis/example.Rmd", message = c("Summary", "Description"))
```

You can try out this new behavior using the GitHub version:

```
remotes::install_github("jdblischak/workflowr")
```
