### ISSUE TITLE
not commiting my html

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#25]
I'm having a problem (v0.4) where for some reason workflowr isn't commiting the html as i expect.
Here is outcome of git status:

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   analysis/index.Rmd
	modified:   docs/index.html

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/ldak.html

no changes added to commit (use "git add" and/or "git commit -a")

I just ran workflowr::wflow_commit(commit_files="ldak.rmd")

when I try again:
workflowr::wflow_commit(commit_files = "ldak.rmd")
Everything up-to-date
Warning message:
In workflowr::wflow_commit(commit_files = "ldak.rmd") :
  None of the commit_files provided were committed, presumably because they have not been updated.

then i try updating the rmd slightly and running again:
workflowr::wflow_commit(commit_files = "ldak.rmd")
Everything up-to-date

or all:
workflowr::wflow_commit(all=TRUE)
workflowr::wflow_commit(all=TRUE)

Rendering about.Rmd
Rendering confounding.Rmd
Rendering license.Rmd

not sure why it doesn't do ldak.rmd...

would a wflow_status command help debug this kind of thing?

**Comment by jdblischak** [comment]
I think this is the same bug as in #10. `wflow_build` and`wflow_commit` cannot yet handle lowercase `rmd` as a file extension. More recent changes I have made (e.g. updates to `wflow_open` and new functions like `wflow_convert`) can handle both `Rmd` and `rmd`.

My next development efforts is going to be focused on overhauling `wflow_build` and `wflow_commit`. During this overhaul I will also add support for the `rmd` file extension.

**Comment by jdblischak** [comment]
[workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0) should support both `.Rmd` and `.rmd` file extensions. Please re-open this Issue if you run into similar problems again
