### ISSUE TITLE
Trouble with Cairo support

### ISSUE THREAD

**Issue by jennysjaarda** [workflowr/workflowr#254]
I am running into an error with building my rmd document due to Cairo-based devices? IT seems like something similar was posted here: https://github.com/rstudio/rmarkdown/issues/1100 but I couldn't find a clear solution. 

```
wflow_build("analysis/update_meeting_05_07_2021.Rmd")
Current working directory: /data/sgg2/jenny/projects/proxyMR
Building 1 file(s):
Building analysis/update_meeting_05_07_2021.Rmd
Build failed. See log files for full details.
stdout: /tmp/RtmpLGc2Z8/workflowr/update_meeting_05_07_2021.Rmd-2021-07-05-13h-58m-00s-out.txt
stderr: /tmp/RtmpLGc2Z8/workflowr/update_meeting_05_07_2021.Rmd-2021-07-05-13h-58m-00s-err.txt
  |.....                                                                 |   8%
  ordinary text without R code


  |                                                                            
  |...........                                                           |  15%
label: seed-set-by-workflowr (with options) 
List of 1
 $ echo: logi FALSE


Error: callr subprocess failed: svg: Cairo-based devices are not available for this platform

```
```
svg()
Error in svg() :
  svg: Cairo-based devices are not available for this platform
```

For reference I am running on a Linux cluster and I compiled R from source as follows: 

`./configure --with-x=no --prefix=/data/sgg2/jenny/bin/R-4.1.0`

Could the `--with-x=no` be the problem?

**Comment by jdblischak** [comment]
@jennysjaarda I'm sorry you're having trouble with R graphics. I don't have any special insights on Cairo-based graphics, so I don't think I can help you.

Did you check what graphics devices are supported by running `capabilities()`? This would be a quick way to determine if it was a compilation issue.

Do you think that workflowr is part of the problem? If yes, please try running the file below outside of your workflowr project. It creates a figure and saves it as PNG. If this also fails, that means it's an issue with R.

````
---
title: "Untitled"
output:
  html_document:
    self_contained: false
---

```{r plot}
plot(1:10)
```

````


Out of curiosity, is there a strong reason why you need to compile R yourself on Linux? Most Linux flavors package R (e.g. `apt-get install r-base` on Ubuntu). And if you don't have admin rights, you could use a package manager like conda, nix, or spack.

**Comment by tashrifbillah** [comment]
> Could the --with-x=no be the problem?

This was not the problem in CentOS 9. I am having the same issue in CentOS 9. Did anyone find the solution?

**Comment by jdblischak** [comment]
> Did anyone find the solution?

Not that I'm aware of.

> I am having the same issue in CentOS 9.

Are you using workflowr? Did you run my minimal test R Markdown file above?

**Comment by tashrifbillah** [comment]
> Are you using workflowr? 

I do not know what that is. I installed R following:
https://docs.posit.co/resources/install-r-source/#download-and-extract-r


> Did you run my minimal test R Markdown file above?

Do I launch R and copy your code in it to run it? Sorry, how to? :)

**Comment by tashrifbillah** [comment]
This is my error:

```R
processing file: myproject/report.Rmd
  |.......                                             |  14% [unnamed-chunk-1]
Quitting from lines 2-21 [unnamed-chunk-1] (myproject/report.Rmd)
Error:
! svg: Cairo-based devices are not available for this platform
Backtrace:
  1. knitr::knit2html(...)
  2. knitr::knit(input, text = text, envir = envir, quiet = quiet)
  3. knitr:::process_file(text, output)
  8. knitr:::process_group.block(group)
  9. knitr:::call_block(x)
 10. knitr:::block_exec(params)
 11. knitr:::eng_r(options)
 12. knitr:::chunk_device(options, keep != "none", tmp.fig)
 14. grDevices (local) `<fn>`(...)
Warning message:
In png(..., res = dpi, units = "in") : no png support in this version of R                                                                           
```

An easier reproduction of the error was `svg('test.svg`.

**Comment by tashrifbillah** [comment]
I tried your file:

> $ Rscript minimal.R

> Error in -title : invalid argument to unary operator
> Execution halted

Nothing happened.

**Comment by jdblischak** [comment]
> Are you using workflowr?
>
> I do not know what that is. I installed R following:
> https://docs.posit.co/resources/install-r-source/#download-and-extract-r

You are posting to the Issues for the R package workflowr.

As far as I can tell, this cairo bug has nothing to do with my package. It is a problem with building R from source on CentOS. I cannot help you with that. I recommend posting to [Posit Community](https://community.rstudio.com), [r/rstats/](https://www.reddit.com/r/rstats/), or StackOverflow.

**Comment by tashrifbillah** [comment]
Hi @jdblischak , after all this months, I figured out my solution. Posting my solution for future Googlers:

https://github.com/rstudio/rstudio/issues/15404

Essentially, I had to rebuild R with `--with-cairo` flag :smiley:
