### ISSUE TITLE
Adding parameters for wflow_build function

### ISSUE THREAD

**Issue by YvesCR** [workflowr/workflowr#255]
Adding a parameter option for wflow_build when running only one file , akin to the params in rmarkdown header.

I generally prefer to run particular notebook over build the entire project as it takes less time (using file= option). Of course regularly building the entire project but though. Adding a parameter can allow differentiation in the code for behavior depending on if the entire build is run or only one notebook.

**Comment by pcarbo** [comment]
@YvesCR You can build one file with `wflow_build("myfile.rmd")`.

**Comment by YvesCR** [comment]
yeah but what would be fancy is to build it with ``wflow_build(file = "myfile.rmd", params = list(params1 = "test_run", params2 = "my_param_2"))`` and the parameters being fed to the notebook as a pre-knitr step. So we can differentiate in the notebook if the file is build on its own or it is the entire project build at once. 

Oh, right. One more addition: I use ``wflow_build(file = "myfile.rmd")`` because I want to have the notebooks build in a particular order. So I rarely use ``wflow_build`` function.

**Comment by jdblischak** [comment]
@YvesCR Thanks for opening the Issue!

Unfortunately workflowr does not support parameterized R Markdown files. This would break the reproducibility guarantees of workflowr. It relies on a 1:1 correspondence between each Rmd and HTML. Also, all the code in the Rmd file needs to be run as is. If you change the params dynamically by passing them to `wflow_build()`, it would be more difficult for you or someone else to recreate those results in the future. See Issue #213 for a previous discussion about parameterized R Markdown files.

However, you can still achieve similar functionality in workflowr using other knitr features. For example, let's say you want to run the same analysis on 5 different input values. You can create one child Rmd file with the shared template code. Then you would create 5 separate Rmd files that pass their input value to the child Rmd file. Please check out the vignette [Sharing common code across analyses](https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html) for various options, and please let me know if any of these will work for your use case.

**Comment by YvesCR** [comment]
Fantastic! It works to use a Rmd for the core! Closing the issue. Thanks!

FYI I have 2 notebooks calling the same general one, each with different set up. One is for running it independently and the other one to run with the full build. I simply did not put the link in the index notebook so it is kind of hidden.
