### ISSUE TITLE
Add option to `wflow_build` to knit with params?

### ISSUE THREAD

**Issue by rmgpanw** [workflowr/workflowr#262]
Hi, thank you for developing this amazing package. Would it be possible to add an option to the `wflow_build` function that allows for parameterised reports (i.e. the `params` argument for `rmarkdown::render()`)?

Many thanks for considering

**Comment by jdblischak** [comment]
@rmgpanw Thanks for the positive feedback and for opening an Issue!

Unfortunately workflowr cannot support parameters in Rmd files. The reproducibility guarantees made by workflowr require an exact 1:1 correspondence between the input Rmd file and its output HTML file. Allowing a single Rmd file to create multiple HTML output files, all with different parameters (passed via `wflow_build()`, and thus undocumented in the source Rmd file), would break these promises.

But there are lots of options for re-using code across multiple similar Rmd files. For ideas, please read the vignette [Sharing common code across analyses](https://jdblischak.github.io/workflowr/articles/wflow-07-common-code.html). Also see the discussion in the related Issue #255.

**Comment by rmgpanw** [comment]
That's great, thanks for getting back to me so quickly and for the helpful links (apologies I missed issue #255 before posting!). Closing this now.
