### ISSUE TITLE
How to define my own list and order of Rmd files

### ISSUE THREAD

**Issue by altairwei** [workflowr/workflowr#263]
By using {bookdown}, we can include a configuration file named `_bookdown.yml` in the book directory, and use a field named `rmd_files` to define our own list and order of Rmd files for the book. Does {workflowr} have similar features? By the way, I don't like to use `01-/02-/03-` prefixes to sort Rmd files because it is not good for version control.

**Comment by jdblischak** [comment]
>  define our own list and order of Rmd files for the book

@altairwei Thanks for the question. Could you please elaborate on exactly you mean by "order"? In the bookdown context, the book is a linear ordering of chapters (1 per Rmd file). There is no analogous linearity in workflowr. It is a website, and you can provide hyperlinks between any of the pages. Typically you provide a list of analysis pages in `index.Rmd`. These can be in any order you like.

Or are you referring to the order in which the Rmd files are executed? There is no explicit support for this. I've long thought about it (see Issue #9), but I don't really have the time to implement a solution. Some users that want fine-grained control of the Rmd execution order combine workflowr with targets (e.g. see Issue #238).

Looking at the [explanation of bookdown's support for `rmd_files`](https://bookdown.org/yihui/bookdown/usage.html#usage), I think the most straigtforward thing would be to include a file in your workflowr project with your desired order. For example, if you committed a file `order.txt` to your repo that contained the following:

```
analysis/index.Rmd
analysis/clean.Rmd
analysis/train.Rmd
analysis/predict.Rmd
```

Then you could have workflowr always build them in this order using code such as the following:

```R
rmd_files <- readLines("order.txt")

# Preview the changes
wflow_build(rmd_files)

# Publish (ie commit) the changes
wflow_publish(rmd_files, "commit message")
```

Would the above solution work for your use case?

**Comment by altairwei** [comment]
> Or are you referring to the order in which the Rmd files are executed? There is no explicit support for this. I've long thought about it (see Issue #9), but I don't really have the time to implement a solution. Some users that want fine-grained control of the Rmd execution order combine workflowr with targets (e.g. see Issue #238).

This is exactly what I mean. I was struggling to combine {workflowr} with {targets}, however it proved to be a hard work. Although _Target Markdown_ of {targets} is very close to the approach I want, it does not allow mixing of normal R chunks and _Target Markdown_ chunks. If my understanding is correct, normal R chunks can only safely be executed after `tar_make()` . So I finally decided to manually save the intermediate products of the R chunks and then rely on the execution order of the Rmd files to ensure the correct workflow.

> I think the most straigtforward thing would be to include a file in your workflowr project with your desired order.

That's the workaround I'm currently using.

**Comment by jdblischak** [comment]
> That's the workaround I'm currently using.

Ok, great. Thanks for reporting back that you went with my proposed workaround.
