### ISSUE TITLE
"Change to the worse" with recent glue CRAN submission (v1.6.0)

### ISSUE THREAD

**Issue by jennybc** [workflowr/workflowr#265]
I haven't delved into this yet but also thought you might be faster than I at determining if this is a false positive. I will have a look soon myself. This didn't show up in my own revdep checks. And this was the only failure that CRAN reported.

https://win-builder.r-project.org/incoming_pretest/glue_1.6.0_20211216_210809/reverseDependencies/summary.txt

**Comment by jennybc** [comment]
This looks a lot like some existing CRAN errors for r-devel-linux-x86_64-fedora-clang, r-devel-linux-x86_64-fedora-gcc, and M1mac:

https://cran.r-project.org/web/checks/check_results_workflowr.html

**Comment by jennybc** [comment]
I see the same problems when I check workflowr locally, even with released versions of glue, so I'm going to assume that glue is not the problem 😅

**Comment by jdblischak** [comment]
@jennybc Thanks! You're correct that the new version of glue is not the problem. The problem was a new warning introduced in [knitr 1.37](https://github.com/yihui/knitr/releases/tag/v1.37), which made `expect_silent()` fail. Fortunately @yihui already fixed it in PR #264

**Comment by jennybc** [comment]
Yes, I had started to suspect this was a coincidence of two releases on one day (glue & knitr). Glad to hear it's already sorted out.

**Comment by jdblischak** [comment]
I actually have a GitHub Actions CRON job that tests workflowr with the devel versions of as many packages as I could find on GitHub, so in theory I should be able to alert you to any potential issues with glue prior to your future  CRAN submissions.

In this case, it detected the issue with knitr 2 months ago. Unfortunately my inbox is such a mess that I missed the email notifications

https://github.com/workflowr/workflowr-pkg-tests/runs/3857338633?check_suite_focus=true#step:10:53

**Comment by yihui** [comment]
@jdblischak That's amazing. I really appreciate this effort!

**Comment by jennybc** [comment]
Yeah, very interesting to see what you've rigged up in https://github.com/workflowr/workflowr-pkg-tests 👍

**Comment by jdblischak** [comment]
Thanks to you both for the positive feedback and encouragement!
