### ISSUE TITLE
Function similar to pkgdown::deploy_to_branch()

### ISSUE THREAD

**Issue by JSchoenbachler** [workflowr/workflowr#266]
Before posting your issue, please search the existing issues (both "open" and "closed") to check that a similar feature has not already been requested.

1. Describe the suggested feature.
a. A function that operates similarly to `pkgdown::deploy_to_branch()`.
b. This function would essentially just run `wflow_build()`, commit, and push the whole `./docs` directory to another branch (`gh-pages` by default would be nice).
c. Also make it non-password required friendly, if possible (like the aforementioned function). Would be useful for automated workflows (ex.- GH Actions)
d. See reference- https://pkgdown.r-lib.org/reference/deploy_to_branch.html

2. Describe why you think this feature is needed.
a. It would make deployment of workflowr projects to dedicated site branches easier.
b. For example, I currently have analysis repositories that use GitHub actions to generate a workflowr site and deploy to a `gh-pages` branch. This would reduce the logic and make it cleaner if there were a single function.
c. See below GitHub Actions workflow steps to see what I do now vs. what I would like the function to do-
Current Code (This currently pushes contents of whole repository rather than simply the docs folder):
```
    - name: Configure git
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash

    - name: Build and publish
      run: |
        install.packages("workflowr", repos = "http://cran.us.r-project.org")
        workflowr::wflow_git_config()
        workflowr::wflow_build()
        fileNames = paste0("analysis/", list.files("analysis")[grepl("*.Rmd", list.files("analysis"))])
        workflowr::wflow_publish(republish = TRUE)
        # workflowr::wflow_git_push(branch = "gh-pages", username = "GitHubActions")
      shell: Rscript {0}

    - name: Commit to "gh-pages"
      run: |
        git add ./
        git commit -m "Updated workflowr site via GitHub Actions"
        git push -f origin master:gh-pages
      shell: bash
```
Ideal future implementation:
```
    - name: Configure git
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
      shell: bash

    - name: Build and publish
      run: |
        install.packages("workflowr", repos = "http://cran.us.r-project.org")
        workflowr::wflow_git_config()
        workflowr::wflow_deploy_to_branch()
      shell: Rscript {0}
```

3. Tell us the version of workflowr you are using. Run `packageVersion("workflowr")` in R or RStudio, and copy & paste the output here.
a. 1.7.0

**Comment by jdblischak** [comment]
@JSchoenbachler Thanks for opening the issue and sharing your nice GitHub Actions example code!

> a. A function that operates similarly to pkgdown::deploy_to_branch().
> d. See reference- https://pkgdown.r-lib.org/reference/deploy_to_branch.html

`pkgdown::deploy_to_branch()` appears to create an orphan branch. Thus only the website code would be tracked separately in gh-pages. This makes sense to me for a documentation-only website like that created with pkgdown. It makes less sense for me in the context of workflowr. The goal with workflowr is to version both the source code and the results in the same Git history as a data analysis project iterates from beginning to end.

Could you please provide more details on your motivation for using a separate gh-pages branch? Also, do you have a public workflowr project that I can look at? I am worried about the past versions tab. Looking at your recent [coding_sprint_workflowr](https://github.com/hugheylab/coding_sprint_workflowr), I see that some of the past versions work ([example](https://rawcdn.githack.com/hugheylab/coding_sprint_workflowr/5f40f644a4b2ac90d78d57ef0a3277eb33ced658/docs/index.html)), while others 404 ([example](https://rawcdn.githack.com/hugheylab/coding_sprint_workflowr/5f40f644a4b2ac90d78d57ef0a3277eb33ced658/docs/sample_analysis.html)). 

> c. Also make it non-password required friendly, if possible (like the aforementioned function). Would be useful for automated workflows (ex.- GH Actions)

Could you please elaborate on the password aspect? If you're using GitHub Actions, I think you should be able to push directly to the repository using the default `secrets.GITHUB_TOKEN` (https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). If you wanted to use `workflowr::wflow_git_push()`, you could pass this token as the password.

> b. This function would essentially just run wflow_build(), commit, and push the whole ./docs directory to another branch (gh-pages by default would be nice).
> a. It would make deployment of workflowr projects to dedicated site branches easier.
> b. For example, I currently have analysis repositories that use GitHub actions to generate a workflowr site and deploy to a gh-pages branch. This would reduce the logic and make it cleaner if there were a single function.

Are you interested in contributing this function? I have limited time to work on workflowr now, so my primary focus is on maintaining its core features. As I mentioned above, committing `docs` to an orphan branch is not the canonical use case for workflowr, and I worry it may break some of the reproducibility checks. If you have the time and motivation, I'm happy to mentor your contribution.

**Comment by JSchoenbachler** [comment]
@jdblischak (Sorry for the delayed response) Upon thinking about it further, I think what you're saying makes sense about not fitting in thematically.

The original thought for this implementation came about because of our lab's "coding sprint" events we do where we create an analysis repository and use workflowr to expose the analysis each of us performs and github pages to create a site where we can browse the analyses together. (See https://github.com/hugheylab/coding_sprint_2021_12 )

I was trying to streamline this process and set up a template repository with GitHub actions workflows that automatically build the analysis and push the site to the gh-pages branch ( https://github.com/hugheylab/coding_sprint_workflowr https://github.com/hugheylab/coding_sprint_workflowr/blob/master/.github/workflows/analysis-workflowr.yaml https://github.com/hugheylab/actions/blob/main/analysis-workflowr/action.yaml ).

I thought a function like this might make it easier, but upon thinking about it more I think I just have a specific use case for this and it might not be worth pursuing at the moment! I'm fine with closing this issue, sorry if I wasted any time!

**Comment by jdblischak** [comment]
> sorry if I wasted any time!

Not at all! It's important for us to learn about how users are using workflowr in practice. I think it's awesome that you are implementing with ways to automate code execution in remote CI jobs.

> push the site to the gh-pages branch

This is the only part of your setup that I still don't understand. You can host a GitHub Pages site from the default branch. There's no requirement to have a separate gh-pages branch for deployment (though this used to be the case years ago). I'd love to better understand your motivation for this technical implementation. I'm also curious if anything breaks with this setup (e.g. links to past versions).

Closing now. Though if you're interested, I'd be happy to share a guest blog post on how you and your lab mates are integrating workflowr and GitHub Actions https://workflowr.io/posts/ Just let me know

**Comment by JSchoenbachler** [comment]
To clarify the use of a `gh-pages` branch, it's pretty much just a way to keep things simple for the other contributors in the repository. I'll use our data analysis sprints as an example, so here is some information on what that entails:

- 1-2 lab members would find a dataset that had potential to spark interesting analysis and discussion (this past December we used a dataset of movies found on various streaming services with information about genre, imdb ratings, rotten tomatoes scores, etc.).
- They would then set up a GitHub repo to host the analysis and GitHub Pages site on the main branch.
- At the beginning of the sprint, they would give a brief run down of the dataset accompanied by a surface level example analysis.
- They'd run the sprint by letting lab members all work on their own analysis for 30-40 minutes before everyone shares and discusses their analyses.

This is a great team exercise, but problems arose with everyone needing to have install, configure, and run functions from workflowr. The primary issue was that once everyone was done with their analyses, we would have to take turns pulling from and then pushing to the repository, but with the additional step of having to build the workflowr site in between pulling and pushing. This took up some unnecessary time we could be instead using for further analysis or discussion.

The use of the action is to automatically build the site and deploy to a separate branch (`gh-pages`) for a few different reasons:
- Contributors no longer had to configure and use workflowr themselves. This was useful for lab members who only used the package during these sprints and might not remember much about the package.
- Contributors no longer had to wait for each other person before them to build the package, they could instead just pull then push and GH Actions would take care of building for them.
- Because I don't really like the idea of the headache accompanying GH Actions pushing to the same branch recursively, the use of a `gh-pages` specific branch just made it cleaner.
- If the github pages site is tied to another branch and build from actions workflows, we can begin discussing the analyses in order of who first pushed to avoid any problems with the pages site not being published immediately.

Does that clear things up? It just makes our process steps easier to follow for contributors and keeps things cleanly separated.

It's the same thought process that goes into generating our package websites using pkgdown, the contributors to the repository don't have to worry about running pkgdown themselves, and we keep the site hosted on another branch just to keep things clean and separate.

Regarding the guest blog post, I'd be more than happy for you to do that! Let me know if you need anything from me, my PI, or other lab members!
