### ISSUE TITLE
Bitbucket Integration

### ISSUE THREAD

**Issue by thedownlohd** [workflowr/workflowr#269]
Hi there, 

Is there any expectation of integration with bitbucket at any point in the not-too-distant future?

thanks!

**Comment by jdblischak** [comment]
Hi @thedownlohd!

> Is there any expectation of integration with bitbucket at any point in the not-too-distant future?

I doubt it. Though this isn't for me to decide. Workflowr relies on the free per-repository site hosting provided by either [GitHub Pages](https://pages.github.com/) or [GitLab Pages](https://docs.gitlab.com/ee/user/project/pages/). Bitbucket does not provide such a service. Instead, Bitbucket only provides hosting for a single website per account. From their [docs](https://support.atlassian.com/bitbucket-cloud/docs/publishing-a-website-on-bitbucket-cloud/) (emphasis mine):

> To publish a static website on Bitbucket Cloud, you combine your workspace ID with the bitbucket.io domain suffix as your repository name. Your workspace ID must be acceptable by DNS standards. Each workspace can have **only one site** hosted on bitbucket.io.

So if one day Bitbucket offered per-repo site hosting, I'd be happy to add better Bitbucket support to workflowr. Until then, using Bitbucket will be awkward. Some ideas would be:

1. Have each workflowr project in separate repos, but then copy or symlink the website (`docs`) to your single workspace ID repo that has hosting
2. Host your static site using a different service. The website in `docs` is a self-contained static website, so you can copy it to any web server without modifications. The vignette [Alternative strategies for deploying workflowr websites
](https://workflowr.github.io/workflowr/articles/wflow-08-deploy.html) has some alternatives. Or maybe a system administrator at your company could help you deploy it internally
3. If you're heavily invested in the Atlassian stack, maybe they could help you setup deploying your website to Confluence

I apologize I can't be more helpful. It's always frustrated me that workflowr can't be used easily with Bitbucket. I don't understand why Atlassian wouldn't be motivated to match this useful feature that is available from their competitors.
