### ISSUE TITLE
"Past versions of figure" table not working on Windows

### ISSUE THREAD

**Issue by warmdev** [workflowr/workflowr#274]
"Past versions of figure" table is not showing when building a workflowr project on Windows, however it shows correctly on MacOS. After debugging, it appears to be an issue with relative path and git2r::commits function (https://github.com/ropensci/git2r/issues/394). There was a commit on this repo (https://github.com/workflowr/workflowr/commit/631a801fe973e00f7e690716643831bb94fc314f) that fixed the same issue for the file table, by passing absolute path to `get_versions_df` function. But for figures, relative paths are still passed to `get_versions_df`. 

It appears that the issue can be fixed by switching line 237 and 239 in https://github.com/workflowr/workflowr/blob/main/R/report.R

Another related issue is that the url in the figure versions table does not use the `github` option in `_workflowr.yml`. This is already noted in the comments in https://github.com/workflowr/workflowr/blob/main/R/wflow_html.R line 214

**Comment by warmdev** [comment]
On a related note, I would suggest to put commit messages also to the "past versions of figure" table. That makes it easier to find and understand the context of a past version of the figure.

**Comment by jdblischak** [comment]
@warmdev Thanks for the thorough bug report! I confirmed that the bug exists on Windows but not Linux.

I can't get to this right away, and you clearly understand the issue thoroughly. Would you like to submit a PR modeled after 631a801fe973e00f7e690716643831bb94fc314f to fix this? [`CONTRIBUTING.md`](https://github.com/workflowr/workflowr/blob/main/CONTRIBUTING.md) contains some guidance, and I'm of course happy to advise you on the process.
