### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by stephens999** [workflowr/workflowr#28]
I'm wondering what the minimal useful support might be for allowing dependency of ones
workflowr project on other repos (one's own repos that are stored locally?
or maybe github repos?).

Would it be useful to be able to specify that your project "depends" 
on code in another git repo? Then workflowr could embed 
that repo's commit hash in the boilerplate? Of course that could get complex if 
we are going to worry about the 
other repo has uncommitted changes...

A specific scenario of interest is that we have an R package under development in one repo,
and we have another workflowr repo where we are investigating how the package is behaving on
simulations etc. How should we manage that dependency? Is it enough that
the version of the in-development package is included in the sessionInfo()? or would
we rather have the commit hash of the package embedded? or other ideas...?
I think this is the kind of thing that may come up frequently for us in practice.

**Comment by pcarbo** [comment]
For keeping track of software/source code dependencies, I would break it down into three cases:

1. There is a consistent version number associated with the software.

2. There is not a version number associated with the software, but it is from a git repo (e.g., github, gitlab).

3. There is not a version number, and it is not from a git repo.

For Case 1, `sessionInfo()` will generally be a convenient option for recording dependencies of R packages used in a script/notebook. 

For software other than R packages, there are some conventions for extracting version numbers from programs and libraries (e.g., with the `--version` flag, and the `ldd` command for libraries), but I don't immediately see a way of introducing an analog to `sessionInfo()`.

For Case 2, `devtools::session_info()` provides more info, including the SHA1 id when it is installed using `install_github()`, e.g.,

```
Packages -----------------------------------------------------------------------
 package       * version date       source
 rmarkdown     * 1.3     2016-12-21 CRAN (R 3.3.2)
 rworkflowr    * 0.4.0   2017-03-21 Github (jdblischak/workflowr@c3c69ed)
```

For non-R-packages, perhaps `workflowr` could provide a function for extracting the relevant info (e.g., SHA1) given a file path (or URL?) to github repo, or file (e.g., script, executable) within a github repo. That would make it easier for the user to record the dependency info.

For Case 3, there isn't much that can be done. I think this falls outside "Best Practice", so I think it is reasonable to not provide a solution to this case. The only exception to this is if a URL + modification date were to be provided. For example, if you are using files downloaded from the 1000 Genomes FTP site, this would be a workable (if fragile) approach.

**Comment by pcarbo** [comment]
Matthew's question made me recall Apache's software configuration and project management tool [Maven](https://maven.apache.org). Obviously, Maven goes way beyond the scope of what you are trying to accomplish with **workflowr**, but, actually, if you try to see past the technical language, there is a good amount of overlap. I think it would be worth skimming some materials (e.g., [this book](http://books.google.com/books?id=cBvZ4s72Z0gC)---start with p. 6, and p. 150 for a figure illustrating the project structure) to see if there are any ideas/concepts worth borrowing.

**Comment by jdblischak** [comment]
To start, I am going to focus on the more limited challenge of recording the state of another repo as described by Matthew below:

> A specific scenario of interest is that we have an R package under development in one repo,
and we have another workflowr repo where we are investigating how the package is behaving on
simulations etc. How should we manage that dependency? Is it enough that
the version of the in-development package is included in the sessionInfo()? or would
we rather have the commit hash of the package embedded? or other ideas...?
I think this is the kind of thing that may come up frequently for us in practice.

Some ideas. First, for very tight integration between the R package under development and the Rmd files testing its functionality, future projects could integrate workflowr directory into the same repo as the R package. For them to co-exist, the workflowr directories can be added to `.Rbuildignore`. I document this in [this section in the migrating vignette](https://jdblischak.github.io/workflowr/articles/migrating.html#scenario-i-have-an-r-package). However, this still isn't fool proof. The user would be responsible for re-building the package before building and committing the workflowr files.

A second option is to manually add the Git SHA1 from the repository being tested to the workflowr Rmd file. Something like the following could be added to `chunks.R`:

```
# ---- code-version-other-repo ----
# Insert the code version (Git commit SHA1) of other repo

# Relative path from workflowr analysis/ to other repo
p <- "../../other"
if(requireNamespace("git2r", quietly = TRUE)) {
  if(git2r::in_repository(p)) {
    r <- git2r::repository(p)
    code_version <- substr(git2r::commits(r)[[1]]@sha, 1, 7)
  } else {
    code_version <- "Unavailable. Initialize Git repository to enable."
  }
} else {
  code_version <- "Unavailable. Install git2r package to enable."
}
cat(sprintf("**Code version of other repo:** %s", code_version))
suppressWarnings(rm(code_version, p, r))
```

Then any Rmd file that tests the performance of the software in the other repo could have the following chunk inserted:

    
    ```{r code-version-other-repo, echo=FALSE, results='asis'}
    ```

This approach also requires the user to be organized. Once the user is happy with the test result, they must first commit the changes in the other repo before running the workflowr commands.

Both of these approaches could be currently implemented, but workflowr doesn't actually offer any safety mechanisms. Offering additional safety mechanisms for software outside of the `analysis` directory would be a big increase in the current scope of workflowr. workflowr's main focus is enabling transparency (or [inspectability](http://ivory.idyll.org/blog/2017-pof-software-archivability.html)) of those crucial decisions made during the last stages of a data analysis (or method prototyping). For example, it makes no checks that the data files in `data` or `output` were created by the latest versions of the software that was used to create them. Trying to guess the status of an independent Git repository seems very tricky. For example, maybe the external Git repository has some changes to tracked files, but they are just documentation files and don't need to be committed. Or maybe the external Git repository is up-to-date, but the user forgot to build and install the latest version, so the workflowr Rmd ends up running an out-dated executable (or loading the out-dated R package) even though the latest SHA1 is inserted into the document.

**Comment by pcarbo** [comment]
John, overall that sounds good to me. What you are describing sounds more general, and doesn't seem like it is particular to R packages; that is, it could work for any git repo (e.g., a repo containing some data that you are using). Am I correct?

**Comment by jdblischak** [comment]
Yes, I was thinking of a general solution for any Git repo. This is where fine-scale changes would be made (e.g. if I tweak this function, do I obtain the results faster?). If the goal is to test software that already has different releases, these could be more easily captured with `sessionInfo()` at the bottom, putting `packageVersion("<name of package being tested>")` at the top of the page to make it more prominent. If the software is not an R package, the following could be added `system(<insert name of software> --version)`.

**Comment by pcarbo** [comment]
Although you wouldn't be able to put it the "session info" at the very top of the page because you would have to first load the packages with `library()` commands.

Also, it is preferrable to have a single command that would print info for all dependencies, rather than having to type a command for each dependency. Perhaps this could build off of `devtools::session_info()`?

**Comment by jdblischak** [comment]
> Although you wouldn't be able to put it the "session info" at the very top of the page because you would have to first load the packages with library() commands.

Agreed. The user would want to use `packageVersion` to display the version at the top.

> Also, it is preferrable to have a single command that would print info for all dependencies, rather than having to type a command for each dependency. Perhaps this could build off of devtools::session_info()?

I don't understand the enhancement. `sessionInfo` (or `devtools::session_info()`) is a single command to print all dependencies.

If the goal is to print the package version of a few packages that are being specifically tested at the top of the page before they are loaded, I don't think it is unreasonable to have the user run `packageVersion` a few times, e.g.:

```
I am testing how package A interacts with package B.

A version: `r packageVersion("A")`

B version: `r packageVersion("B")`
```

**Comment by pcarbo** [comment]
> I don't think it is unreasonable to have the user run `packageVersion` a few times.

Agreed.

> I don't understand the enhancement.

I was only thinking about a single command that could list dependencies for all packages, other github repos that are not packages, non-R libraries, and executables (e.g., `software --version`). It would take a list of all the software/libraries/packages you are using.

**Comment by stephens999** [comment]
my current thought is that for the specific instance I mentioned
(development of an R package) I'm inclined, for my own workflow,
to just get in the habit of changing the version number at each (relevant)
commit, and use the package version in sessioninfo as a way to keep track
of what package version was used. It seems like a reasonable approach
and workflowr can already deal with this...

Matthew

On Tue, Mar 28, 2017 at 11:22 AM, Peter Carbonetto <notifications@github.com

**Comment by jdblischak** [comment]
OK. And the nice thing about always updating the version number is that you know that not only did you commit the change, but that you also installed it.

**Comment by stephens999** [comment]
Exactly!

**Comment by jdblischak** [comment]
I think this has been resolved. To summarize, for tight integration of an R package in development and a workflowr site that uses this new package, the recommended options are:

1. Tick the package version number whenever a substantial change has been made. Then it will be displayed by `sessionInfo()` (which also confirms that this version of the package was installed and used)
2. Include the package and the workflowr site in the same Git repository. This will make the "code version" reported by workflowr very accurate for describing the state of the R package, too. However, it doesn't guarantee that the current version of the package was installed and used, so it's best to still bump the version often as described in 1.
