### ISSUE TITLE
Error: in callr subprocess.

### ISSUE THREAD

**Issue by adamZhang-J2018** [workflowr/workflowr#284]
Dear author, 

I am trying to use workflowr to manage my project. I already generated some html files with "wflow_build". When I applied to a similar Rmd file, it show "Error: in callr subprocess." and no anything else info about the error cause.  If you can give me some clues about the error, that would be greatly appreciated.

Jigang

**Comment by jdblischak** [comment]
Hi Jigang: Could you please run the following commands below and then copy-paste the full output? You'll need to replace `"analysis/test.Rmd"` with the name of your problematic Rmd file. The first command is what you have already done, but I'd like to see the full output, which should provide clues as to the source of the error. The second executes the code in the current R session, so it should be easier to determine the actual error.

```R
wflow_build("analysis/test.Rmd")
wflow_build("analysis/test.Rmd", local = TRUE)
```

**Comment by adamZhang-J2018** [comment]
Hi  @jdblischak 
 Thanks a lot for your response! I found the problem could be that one code ran out of memory. I will look into it. Thanks again!
Jigang

**Comment by jdblischak** [comment]
Thanks Jigang. I'll close this now, but please feel free to re-open and copy-paste the error messages if you need troubleshooting assistance
