### ISSUE TITLE
Not able to publish website

### ISSUE THREAD

**Issue by william-denault** [workflowr/workflowr#290]
Hello I am trying to publish a workflowr website:

I have followed your tutorial:
When running

```

 wflow_use_github("william-denault")

Enter your choice (1 or 2): 1
You chose option 1: have workflowr attempt to create repo
Requesting authorization for workflowr app to access GitHub account william-denault
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Creating repository GTEX_analysis_Fsusie
Request failed [422]. Retrying in 1 seconds...
Request failed [422]. Retrying in 1.2 seconds...
Error in create_gh_repo(account, repository, account_is_organization = account_is_organization) : 
  Unprocessable Entity (WebDAV; RFC 4918) (HTTP 422).
```

I dont understand this message given that when send on the browser I get

`Authentication complete. Please close this page and return to R.`

**Comment by pcarbo** [comment]
@william-denault I don't think that option 1 will work for you because you the repository already exists.

Are you trying to do this on the RCC cluster or on your laptop? Are you already able to push and pull github repositories? If so, you might be able to skip this step. Happy to walk you though this in person.

**Comment by william-denault** [comment]
I am doing that from my laptop.

I think it would be better to speak in personn

**Comment by jdblischak** [comment]
Has this been resolved?

**Comment by pcarbo** [comment]
Yes! Thanks for the reminder. I'll close the issue.

**Comment by pcarbo** [comment]
@jdblischak Just to close the loop, the short story is that William was able to push/pull the repo through GitHub Desktop, which seems to be working for him.
