### ISSUE TITLE
Is it possible to add the "copy button" to the code?

### ISSUE THREAD

**Issue by tkcaccia** [workflowr/workflowr#292]
I would like to have a copy button in the top right of the code section.
Like the same way the Rm file of github has.

Is it possible?

**Comment by jdblischak** [comment]
Unfortunately it doesn't appear easy to add.

`workflowr::wflow_html()` extends `rmarkdown::html_document()`, but the latter doesn't support the code copy button as one of its [features](https://bookdown.org/yihui/rmarkdown/html-document.html).

It's possible to use features from other output functions like `bookdown::html_document2()` by updating your `_site.yml` file. For example, the setup below allows you to use the cross-referencing features from {bookdown} in your {workflowr} website (https://github.com/workflowr/workflowr/issues/210):

```yaml
output:
  bookdown::html_document2:
    base_format: workflowr::wflow_html
```

Unfortunately `bookdown::html_document2()` also does not support the code copy button. Supposedly `bookdown::gitbook()` does, but when I tried it, it was too incompatible with `wflow_html()` (removed all the {workflowr} features, and also didn't have the code copy button anyways).

There are some other hacks available, for example using the package [{klippy}](https://rlesur.github.io/klippy/). Here are some discussions I found from a quick search:

https://stackoverflow.com/questions/73138448/does-the-copy-code-to-clipboard-option-exist-in-r-markdown
https://forum.posit.co/t/copy-to-clipboard-buttons-for-code-blocks/45367

Unless this option is implemented upstream in {rmarkdown}, it can't be easily supported in {workflowr}. I did a quick search of the Issues at https://github.com/rstudio/rmarkdown/ and couldn't find one about the code copy button, so I'd encourage you to open an Issue there.
