### ISSUE TITLE
Proposal to remove hardcoding of `analysis/` and `docs/` subdirectories

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#31]
Currently I have hard-coded the directory containing the R Markdown files to be `analysis/` and the directory containing the website files to be `docs/`. These are good defaults, but are restrictive.

To remove this requirement, I could update workflowr to automatically search the project directory for the `_site.yml` file. This would be assigned as the "analysis" directory. Then the function would read `_site.yml` to determine the "docs/" directory.

The above would be straightforward to implement. The main downside I can think of at the moment is that when a user changes the name of the "analysis" directory, the current setting would require re-building the entire website (because the renamed Rmd files would be found in the Git log before the corresponding HTML files). However, I think this is reasonable (and also it's not bad to occasionally make sure the entire site is reproducible).

@pcarbo @stephens999 Thoughts on this proposal?

**Comment by pcarbo** [comment]
A few thoughts:

+ What would you call this setting? `source_files_dir`?

+ Would you add these options to `wflow_start()`, with defaults?

+ Have you thought about having an `wflow_options()` command that would allow the user to change some of the more important settings in R? For example, if I run `wflow_options(source_files_dir = "notebooks")`, it could (1) modify the `_site.yml`, and (2) run `git mv ...`, and (3) anything else that needs to be adjusted.

+ More generally, what about `wflow_options()` that reads and writes to `_site.yml`? (That way, only expert users would directly modify `_site.yml`.)

+ I wouldn't worry so much about having to re-build the website. I don't think this setting would be modified very often, so should be only a minor inconvenience.

**Comment by stephens999** [comment]
i agree that it is potentially useful, and I'm not that worried about
having to rebuild website.... it will make people think if it is really
worth
renaming!

Matthew

On Tue, Mar 28, 2017 at 11:17 AM, Peter Carbonetto <notifications@github.com

**Comment by jdblischak** [comment]
>  What would you call this setting? source_files_dir?

I was thinking of calling it `analysis_dir` because in the documentation I refer to it as the analysis subdirectory. I assume that novice users are less likely to have encountered the idea of a "source file".

And I would call the website directory `output_dir` to match the variable name used by rmarkdown.

> Would you add these options to wflow_start(), with defaults?

I hadn't considered that, but yes, certainly a possibility. I had mainly been thinking of adding these to the other workflowr commands (e.g. `wflow_build`, so that when a function calls it internally, it doesn't have to re-do the search).

>  Have you thought about having an wflow_options() command that would allow the user to change some of the more important settings in R? For example, if I run wflow_options(source_files_dir = "notebooks"), it could (1) modify the _site.yml, and (2) run git mv ..., and (3) anything else that needs to be adjusted.

I'm not enthusiastic about this proposal. My reasons:

1. Specifying the analysis directory in `_site.yml` would not help the workflowr functions because `_site.yml` is already in the analysis directory.
1. Part of my motivation for developing a dynamic option that automatically detects the correct directories was to avoid a workflowr-specific config file or workflowr-specific R options (because I think that would add a lot of extra complexity).
1. I try to avoid large changes to Git (like a `git mv` of an entire directory), especially since I think this could be unexpected behavior to the user. I think it would be safer to allow the user to experiment with changing the name(s) of the directories, and then they can manually commit the files at the command line or with `wflow_commit`. The goal of this proposal is to give flexibility to power users. For those less comfortable with Git and rmakdown, they should probably just continue to use the default names.

> More generally, what about wflow_options() that reads and writes to _site.yml? (That way, only expert users would directly modify _site.yml.)

I am skeptical that this would be worth the effort. In the amount of time the user would have to spend reading the documentation of my custom function, they could read the entire [rmarkdown documentation on creating websites](http://rmarkdown.rstudio.com/rmarkdown_websites.html). In other words, I think learning to configure the `wflow_options` would require the same expertise as learning to directly edit the `_site.yml` file.

> pc: I wouldn't worry so much about having to re-build the website. I don't think this setting would be modified very often, so should be only a minor inconvenience.
> ms: i agree that it is potentially useful, and I'm not that worried about having to rebuild website.... it will make people think if it is really worth renaming!

OK. Great.

**Comment by pcarbo** [comment]
Sounds good. In summary: don't add R interfaces for customization because (1) a lot of work to implement, (2) would require more documentation, and (3) we will assume (expert) user can figure out how to customize things manually.

**Comment by jdblischak** [comment]
> Sounds good. In summary: don't add R interfaces for customization because (1) a lot of work to implement, (2) would require more documentation, and (3) we will assume (expert) user can figure out how to customize things manually.

Yes! I'll only add that the most common customization options can now be achieved by **non**-experts with minimal effort due to recent updates to the rmarkdown package. As an example, for my singleCellSeq site, I had to manually locate and edit the raw HTML files to customize the navigation bar. Now there is a dedicated configuration file (`_config.yml`) that abstracts away this complexity and is also well documented on their website. That's why I think it will be most effective to point users to the relevant documentation instead of building an API to the configuration file.

**Comment by jdblischak** [comment]
[workflowr 0.5.0](https://github.com/jdblischak/workflowr/releases/tag/v0.5.0) supports renaming of`analysis/` and `docs/`.

However, the user must do the renaming manually (i.e. with `git mv`). It is not an option of `wflow_start()`. I think this makes sense for now. Renaming the directories is a more advanced customization, so I'll leave that possibility for more advanced users. If there is demand for it, I can always add this option to `wflow_start()` in the future.
