### ISSUE TITLE
Option to only build files listed in index.Rmd

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#38]
One way to know for sure that an analysis file is ready to be built and committed as part of the website is that it is listed in index.Rmd. Thus one convenient option would be to only build these files. The main con is that this is yet another potential argument that affects which files to build and commit, which risks confusing users.

Please add any additional thoughts to this Issue.

**Comment by pcarbo** [comment]
I could see this as being a very useful feature, and potentially could be the default behaviour for `workflowr`. But I agree we should hold off on this feature for now until the other options have been fully implemented.

**Comment by jdblischak** [comment]
No users have expressed interest in this feature, so at the moment I don't think the added complication is worth the potential convenience.
