### ISSUE TITLE
Support Jupyter notebooks

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#39]
In theory it should be possible to add support for Jupyter notebooks to workflowr. Here's what would need to be done:

* Add a build option that would run `jupyter nbnconvert` on the `.ipynb` files. May be able to use [nbconvertR](https://cran.r-project.org/web/packages/nbconvertR/index.html), though it requires a meta file as input, not the actual notebook file.

* Need to [customize the template](http://nbconvert.readthedocs.io/en/latest/customizing.html) so that it uses the same CSS as the R Markdown files.

* Need to investigate how Jupyter notebooks save figure files.

**Comment by jdblischak** [comment]
Some notes after more research:

The command would be something like the following:

```
jupyter nbconvert --to html --template basic --execute --stdout analysis/file.ipynb > docs/file.html
```

The `--execute` will re-run all the cells to make sure the results in the HTML are created with the current state of the Git repo. The default template options are "full" and "basic", but I should be able to customize them like any Jinja template ([nbconvert docs](https://nbconvert.readthedocs.io/en/latest/customizing.html)).

Another thing to keep in mind is that the API is not stable as of version 4.2.1:

```
$ jupyter --version
4.2.1
$ jupyter nbconvert -h | grep WARNING
WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.
```

I took another quick look at [nbconvertR](https://cran.r-project.org/web/packages/nbconvertR/index.html) and realized it has a very specific use case: "nbconvertR: Vignette Engine Wrapping IPython Notebooks". Since its use case is as a vignette builder for packages, I may be better off writing my own wrapper to reduce the dependencies (especially since I would already have to write code to create the meta file it requires as input).

**Comment by pcarbo** [comment]
> Since its use case is as a vignette builder for packages, I may be better off 
> writing my own wrapper to reduce the dependencies.

@jdblischak I agree.

**Comment by jdblischak** [comment]
I've decided to not add support for Jupyter notebooks for the following reasons:

1. This would substantially increase the scope of workflowr. It would require a duplicated set of functions to internally process the notebooks, making the code base much harder to maintain. Also, it hard for me to imagine that many users will want to write their analyses in a Jupyter notebook but then return to the R console to run the workflowr functions.

1. With the reticulate package and the improved support for Python code chunks in rmarkdown, writing Python code using R Markdown files is now more viable.
