### ISSUE TITLE
Ideas for improving the getting-started vignette

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#4]
To do:

- [x] Note the location of the figures
- [x] Explain the difference between the special directories `analysis/` and `docs/` and the other directories
- [x] Add URLs to the vignette HTML files (see [here](https://stackoverflow.com/questions/34946219/linking-r-package-vignettes)).
- [x] Before "Start the project", explain what *is* a project (the central data structure in the *workflowr* package).
- [x] Suggest calling it "myproject" instead of "new-project".

**Comment by pcarbo** [comment]
I added a few more suggestions for improvement.
