### ISSUE TITLE
a single function that combines `wflow_build` and `wflow_view`

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#41]
Hi John @jdblischak 

Is there any function/command available in `workflowr` package that combines `wflow_build` and `wflow_view`?

This feature is similar to the "knit" button: I write a `Rmd` file, click the button and then I see the pdf or html output automatically.

BTW. I update `workflowr` to the latest release and do not find any issue. Thanks for the update.

**Comment by jdblischak** [comment]
> Is there any function/command available in workflowr package that combines wflow_build and wflow_view?
>
> This feature is similar to the "knit" button: I write a Rmd file, click the button and then I see the pdf or html output automatically.

Good point. That is something I want to implement, but I don't think it requires a new function. My plan was to add an argument `view = interactive()` to `wflow_build()`. Thus if `wflow_build()` is run interactively in the console, the default will be to automatically view the site. This default behavior was inspired by a similar function `pkgdown::build_site()`, which has the argument `preview = interactive()` ([source](https://github.com/hadley/pkgdown/blob/72c4c5a4ab31cd3084c6439f14ccbe1ca018ce67/R/build.r#L156)).

Some questions for you (and other users):

1. Do you think this is a good default behavior for `wflow_build()`?
2. What should the default be for `wflow_publish()`? Should it also open the site in the browser by default, or should it only be optional?
3. Which file should be automatically opened after building? `wflow_view()` has options to open `index.html` or a specific file(s).

> BTW. I update workflowr to the latest release and do not find any issue. Thanks for the update.

Good to know! Thanks!

**Comment by pcarbo** [comment]
@jdblischak IMO, the default behaviour should be similar to the knit button in RStudio. In the future, perhaps you could have a function such as `wflow_opts` that modifies these defaults in a convenient way (similar to changing RStudio preferences).

**Comment by jdblischak** [comment]
> the default behaviour should be similar to the knit button in RStudio

@pcarbo The problem is that `wflow_build()` is more complicated than the knit button (and an entire workflowr site is more complicated than a single Rmd file). The knit button in RStudio always builds and then previews one file. `wflow_build()` may build 0, 1, or 1+ files (and these files are part of a larger website). Thus we need to decide on defaults for all these scenarios:

1. When 0 files are built, `wflow_build()` could A) do nothing, B) open `index.hmtl`, or C) open the most recently modified HTML file (i.e. pass `recent = TRUE` to `wflow_view()`)

2. When 1 file is built, `wflow_build()` could A) open this file or B) open `index.html`.

3. When 1+ files are built, `wflow_build()` could A) open all the files, B) open `index.html`, C) open the first file, D) open the last file, or E) another possibility.

As a reference, `pkgdown::build_site()` always opens `index.html`.

**Comment by pcarbo** [comment]
Good point. So maybe either similar to RStudio `knit` or `pkgdown` whenever most appropriate? The "default" could be different depending on the other input arguments.

**Comment by xiangzhu** [comment]
@jdblischak  Good to know that the requested feature is almost available!

Below are my replies to your questions, which are purely based on **my own experiences** of using `workflowr`. It may be useful to get feedback from other users.

> 1. Do you think this is a good default behavior for wflow_build()?

Yes. Indeed I am typing `wflow_build()` + `wflow_view()` most of time, which is why I open this ticket to ask about alternatives.

> 2. What should the default be for wflow_publish()? Should it also open the site in the browser by default, or should it only be optional?

Not sure. When I reach the step of using `wflow_publish()`, I am pretty ok with new web pages. I don't need to look at the output again.

> 3. Which file should be automatically opened after building? wflow_view() has options to open index.html or a specific file(s).

I prefer `index.html`. Most of time I make changes in multiple pages, so it is easier to get `index.html` first, where I list all the links to other pages. 

If I only make changes in a single page, I usually click the `knit` button and it will show me the output for the changed page automatically.

**Comment by jdblischak** [comment]
Thanks for the feedback, @xiangzhu! Here is what I am currently planning on implementing:

1. When 0 files are built, `wflow_build()` will do nothing.

1. When 1 file is built, `wflow_build()` will open that file.

1. When 1+ files are built, `wflow_build()` will open `index.html`.

**Comment by pcarbo** [comment]
@jdblischak Sounds good to me.

**Comment by pcarbo** [comment]
@jdblischak Would `wflow_publish()` do the same thing?

**Comment by jdblischak** [comment]
> Would wflow_publish() do the same thing?

Thanks for the reminder, @pcarbo. I had meant to include these details.

In short, no. By default `wflow_publish()` will have `view = FALSE`. If it is changed to `view = TRUE`, this will be passed to `wflow_build()`, and then have the same behavior as described above.

**Comment by pcarbo** [comment]
That sounds fine.

**Comment by xiangzhu** [comment]
@jdblischak  Thanks! I am looking forward to this new feature!

**Comment by jdblischak** [comment]
@xiangzhu This feature has been implemented in [v0.7.0](https://github.com/jdblischak/workflowr/releases/tag/v0.7.0). See the [release notes](https://jdblischak.github.io/workflowr/news/index.html#workflowr-0-7-0) for other changes. You can upgrade to this latest release by running the following:

```
devtools::install_github("jdblischak/workflowr", build_vignettes = TRUE)
```

Please try it out and let me know if you have any issues or suggestions for improvement.

**Comment by xiangzhu** [comment]
@jdblischak  Thanks for the update! I just try this new feature a few times, and it is working.

**Comment by jdblischak** [comment]
For any future readers, note this behavior has now slightly changed. As of [v0.11.0](https://github.com/jdblischak/workflowr/releases/tag/v0.11.0), `wflow_publish()` now behaves the same as `wflow_build()`, i.e. it opens the website for viewing if run in an interactive R session.
