### ISSUE TITLE
wflow_rename

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#46]
Implement function `wflow_rename` to rename files and/or folders in a workflowr project.

Options for function may include:

+ Automatically run `wflow_publish` on just the renamed files.

+ Update links in existing R Markdown and HTML files.

**Comment by jdblischak** [comment]
@pcarbo [`wflow_rename()`](https://jdblischak.github.io/workflowr/reference/wflow_rename.html) has been added in the 1.2.0 release.

> * Automatically run `wflow_publish` on just the renamed files.
> * Update links in existing R Markdown and HTML files.

It doesn't currently implement these features.
