### ISSUE TITLE
Give instructions for dependency management with checkpoint and other options

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#52]
workflowr currently does not explcitly support any dependency management system. This flexibility allows users to choose from common options like [checkpoint][], [packrat](https://cran.r-project.org/package=packrat), [conda](https://conda.io/docs/), [docker](https://docs.docker.com/), or others. For less experienced users, it would be useful to include instructions (or at minimum links to instructions) for how to use these tools to manage project dependencies. This documentation could start in the FAQ vignette and potentially migrate to its own separate vignette if there is interest.

* This [paper by Jeffrey Racine](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2916754) describes a strategy for integrating [checkpoint]() with R Markdown files.

[checkpoint]: https://cran.r-project.org/package=checkpoint

**Comment by sdhutchins** [comment]
Any movement on this? I'd love to give packrat a shot with this at least. I think it may be better suited for this package than `conda` or `docker`.

**Comment by jdblischak** [comment]
@sdhutchins No, we haven't written any documentation on how to use packrat (or any other dependency management software) with workflowr. Would you be interested in writing a vignette with advice on how to leverage packrat in a workflowr project?

xref: #128

**Comment by pcarbo** [comment]
@sdhutchins As a practical suggestion, perhaps you could create a simple example demonstrating how you use packrat & workflowr together? (And later you could consider developing this into a  proper vignette.) Thanks for your suggestions and contributions!

**Comment by sdhutchins** [comment]
I can definitely do that @pcarbo just to see if it is "sensible" enough. Currently doing a hackathon this weekend, but early next week, I'll have something. @jdblischak

**Comment by jdblischak** [comment]
Let's close this in favor of #128. I'd prefer to implement at least some basic functionality, and then we can write a vignette on how to use it.
