### ISSUE TITLE
Spacing between sections

### ISSUE THREAD

**Issue by pcarbo** [workflowr/workflowr#57]
This seemingly small issue has bugged me with the rendered HTML: there is no additional spacing between sections (this is in all the templates, not just the readable theme). My fix is to include a `header.html` with an additional CSS instruction. See here:

https://github.com/stephenslab/wflow-divvy/blob/master/analysis/include/header.html
https://github.com/stephenslab/wflow-divvy/blob/master/analysis/_site.yml

Not sure if this deserves to be added to the `workflowr` package, but, IMO, it would be nice to start users off correctly with spacing…

**Comment by jdblischak** [comment]
> Not sure if this deserves to be added to the workflowr package

I do think this makes sense to include in workflowr. It is straightforward to implement, and we may want to include even more CSS customization in the future. Please feel free to add this to the dev branch. The files you'd need to edit are in `inst/infrastructure/analysis`.

**Comment by pcarbo** [comment]
@jdblischak See [commit ec0986a](https://github.com/jdblischak/workflowr/commit/ec0986a7bc27106f602d53407656010ce53bd12f).

IMO, this seems like a standard/default fix we would want for most workflowr sites; I agree that there are potentially lots of customizations that could be made.

**Comment by jdblischak** [comment]
Closing now that this has been merged into master in release 0.8.0.
