### ISSUE TITLE
wflow_build problem *specific to one project*

### ISSUE THREAD

**Issue by johnsonlab** [workflowr/workflowr#67]
Hi there - all but one of my projects is working without incident. For one project, however, I am unable to complete a wflow_build() without the following message:

> wflow_build()
Building redacted.Rmd
Build failed. See log files for full details.
stdout: /tmp/workflowr/redacted.Rmd-2017-09-21-16h-24m-22s-out.txt
stderr: /tmp/workflowr/redacted.Rmd-2017-09-21-16h-24m-22s-err.txt
NA
Error: unused arguments (lib_dir = "site_libs", self_contained = FALSE)

I have also tried to simply knit to .pdf from the command line per your suggestion on closed issue #59. 

The good news: running

render("redacted.Rmd", pdf_document())

worked fine and produced a .pdf from this .Rmd file. 

Embarrassingly, I have been unable to find and open those ouput and error text files mentioned above. Maybe they would help?

Thanks! JJ

**Comment by jdblischak** [comment]
> Error: unused arguments (lib_dir = "site_libs", self_contained = FALSE)

This error is likely coming from the function `pdf_document()`. Did you edit the file `analysis/_site.yml`? I am able to get the same error by replacing `html_document` with `pdf_document` in the `output:` section of `analysis/_site.yml`.

> I have been unable to find and open those ouput and error text files mentioned above. 

To read the log files from R, you could run something like the following:

```
cat(readLines("/tmp/workflowr/redacted.Rmd-2017-09-21-16h-24m-22s-out.txt"), sep = "\n")
cat(readLines("/tmp/workflowr/redacted.Rmd-2017-09-21-16h-24m-22s-err.txt"), sep = "\n")
```

The file containing standard output (ending in `out.txt`) is probably empty in this case.

**Comment by johnsonlab** [comment]
Hi there: 
1) html_document appears to be intact

Here's the contents of analysis/_site.yml 

name: REDACTED
output_dir: "../docs"
include: [".nojekyll"]
exclude: ["include"]
navbar:
  title: REDACTED
  left:
    - text: "Home"
      href: index.html
    - text: "About"
      href: about.html
    - text: "License"
      href: license.html
  right:
    - icon: fa-github
      href: https://github.com/jdblischak/workflowr
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: textmate
    include:
      after_body: include/footer.html

2a) And the output of (great tip thanks!) cat: 

cat(readLines("/tmp/workflowr/REDACTED.Rmd-2017-09-22-10h-03m-32s-err.txt"), sep = "\n")

Error in (function (toc = FALSE, toc_depth = 2, number_sections = FALSE,  : 
  unused arguments (lib_dir = "site_libs", self_contained = FALSE)
Calls: withCallingHandlers ... create_output_format -> do.call -> <Anonymous> -> .handleSimpleError -> h
Execution halted

2b) You're correct, out.txt is empty. 

Noticed that toc = FALSE in the log file but it is true (toc: true) in the output section of _site.yml.   Editing that to false in the analysis/_site.yml  file does not help, unfortunately, and another site of mine that compiles correctly has true in its analysis/_site.yml.  Have also removed a compiled .pdf from docs, no help either. Thanks for your help!!

**Comment by jdblischak** [comment]
OK. We've ruled out problems with `analysis/_site.yml`. Next, could you please post the YAML header (everything between the two `---` lines at the top) for the problem R Markdown file? Also, does `wflow_build()` fail for every file in this wrokflowr project or just this specific one? In other words, can you run `wflow_build("analysis/index.Rmd")`?

**Comment by johnsonlab** [comment]
That's it - At some point I must have done something (compiled to .pdf from R cmd line?) that altered the YAML header of two of my four R Markdown files. I copied the following working output: block:

output:
  html_document: default
  pdf_document:
    citation_package: natbib
  word_document: default

from one of the working files to the non-working files and all compiled individually and as a group with wflow_build().

Thanks VERY much!! JJ

**Comment by jdblischak** [comment]
> At some point I must have done something (compiled to .pdf from R cmd line?) that altered the YAML header of two of my four R Markdown files.

My guess would be the Knit button in RStudio. It will add/rearrange the YAML header depending on which output (HTML, PDF, Word) is selected.

Glad it's working now!

**Comment by pcarbo** [comment]
@jdblischak Would it be possible to check that the YAML header is compatible with workflowr, and report an error if not?

**Comment by jdblischak** [comment]
Good idea, @pcarbo. I opened a new Issue https://github.com/jdblischak/workflowr/issues/68
