### ISSUE TITLE
add option to publish index.html to repository root rather than docs/

### ISSUE THREAD

**Issue by nkicg6** [workflowr/workflowr#71]
Awesome package, thanks for putting it together! This morning I used workflowr to build a website for a reproducible research club at my university. I published on a new github organization site as the organization page. Unfortunately, it seems like github will not let you set the `docs/` directory as the github pages root for organization/personal sites (it only works for project sites). I got around this by copying `index.html` to the repository root, deleting the `readme.md` and adding `docs/` to all the links. 

Do you think it would be useful to have a `wflow_build(as_root=TRUE)` option that would publish as an organization/personal page in this way? I would be happy to work on implementing this feature if you think it would be useful.

**Comment by pcarbo** [comment]
@nkicg6 Would you be able to share with us the link to the Github repository with your setup?

**Comment by nkicg6** [comment]
@pcarbo  Absolutely. Here is the repo https://github.com/UCD-Reproducible-research-clinic/UCD-Reproducible-research-clinic.github.io and here is the github pages site https://ucd-reproducible-research-clinic.github.io/ .We are just getting started but I think workflowr is perfect for this.

**Comment by jdblischak** [comment]
@nkicg6 I'm glad you like workflowr!

You can change the output directory in the file `analysis/_site.yml`. The default is `../docs`. Try changing [this line in your repo](https://github.com/UCD-Reproducible-research-clinic/UCD-Reproducible-research-clinic.github.io/blob/80e100b644a85c56ddbfcffcdb847344cf9102e5/analysis/_site.yml#L2) to instead be `output_dir: ".."`. This will dump the HTML files and figures into the root of the repository.

If this looks good, then you can re-publish the site by running the following:

```
library("workflowr")
wflow_publish("analysis/_site.yml", republish = TRUE)
```

Please let me know if this solution works for your situation.

Also, your research clinic looks awesome! Have you heard of [Software Carpentry](https://software-carpentry.org/)? They're a network of scientists that teach 2-day workshops. Their [lessons](https://software-carpentry.org/lessons/) are online and open source (i.e. you could teach them verbatim or modify them for your purposes). In general they're a great community to engage with for discussing how to improve the coding skills of scientists.

**Comment by pcarbo** [comment]
@jdblischak Related to this: is it possible to have `.Rmd` files in subdirectories of `analysis`? e.g., `analysis/lesson1/pca.Rmd` and then the webpage will be rendered as `docs/lesson1/pca.html`?

**Comment by nkicg6** [comment]
@jdblischak Awesome, thank you for that I should have looked more closely at the yml! I have heard of software carpentry, I learned git at one of their workshops last year, they are an awesome organization. I refer to their lessons a lot and I will definitely get in touch with them more as we expand this club. Thanks again for the help.

**Comment by jdblischak** [comment]
> Related to this: is it possible to have .Rmd files in subdirectories of analysis? e.g., analysis/lesson1/pca.Rmd and then the webpage will be rendered as docs/lesson1/pca.html?

@pcarbo This is an inherent limitation of knitr (and thus rmarkdown). It does not handle nested directory structures well because it has trouble keeping track of the file paths to figures and other resources.

**Comment by jdblischak** [comment]
> Awesome, thank you for that I should have looked more closely at the yml!

@nkicg6 No worries! I'm glad it is working for you now. workflowr is built on top of rmarkdown, so most rmarkdown website features should be compatible with a workflowr project.

http://rmarkdown.rstudio.com/rmarkdown_websites.html

> I have heard of software carpentry, I learned git at one of their workshops last year, they are an awesome organization. I refer to their lessons a lot and I will definitely get in touch with them more as we expand this club. Thanks again for the help.

Great. Keep up the good work!
