### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#77]
Hi John,

When searching for certain usage information and links, I accidentally spot my name and GitHub link in README "Credits" section, but I think my full name is wrong there. It should be "Xiang Zhu" rather than "Xiang Zhou". Thank you!

README: https://github.com/jdblischak/workflowr/blob/master/README.md

**Comment by jdblischak** [comment]
So sorry about this @xiangzhu! It's been corrected.
