### ISSUE TITLE
Publish multiple files with similar names

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#84]
Hi John,

I wonder if there is a smarter way of performing the following task within `workflowr`.

I updated multiple files, with name `week*_review.Rmd`, and I wanted to published all of them once.

I tried the following code, and unsurprisingly, it did not work:

```r
> wflow_publish("analysis/week*_review.Rmd")
Error in wflow_publish("analysis/week*_review.Rmd") : 
  Not all files exist. Check the paths to the files
```

Currently I am using the following code to publish multiple files with similar names once:

```r
> file.list <- paste0("analysis/week",1:8,"_review.Rmd")
> file.list
[1] "analysis/week1_review.Rmd" "analysis/week2_review.Rmd" "analysis/week3_review.Rmd" "analysis/week4_review.Rmd"
[5] "analysis/week5_review.Rmd" "analysis/week6_review.Rmd" "analysis/week7_review.Rmd" "analysis/week8_review.Rmd"
> wflow_publish(files=file.list)
Building analysis/week1_review.Rmd
Building analysis/week2_review.Rmd
Building analysis/week3_review.Rmd
Building analysis/week4_review.Rmd
Building analysis/week5_review.Rmd
Building analysis/week6_review.Rmd
Building analysis/week7_review.Rmd
Building analysis/week8_review.Rmd
Summary from wflow_publish
```

Thanks!

**Comment by pcarbo** [comment]
@xiangzhu You should be able to do something like this: `wflow_publish(Sys.glob("analysis/week*_review.Rmd"))`

@jdblischak It makes me think: it would be cool of the `files` argument behaved like the command-line, e.g., with wildcards. Do you think that would be hard to implement. To forsee any undesirabilities? Most people don't know about `Sys.glob` and I think that would be a cool feature.

**Comment by xiangzhu** [comment]
Thanks Peter! Yes, I did not know `Sys.glob` until you showed me this example.

**Comment by jdblischak** [comment]
> You should be able to do something like this: wflow_publish(Sys.glob("analysis/week*_review.Rmd"))

@xiangzhu I agree with @pcarbo that using globs is the easiest way to select many files with similar names. I often run `wflow_publish(Sys.glob("analysis/*Rmd"))` at the beginning of a project when I know I want to publish the original workflowr R Markdown files.

**Comment by jdblischak** [comment]
> It makes me think: it would be cool of the files argument behaved like the command-line, e.g., with wildcards. Do you think that would be hard to implement. To forsee any undesirabilities? Most people don't know about Sys.glob and I think that would be a cool feature.

@pcarbo I agree this would be convenient. I'm trying to think of downsides. For example, why doesn't R allow globs for functions like `file.exists`? Similar to the workflowr functions, the only input to this function is filenames. Trying to get workflowr to handle filepaths consistently on both Unix-alike and Windows has been a real pain, so I'm worried I'm not thinking of potential disasters.

**Comment by pcarbo** [comment]
@jdblischak I think it would be okay as long as you gave an informative console output explaining what files are being rendered; it would be hard to use wildcards without intending to.

The general principle of making these functions act like the command-line would improve ease-of-use.

**Comment by xiangzhu** [comment]
Thanks again! @jdblischak @pcarbo  I will use `Sys.glob`, and in fact I am happy with this solution!

**Comment by jdblischak** [comment]
@xiangzhu I'm glad that `Sys.glob` solves your immediate need.

@pcarbo I'm going to label this Issue as Enhancement as a placeholder for the proposal of accepting globs as input to the workflowr functions.

**Comment by jdblischak** [comment]
Support for file globbing was added in [0.10.0](https://github.com/jdblischak/workflowr/releases/tag/v0.10.0)
