### ISSUE TITLE
Can't build vignettes during installation on Windows

### ISSUE THREAD

**Issue by jdblischak** [workflowr/workflowr#87]
On Windows, this fails:

```
devtools::install_github("jdblischak/workflowr", build_vignettes = TRUE)
Error: processing vignette 'wflow-01-getting-started.Rmd' failed with diagnostics:
The directory where you have chosen to create a new workflowr directory is already within a Git repository. This is potentially dangerous. If you want to have a workflowr project created within this existing Git repository, re-run wflow_start with `git = FALSE` and then manually commit the new files. The following directory contains the existing .git directory: C:/Users/han
Execution halted
```

I confirmed this still works on Ubuntu, regardless of whether or not the installation is run from inside a Git repo. I'll need to see if I can verify this on Windows. One thing that could be causing a problem is the `.git` is in the user's home directory.

**Comment by pcarbo** [comment]
@jdblischak If you need it, there is a Windows machine in room 407 that you can use to test and debug this error.

**Comment by jdblischak** [comment]
@pcarbo Thanks! Good to know that's available.

**Comment by jdblischak** [comment]
And the temporary fix for the time being is to install workflowr on Windows without building the vignettes locally.

```
devtools::install_github("jdblischak/workflowr")
```

And instead rely solely on the [online vignettes](https://jdblischak.github.io/workflowr/articles/index.html).

**Comment by jdblischak** [comment]
This Issue was fixed by having the user delete the Git repo in their home directory, i.e. `C:/Users/han/.git`. The worry now is if this Git repo was possibly created by workflowr.
