### ISSUE TITLE
Error when creating a project

### ISSUE THREAD

**Issue by f0nzie** [workflowr/workflowr#89]
There is an error when trying to create a project with `workflowr` with:
```
> wflow_start("myproject")
```

This is the error:
```
Error in wflow_start("myproject") : 
  The directory where you have chosen to create a new workflowr directory is already within a Git repository. This is potentially dangerous. If you want to have a workflowr project created within this existing Git repository, re-run wflow_start with `git = FALSE` and then manually commit the new files. The following directory contains the existing .git directory: C:/Users/msfz751
```

This happens in Windows 10, R 3.4.3, RStudio 1.1.383, with a clean directory (no git repo or anything).

Thanks.

**Comment by f0nzie** [comment]
By the way, excellent idea.
In the meantime, I got it working adding `git = FALSE`, and the website was built.

Thank you for such a wonderful work.

**Comment by jdblischak** [comment]
@f0nzie I think this is directly related to the installation issue. A Git repo was created by the vignette in your home directory. Please look for a directory named `C:/Users/msfz751/.git` (if it's not there, then check `C:/Users/msfz751/Documents/.git`). Delete this directory and try `wflow_start()` again. The integration with Git is critical for both the reproducibility features of workflowr and hosting the website online.

> Thank you for such a wonderful work.

Of course! I'm glad you like workflowr. And thank you for taking the time to document the issues you are having.

**Comment by jdblischak** [comment]
I think this problem was solved by the change in https://github.com/jdblischak/workflowr/issues/88#issuecomment-355889202. Please feel free to re-open (or create a new Issue) if you still have problems with `wflow_start()`.
