### ISSUE TITLE
GitHub icon link issue

### ISSUE THREAD

**Issue by f0nzie** [workflowr/workflowr#90]
Hello,
I am not sure if this would be a bug, I am reporting it, just in case. Every time that I press the GitHub icon, it redirects to your repo website.
![image](https://user-images.githubusercontent.com/29108853/33910560-bddb3b86-df54-11e7-8ea3-6c76c89b0412.png)

I found that link doing this is in the `_site.yml` file. See below:
![image](https://user-images.githubusercontent.com/29108853/33910480-80ef1c9c-df54-11e7-87b6-6231492fdb0e.png)

Maybe, that should be entered manually, or automatically, if the package guess the website name from the repo URL that was provided to it during the Git set up.

Thanks.

**Comment by jdblischak** [comment]
@f0nzie Currently this has to be configured manually. Editing the navigation bar via `_site.yml` is described in the section [Customize the navigation bar](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html#customize-the-navigation-bar) of the [Customize your research website](https://jdblischak.github.io/workflowr/articles/wflow-02-customization.html) vignette:

> The navigation bar appears on the top of each page. By default it includes links to index.html (Home), about.html (About), license.html (License), and the workflowr repository (the GitHub icon). This is all specified in analysis/_site.yml. To start, replace the URL to the workflowr GitHub repository with the URL to your GitHub repository.

I agree that it would be nice to automate this when configuring the remote repository (or at the very least send a message to the user suggesting that they edit `_site.yml`).

**Comment by jdblischak** [comment]
@f0nzie Now in workflowr 1.2.0, the functions [`wflow_use_github()`](https://jdblischak.github.io/workflowr/reference/wflow_use_github.html) and [`wflow_use_gitlab()`](https://jdblischak.github.io/workflowr/reference/wflow_use_gitlab.html) will automatically insert the correct link to the source code repository into the navigation bar and commit the change.
