### ISSUE TITLE
Removal of sidebar navigation from certain pages

### ISSUE THREAD

**Issue by pwh124** [workflowr/workflowr#91]
I am currently building a website using workflowr for my research (https://pwh124.github.io/sc-da-parkinsons/)

I have a plethora of different analyses. I currently have it set up so that I have a "links page" for each of these analyses. 

These link pages currently have blank sidebar navigations.

Is there any way that I can remove the sidebar navigation through .Rmd so it can look more like the "About", "Licence", or "Home" pages?

**Comment by pcarbo** [comment]
@pwh124 Very nice workflowr site!

I know of least two ways to get rid of the sidebar:

1. Set `toc: false` in the individual R Markdown file. See [here](https://raw.githubusercontent.com/stephenslab/wflow-divvy/master/analysis/license.Rmd) for an example.

2. Set `toc: false` in the `_site.yml` file, which will remove the sidebar for all webpages.

Does this solve your problem?

**Comment by pwh124** [comment]
@pcarbo That did fix the problem! Thank you for your help!

**Comment by jdblischak** [comment]
Just to reiterate what @pcarbo said: the default defined in `_site.yml` is to include a floating table of contents, and this can be deactivated in the individual Rmd files. If you'd prefer the opposite default, you can edit `_site.yml` to remove the table of contents and then activate it for specific files.

And thanks for sharing your workflowr site @pwh124! I really like the customization you did. Keep up the good work!
