### ISSUE TITLE
Temporarily change font size for better display

### ISSUE THREAD

**Issue by xiangzhu** [workflowr/workflowr#92]
Hi John,

I wonder if it is possible to add the following feature of `bookdown` to `workflowr`:
<img width="287" alt="screen shot 2017-12-21 at 10 08 00 pm" src="https://user-images.githubusercontent.com/5986023/34287547-b210bfac-e69c-11e7-9410-44c04f80773a.png">

Personally I find the changing font size feature (the "smaller A bigger A" sign) pretty handy. I have been using `workflowr` for group meeting/class presentation (it saves me a lot of time in making slides!), and sometimes I found the font size is too small for clear project display. I wish I could click some similar button in `bookdown` and the font size will get bigger temporarily.

I am very happy with the default font size of `workflowr` for work and one-to-one meetings.

Happy Holidays!

**Comment by jdblischak** [comment]
@xiangzhu That is a nice feature, but I think it would be difficult to port over to workflowr. bookdown has an entire [gitbook style](https://bookdown.org/yihui/bookdown/html.html#gitbook-style) that is quite different from the vanilla Bootstrap used by workflowr. I did a quick experiment to see if adding the following to `_site.yml` would work:

```
output:
  bookdown::gitbook:
    lib_dir: site_libs
```

but it didn't.

It's possible that we could extract out just this font aspect to implement in workflowr, but it appears that the Gitbook Javascript files expect to be used together:

https://github.com/rstudio/bookdown/blob/0d3e67c05066c32c8a371f0428f8bf7a7926b13e/R/gitbook.R#L82
https://github.com/GitbookIO/plugin-fontsettings/blob/master/assets/fontsettings.js#L1

I know it's not ideal, but I find changing the zoom on my web browser is usually quite effective. Sorry I can't be more helpful.

**Comment by jdblischak** [comment]
And happy holidays to you, too!

**Comment by xiangzhu** [comment]
No problem. Thanks for your quick reply and explanations!
