### ISSUE TITLE
error: processing vignette 'wflow-01-getting-started.Rmd' failed

### ISSUE THREAD

**Issue by guhjy** [workflowr/workflowr#93]
```
> devtools::install_github("jdblischak/workflowr", build_vignettes = TRUE, force=TRUE)
Downloading GitHub repo jdblischak/workflowr@master
from URL https://api.github.com/repos/jdblischak/workflowr/zipball/master
Installing workflowr
Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Downloading GitHub repo krlmlr/rprojroot@r-1.2
from URL https://api.github.com/repos/krlmlr/rprojroot/zipball/r-1.2
Installation failed: stop(github_error(request)) : 404: Not Found
 (404)

Installation failed: install_packages(package_name, repos = remote$repos, type = remote$pkg_type,      dependencies = NA, ..., quiet = quiet, out_dir = out_dir,      skip_if_log_exists = skip_if_log_exists) : formal argument "repos" matched by multiple actual arguments
Running command C:/PROGRA~1/R/R-34~1.2/bin/x64/Rcmd.exe 
Arguments:
build
--no-resave-data
--no-manual
* preparing 'workflowr':
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ...Warning: running command '"C:/PROGRA~1/R/R-34~1.2/bin/x64/Rscript" --vanilla --default-packages= -e "tools::buildVignettes(dir = '.', tangle = TRUE)"' had status 1
 ERROR
Warning in in_dir(input_dir(), evaluate(code, envir = env, new_device = FALSE,  :
Quitting from lines 231-233 (wflow-01-getting-started.Rmd) 
error: processing vignette 'wflow-01-getting-started.Rmd' failed with diagnostics:
processx error, create process: #0 execution completed
 at 'win/processx.c:678'
execution halted
Installation failed: run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),      stderr_line_callback = real_callback(stderr), stdout_callback = real_block_callback,      stderr_callback = real_block_callback, echo_cmd = echo, echo = show,      spinner = spinner, error_on_status = fail_on_status, timeout = timeout) : System command error
There were 42 warnings (use warnings() to see them)
Warning messages:
1: In readChar(proc$get_output_connection(), 2000) :
  can only read in bytes in a non-UTF-8 MBCS locale
```

```  
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Traditional)_Taiwan.950 
[2] LC_CTYPE=Chinese (Traditional)_Taiwan.950   
[3] LC_MONETARY=Chinese (Traditional)_Taiwan.950
[4] LC_NUMERIC=C                                
[5] LC_TIME=Chinese (Traditional)_Taiwan.950    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
 [1] digest_0.6.13        crayon_1.3.4        
 [3] withr_2.1.1.9000     rprojroot_1.2       
 [5] assertthat_0.2.0     mime_0.5            
 [7] R6_2.2.2             jsonlite_1.5        
 [9] backports_1.1.2      git2r_0.21.0        
[11] magrittr_1.5         httr_1.3.1          
[13] debugme_1.0.2        rlang_0.1.6.9003    
[15] cli_1.0.0            curl_3.1            
[17] rstudioapi_0.7       callr_1.0.0.9000    
[19] testthat_1.0.2       devtools_1.13.3.9000
[21] desc_1.1.1           tools_3.4.2         
[23] processx_2.0.0.1     yaml_2.1.15         
[25] compiler_3.4.2       pkgload_0.0.0.9000  
[27] pkgbuild_0.0.0.9000  memoise_1.1.0       
[29] knitr_1.18           usethis_1.1.0.9000 
```

**Comment by jdblischak** [comment]
Thanks for reporting this error, @guhjy! In the short-term, try installing without building the vignettes:

```
devtools::install_github("jdblischak/workflowr")
```

This is a new error for me. I was unable to replicate the error on my Windows 10 machine. There are multiple errors happening. One is when trying to build the workflowr vignette during installation. This shouldn't affect your workflowr experience at all (I have to use a lot of tricks to get workflowr to run inside of an R Markdown document).

However there are devtools errors that happen prior to installing workflowr:

```
formal argument "repos" matched by multiple actual arguments
```

I noticed that you have installed devtools version 1.13.3.9000. Could you please try installing the latest (1.13.4) from CRAN using `install.packages` and then re-attempting to install workflowr?

**Comment by pcarbo** [comment]
@jdblischak Did you notice that his `install_github` call above is trying to install `rprojroot` from Github? I don't know why that would happen.

```
Downloading GitHub repo krlmlr/rprojroot@r-1.2
from URL https://api.github.com/repos/krlmlr/rprojroot/zipball/r-1.2
Installation failed: stop(github_error(request)) : 404: Not Found
 (404)
```

**Comment by jdblischak** [comment]
> Did you notice that his install_github call above is trying to install rprojroot from Github? I don't know why that would happen.

@pcarbo `devtools::install_github` can be quite aggressive with installing dependencies from GitHub even if they are already installed from CRAN with `install.packages`.

But even stranger, instead of trying to install from the master branch (which is what happens when I explicitly run `devtools::install_github("krlmlr/rprojroot")` on Windows 10), it tries to install from a branch named "r-1.2", which doesn't exist (the closest existing branch is "r-1.3"). Thus the 404 error is expected, but I don't know why devtools is downloading from an unavailable branch.

**Comment by guhjy** [comment]
After I upgrade to the newest versions of RStudio and devtools, the problem has been solved. Thank you.

**Comment by jdblischak** [comment]
Great! I'm glad that was able to fix the problem, @guhjy. Just to confirm that I understand, you are now able to run `install_github` with the argument `build_vignettes = TRUE`, correct? As a test, are you able to open the Getting Started vignette with the following command?

```
vignette("wflow-01-getting-started", package = "workflowr")
```

And just a heads up, I'll be releasing version 0.10.0 soon, so you may notice the version number changing. However, this shouldn't affect your issue.

**Comment by guhjy** [comment]
Yes. I am able to run install_github with the argument "build_vignettes = TRUE".
I am able to open the Getting Started vignette with the following command: vignette("wflow-01-getting-started", package = "workflowr").
Thank you.

**Comment by jdblischak** [comment]
Thanks for your help, @guhjy!
